Test/baseResults/preprocessor.line.frag.err
Test/baseResults/preprocessor.line.frag.out
Test/baseResults/preprocessor.line.vert.out
Test/preprocessor.line.frag
Test/test-preprocessor-list
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/ParseHelper.h
glslang/MachineIndependent/ShaderLang.cpp
glslang/MachineIndependent/preprocessor/Pp.cpp

This pull request contains three commits, mainly for fixing directive handling when doing preprocessing. More details can be found in each commit's commit message. :)

Preprocessing directive handling

---

glslang/Include/Common.h
glslang/Include/InfoSink.h
glslang/MachineIndependent/preprocessor/Pp.cpp

Create a new method to return string name or number to DRY code.

Add getStringNameOrNum() in TSourceLoc.

---

glslang/MachineIndependent/Scan.cpp
glslang/MachineIndependent/preprocessor/PpScanner.cpp

Hello,
Here are two commits that optimize some slow parts of the scanner, based on some profiling I did on our use case.
Cheers,
Maxime.

Scanner optimisations

---

SPIRV/SPVRemapper.cpp
SPIRV/SPVRemapper.h

Only last commit (...fixed L/S defect) needs be merged to gitlab.

SPV Remapper: Update for 1.0 and bug fixes

---

SPIRV/GlslangToSpv.cpp
Test/baseResults/spv.420.geom.out

Fix issue https://github.com/KhronosGroup/glslang/issues/191

Enable adding capability: MultiViewport

---

gtests/Initializer.h

Gtest runs in single-threaded mode.  So the GlslangInitializer
object in the test code doesn't have to do its own synchronization.
Credit to @AWoloszyn and @antiagainst for suggesting this approach and determining this is safe to do.

Remove use of std::mutex in gtest code.

---

.appveyor.yml
SPIRV/Logger.cpp
SPIRV/Logger.h

The first commit add configuration for Windows build.
The second commit fixed a bug revealed by the Windows build.
Appveyor is approved by the Khronos Group.

Configuration for Windows buildbot & fix a bug

---

SPIRV/SpvBuilder.cpp
Test/baseResults/spv.400.frag.out
Test/baseResults/spv.420.geom.out

This change resolves the issue #244.

SPV: Add capability ImageGatherExtended if necessary.

---

glslang/MachineIndependent/intermOut.cpp

Make the include header match the usage in `is_positive_infinity`

Fix Ubuntu 16.10 build

---

glslang/MachineIndependent/ParseHelper.cpp

I'm not sure if this is the correct mechanism to implement it, but having some sort of message like this would've saved me a fair amount of time just now :)

Suggest gl_[Vertex,Instance]Index when gl_[Vertex,Instance]ID is encountered in Vulkan GLSL

---

Test/baseResults/hlsl.inoutquals.frag.out
Test/hlsl.inoutquals.frag
gtests/Hlsl.FromFile.cpp
hlsl/hlslGrammar.cpp
hlsl/hlslScanContext.cpp
hlsl/hlslTokens.h

Small change to add in/out/inout qualifiers, and a test for same.  The test has also been compiled under FXC for verification.

HLSL: add in/out/inout qualifiers

---

SPIRV/GlslangToSpv.cpp

Group invocation operations of Add, Min, Max should be applied to scalar. So we have to break vector operand to scalar operands. This is similar to some matrix operations, that are broken to vector operands to keep consist with SPIR-V spec.

SPV: Some group invocation operations should be applied to scalars.

---

StandAlone/StandAlone.cpp
hlsl/hlslParseHelper.cpp

This will get a better error message for when things fail in the HLSL conversion.

HLSL: Better error message for when HLSL translation fails

---

hlsl/hlslParseHelper.cpp

Addresses issues #475 and others. This is my first stab at interpreting HLSL SV values correctly. A few of them I'm not sure how to map to in Vulkan land, and I'm not 100% confident of the SV_TARGET stuff if it will end up in the right place based on the qualifier stuff. 
However, this change is probably far better then what's currently implemented (Which was pretty wrong).
A decision about parsing DX9 should be made at some point, right now I turned that off by default but open to discuss how that should be handled.
I have not updated the tests yet

WIP: First stab at system value interpretation

---

CMakeLists.txt
Test/baseResults/300.vert.out
Test/baseResults/420.vert.out

Please see #517 for more details.

#517: Enable AMD extensions by default

---

Test/baseResults/hlsl.array.multidim.frag.out
Test/hlsl.array.implicit-size.frag
Test/hlsl.array.multidim.frag
gtests/Hlsl.FromFile.cpp
hlsl/hlslGrammar.cpp

All the underpinnings are there; this just parses multiple array dimensions and passes them through to the existing mechanisms.
Also, minor comment fixes, and add a new test for multi-dim arrays.

HLSL: allow multi-dimensional arrays

---

StandAlone/ResourceLimits.cpp

Unfortunately, suppress only has a one line budget which gets consumed by
the "#endif" so I had to resort to something a bit more bloated.

silence -Wunknown-pragmas warnings on gcc

---

Test/baseResults/spv.register.autoassign.rangetest.frag.out
glslang/MachineIndependent/ShaderLang.cpp
glslang/MachineIndependent/iomapper.cpp
glslang/MachineIndependent/iomapper.h
glslang/Public/ShaderLang.h

Adds a resource mapping handler.
If not provided it behaves as before.

HLSL -> Spir-V: Resource mapping handler

---

glslang/MachineIndependent/iomapper.cpp

This has no functional changes.

Fix build warnings in iomapper.cpp, re-indent to glslang standard

---

glslang/MachineIndependent/preprocessor/Pp.cpp

- some paths didn't release 'res'
- token is always '\n' after proper acceptance of the directive itself,
so no need to test it, change it to '\n', etc.
- assuming setCurrentColumn(0) is not needed unless there are header tokens,
but not clear why it is ever needed
Note: much of the simplified code read as if the included header tokens had
actually been processed, versus queued up for processing; maybe that explains
some things.

PP: #include: simplify the different paths out of #include.

---

SPIRV/SPVRemapper.h
glslang/MachineIndependent/iomapper.cpp
glslang/MachineIndependent/localintermediate.h
glslang/MachineIndependent/preprocessor/PpContext.h
glslang/MachineIndependent/propagateNoContraction.cpp
glslang/MachineIndependent/reflection.h
hlsl/hlslParseHelper.cpp
hlsl/hlslParseHelper.h

These minor changes address a few small compiler warnings that have been bugging me. No functionality should be affected.

Address several compiler warnings

---

hlsl/hlslParseHelper.cpp

Improves overload handling for all EOpMethod* opcodes to allow a stricter set of functions to be in a particular overload set.
Change-Id: I60cf0b0e03da89b0e415125f1a9ffb1de7db71d4

HLSL: Improved overload handling

---

hlsl/hlslParseHelper.cpp

Fix compilation with MSVC 2010

---

hlsl/hlslParseHelper.cpp

* Removed range-based for
* Added explicit return type to non-trivial lambda
* Added explicit scope for `tInterstageIoData`
The last one I presume is just a compiler scoping quirk - it's a struct member of `HlslParseContext` so the lambda doesn't seem to have default access to it.
Tests all look OK, although it's a pretty trivial set of changes so I'd hope it's safe.
FWIW I'm probably dropping VS2010 soon for my project, because most other dependencies are sadly increasingly unsupported on that version. Take that as you wish for your own compiler support decisions :smile:.

Compile fixes for VS2010

---

glslang/Include/Types.h
glslang/MachineIndependent/iomapper.cpp
glslang/MachineIndependent/localintermediate.h
glslang/Public/ShaderLang.h
hlsl/hlslParseHelper.cpp

This change adds two things.
- Adds capture of HLSL semantics into TQualifier
- Extends TIoMapResolver to remap shader in/out variables

HLSL/TIoMapResolver: Extend to handle shader in/out variables and semantic capture

---

glslang/Include/Types.h

There were many (~8) different places in TType which all knew how to traverse the struct/type hierarchy.  There's a need to add another, but I didn't want to duplicate the traversal code again.  This is a small  refactoring which passes a predicate to a single traverse-and-test method.  That also shortens all the containsSomething() methods from 9 lines of body to 1.
There are no test diffs - it's a nonfunctional change.

Refactor TType::contains* methods (nonfunctional)

---

Test/baseResults/hlsl.constantbuffer.frag.out
Test/hlsl.constantbuffer.frag
glslang/MachineIndependent/iomapper.cpp
gtests/Hlsl.FromFile.cpp
hlsl/hlslGrammar.cpp
hlsl/hlslGrammar.h
hlsl/hlslScanContext.cpp
hlsl/hlslTokens.h

Note: multi-dimension arrays of ConstantBuffer objects will go through uniform flattening.
Fixes #838

HLSL: Add ConstantBuffer<T> syntax

---

glslang/MachineIndependent/iomapper.cpp

Fix iomapper build warnings

---

SPIRV/InReadableOrder.cpp

Previously we are using unordered_map to map to bool, which can
be simplified with unordered_set.

Use unordered_set in ReadableOrderTraverser.

---

StandAlone/StandAlone.cpp
Test/baseResults/spv.glsl.register.autoassign.frag.out
Test/baseResults/spv.glsl.register.noautoassign.frag.out
Test/baseResults/spv.noLocation.vert.out
Test/runtests
Test/spv.noLocation.vert
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/ShaderLang.cpp
glslang/MachineIndependent/iomapper.cpp
glslang/MachineIndependent/linkValidate.cpp
glslang/MachineIndependent/localintermediate.h
glslang/Public/ShaderLang.h
gtests/Link.FromFile.Vk.cpp
gtests/TestFixture.h

Also, provides an option to auto-assign locations.
Existing tests use this option, to avoid the error message,
however, it is not fully implemented yet.

SPV: Give error on not assigning locations to I/O.

---

glslang/MachineIndependent/ParseHelper.cpp

I believe this is a repeat of 12d6936.

Build: Fix linux

---

StandAlone/StandAlone.cpp
Test/runtests
Test/spv.targetOpenGL.vert
Test/spv.targetVulkan.vert
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/ShaderLang.cpp
glslang/MachineIndependent/Versions.cpp
glslang/MachineIndependent/Versions.h
glslang/Public/ShaderLang.h

Parameterize the different client APIs and target environments, and their impact on input semantics and generated code.

Compilation-environment control

---

glslang/Include/intermediate.h
hlsl/hlslParseHelper.cpp

Method rename, add comment about its intended (exceptional cases) use.  No test diffs.

HLSL: nonfunctional: rename setId -> switchId, add comment

---

glslang/MachineIndependent/preprocessor/PpScanner.cpp

GLSL: Only parse [-]1.#INF in HLSL mode.

---

SPIRV/GlslangToSpv.cpp
known_good.json

Also adds CFGCleanupPass after DeadBranchEliminationPass.

Update spirv-tools known-good

---

Test/cppIntMinOverNegativeOne.frag
glslang/MachineIndependent/preprocessor/Pp.cpp

Preprocessor: Evaluate INT_MIN % -1 to 0.

---

Test/baseResults/implicitInnerAtomicUint.frag.out
Test/implicitInnerAtomicUint.frag
glslang/MachineIndependent/ParseHelper.cpp
gtests/AST.FromFile.cpp

GLSL: Check for implicit inner dimension in array of atomic_uint.

---

Test/baseResults/constFoldIntMin.frag.out
Test/constFoldIntMin.frag
glslang/MachineIndependent/Constant.cpp
gtests/AST.FromFile.cpp

GLSL: Fold constant SHRT_MIN/INT_MIN/LLONG_MIN % -1 to 0.

---

update_glslang_sources.py

This allows this script to be executed with either python2 or python3.

Add python3 compatibility to update_glslang_sources.py

---

SPIRV/SPVRemapper.cpp

Remapper: Fix strip algo when strip ranges overlap

---

Test/baseResults/hlsl.snorm.uav.comp.out
Test/hlsl.snorm.uav.comp
gtests/Hlsl.FromFile.cpp
hlsl/hlslGrammar.cpp

This is currently parsed and ignored, save for some minor validation.
Fixes #1141

HLSL: Accept unorm and snorm on types

---

Test/baseResults/hlsl.color.hull.tesc.out
Test/hlsl.color.hull.tesc
gtests/Hlsl.FromFile.cpp
hlsl/hlslParseHelper.cpp

HLSL: Allow primitive id on hull shader input

---

glslang/MachineIndependent/ShaderLang.cpp

std::stringstream has a measurable overhead for preprocessing - it
appears that operator<< does a tiny bit of extra work for appending
chars/strings and also can't be inlined in most cases on VS2015;
additionally, std::endl triggers a stream flush which also adds up.
Replacing this with std::string buffer gets the preprocessing time down
from 180ms to 135ms in one case, making it 1.33x faster.
Note that integer-to-string conversion is using std::to_string; in
theory this could be slower than sprintf or manual conversion, but I
haven't found these cases to affect preprocessing time in practice
(std::to_string would always use the short string buffer for
line/version numbers, and the number of calls is not too significant).

Preprocessor: Use std::string instead of std::stringstream

---

update_glslang_sources.py

--site <site-name> must be added to command for new capability.
Default is github.

Upgrade update_glslang_sources.py to work with other sites

---

Test/hlsl.wavebroadcast.comp
hlsl/hlslParseables.cpp

Was using WaveReadFirstLane previously...
@antiagainst spotted this thanks!

WaveReadLaneFirst is the correct wording 

---

glslang/MachineIndependent/ShaderLang.cpp

Fix memory leak upon ProcessDeferred failure.

---

Test/baseResults/300.frag.out
Test/baseResults/310.frag.out
Test/baseResults/310.tese.out
Test/baseResults/320.frag.out
Test/baseResults/320.tese.out
Test/baseResults/nvShaderNoperspectiveInterpolation.frag.out
Test/nvShaderNoperspectiveInterpolation.frag
glslang/MachineIndependent/Scan.cpp
glslang/MachineIndependent/Versions.cpp
glslang/MachineIndependent/Versions.h
glslang/MachineIndependent/glslang.y
glslang/MachineIndependent/glslang_tab.cpp
glslang/MachineIndependent/glslang_tab.cpp.h
gtests/AST.FromFile.cpp
gtests/Spv.FromFile.cpp

Extension documentation:
https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_noperspective_interpolation.txt

Add support for GL_NV_shader_noperspective_interpolation

---

glslang/MachineIndependent/ShaderLang.cpp

`CreateParseContext` can return null, so I added a check before dereferencing its returned pointer. Returning early after failure would require adding a bunch of explicit delete statements in `ProcessDeferred`, so I used `std::unique_ptr` to handle that automatically. There was also a really weird ternary expression for `versionNotFirst`.

Minor cleanup in ShaderLang.cpp

---

glslang/MachineIndependent/Intermediate.cpp

The transform removes sampler arguments from functions and function
calls; this causes function arguments to change their indices. When some
function arguments have an output qualifier, this qualifier can get lost
because of the removal which can lead to incorrect results (e.g. out
qualifier not having effect).
To fix this we iterate through both seq & qual arrays in lock-step and
manually remove/replace entries as appropriate.

Fix TextureUpgradeAndSamplerRemovalTransform when used with qualifiers

---

glslang/MachineIndependent/iomapper.cpp

Previously if you had code like the following:
```
uniform r_values {
float val;
} r_arr[5];
uniform g_values {
float val;
} g_arr[5];
```
it would assign binding 0 to r_arr and binding 1 to g_arr. This means that the binding for g_arr collides with r_arr because r_arr uses 5 consecutive bindings. This pull request tries to fix that.

Take into account arrays of opaque types with --auto-map-bindings

---

Test/baseResults/spv.unit1.frag.out
Test/spv.unit1.frag
Test/spv.unit2.frag
Test/spv.unit3.frag
glslang/Include/Types.h
glslang/MachineIndependent/linkValidate.cpp
glslang/MachineIndependent/localintermediate.h

Link: Merge all downstream consumed intermediate modes.

---

.appveyor.yml

Fixes https://github.com/KhronosGroup/glslang/issues/1396

Appveyor CI: build artifacts for x64

---

SPIRV/GlslangToSpv.cpp
glslang/MachineIndependent/reflection.h

Fix -Wignored-qualifier and -Wunused-variable warnings

---

SPIRV/GlslangToSpv.cpp

Stop including an internal SPIRV-Tools header. It has been
deleted.
Fixes #1477

Use our own SPIRV-Tools message stringifier

---

SPIRV/SpvTools.cpp

Fix build. This morning this typo led to fail of tests of my project.

Fixed a typo leading to compilation error.

---

glslang/MachineIndependent/Initialize.cpp
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/Versions.cpp
glslang/MachineIndependent/Versions.h

https://github.com/KhronosGroup/Vulkan-Docs/issues/796

Add GL_EXT_shader_atomic_int64

---

glslang/MachineIndependent/ShaderLang.cpp

Had missed a case label in DeduceVersionProfile
Tagging @johnkslang for visibility

Fix missing case label for miss stage.

---

BUILD.gn

Sorry for the churn on this, PTAL @johnkslang @dj2

BUILD.gn: only use complete_static_lib on mac

---

CMakeLists.txt

PCH filename depends on current binary dir

---

SPIRV/GlslangToSpv.cpp
SPIRV/SpvBuilder.cpp
SPIRV/SpvBuilder.h
Test/baseResults/hlsl.pp.line3.frag.out
glslang/MachineIndependent/localintermediate.h
glslang/MachineIndependent/preprocessor/Pp.cpp

Create separate OpSource for each included file when compiling -g

---

Test/baseResults/440.vert.out
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/linkValidate.cpp
glslang/MachineIndependent/localintermediate.h
hlsl/hlslParseHelper.cpp

Add int64 support in XFB. Change containsDouble to contains64BitType. Make it more general.

Fix xfb_stride incorrectness(#1654)

---

Test/320.comp
Test/baseResults/320.comp.out
glslang/MachineIndependent/Initialize.cpp

@chaoc I think this was broken by beae2251b.
See #1823 for more detail.

ESSL: Fix #1823: Conditions for when derivatives are in compute shader.

---

BUILD.gn
CMakeLists.txt
SPIRV/GlslangToSpv.cpp
glslang/Include/Types.h
glslang/MachineIndependent/ParseHelper.h
glslang/MachineIndependent/iomapper.h
glslang/Public/ShaderLang.h

These are causing integration issues with Chromium down stream since
it is more strict about these.

Remove unnecessary semi-colons and add warning about them

---

README.md

Knowing this in advance would have saved me some time.

Update README.md to include other test requirements

---

StandAlone/StandAlone.cpp

Fixes: bd97b6f9 ("Command-line: Give better error messages. From #1829.")

standalone: Fix --help

---

CMakeLists.txt

RTTI is required in some cases.
So I add an option to make RTTI enabled.

Add an option to make RTTI enabled

---

Test/baseResults/hlsl.pp.line4.frag.out
glslang/MachineIndependent/preprocessor/Pp.cpp
glslang/MachineIndependent/preprocessor/PpContext.cpp
glslang/MachineIndependent/preprocessor/PpContext.h
glslang/MachineIndependent/preprocessor/PpScanner.cpp

disable escape sequences for #line and #error

---

SPIRV/disassemble.cpp

Use strcmp for all of the extended instruction set checks in the disassembler

---

Test/baseResults/rayQuery.rgen.out
Test/rayQuery-allOps.Error.rgen
Test/rayQuery-allOps.comp
Test/rayQuery-allOps.frag
Test/rayQuery-allOps.rgen
Test/rayQuery-committed.Error.rgen
Test/rayQuery-decls.rgen
Test/rayQuery-initialize.rgen
Test/rayQuery-no-cse.rgen
Test/rayQuery.rgen
glslang/MachineIndependent/Scan.cpp

GL_EXT_ray_query acceleration structure issue #2152 (https://github.com/KhronosGroup/glslang/issues/2152)

GL_EXT_ray_query accelerationStructureEXT 

---

SPIRV/hex_float.h
StandAlone/StandAlone.cpp
StandAlone/spirv-remap.cpp
glslang/MachineIndependent/SymbolTable.cpp
glslang/MachineIndependent/reflection.cpp
hlsl/hlslParseHelper.cpp

I'd comment just only changing bit operation to logical. It's ok but it will be cast from bool to int (iso cpp 4.5.6).

Humble fix

---

Test/150.frag
Test/baseResults/150.frag.out
glslang/MachineIndependent/Initialize.cpp
glslang/MachineIndependent/Versions.cpp
glslang/MachineIndependent/Versions.h

This extension enables the extension GL_ARB_shader_bit_encoding

Add support for extension GL_ARB_shader_bit_encoding

---

glslang/MachineIndependent/Initialize.cpp

This variable is no longer used, remove.

Remove unused Es310Desktop430

---

SPIRV/GlslangToSpv.cpp
Test/310.frag
Test/baseResults/310.frag.out
Test/baseResults/versionsErrors.frag.out
glslang/MachineIndependent/Intermediate.cpp
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/Versions.cpp
glslang/MachineIndependent/Versions.h
glslang/MachineIndependent/intermOut.cpp
glslang/MachineIndependent/localintermediate.h

Updated extension management in TIntermediate class.

Add support for extension GL_EXT_shader_implicit_conversions

---

StandAlone/ResourceLimits.cpp
Test/100.frag
Test/300.frag
Test/baseResults/100.frag.out
Test/baseResults/300.frag.out
Test/baseResults/test.conf
glslang/Include/BaseTypes.h
glslang/Include/ResourceLimits.h
glslang/Include/glslang_c_interface.h
glslang/MachineIndependent/Initialize.cpp
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/Versions.cpp
glslang/MachineIndependent/Versions.h
glslang/OSDependent/Web/glslang.js.cpp

* Introduces builtin variables gl_SecondaryFragColorEXT and gl_SecondaryFragDataEXT
* Introduces builtin constant gl_MaxDualSourceDrawBuffersEXT
* enables support for layout qualifier "index" in es profile

Add support for es extension GL_EXT_blend_func_extended

---

glslang/MachineIndependent/Initialize.cpp

This small change fixes the web build :)

Fix Web build

---

Test/330.frag
Test/baseResults/330.frag.out
glslang/MachineIndependent/Intermediate.cpp

Add check for DOUBLE in low versions, fix issue #2206

Add check for DOUBLE in low versions

---

SPIRV/GlslangToSpv.cpp
Test/baseResults/spv.ext.RayPrimCull_Errors.rgen.out
Test/rayQuery-allOps.comp
Test/spv.ext.RayGenShader.rgen
Test/spv.ext.RayPrimCull_Errors.rgen
glslang/Include/Types.h
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/localintermediate.h
gtests/Spv.FromFile.cpp

Fixes https://gitlab.khronos.org/vulkan/vulkan/issues/2073

Add support for primitive culling layout qualifier.

---

Test/baseResults/hlsl.hull.6.tesc.out
Test/hlsl.hull.6.tesc
gtests/Hlsl.FromFile.cpp
hlsl/hlslParseHelper.cpp

Fix missing patch decoration for TessFactor PCF arg

---

CMakeLists.txt

CMake: Error on unresolved symbols

---

BUILD.gn

We're turning these on in ANGLE and want to keep the build clean.

Suppress two override suggestion warnings.

---

SPIRV/SpvTools.cpp
SPIRV/SpvTools.h
StandAlone/CMakeLists.txt
gtests/CMakeLists.txt

This addresses the problems highlighted in: https://github.com/KhronosGroup/glslang/issues/2405

Improved SpirvToolsDisassemble interface and documentation.

---

kokoro/linux-clang-gn/build-docker.sh
kokoro/linux-clang-gn/build.sh

Kokoro: Add configurations for GN presubmit

---

glslang/MachineIndependent/iomapper.cpp

Fix warning in iomapper.

---

glslang/MachineIndependent/Initialize.cpp

Fixes a crash in ANGLE.
Closes: #2452

Compile out code for GL_EXT_shader_image_int64 for ANGLE

---

.travis.yml

Fix Travis to use pre-breakage googletest

---

README.md

Update README to avoid googletest breakage

---

glslang/HLSL/hlslParseHelper.cpp

Fix tess factor cut and paste error

---

StandAlone/StandAlone.cpp

Prevent HLSL input under OpenGL semantics

---

Test/baseResults/negativeWorkGroupSize.comp.out
Test/negativeWorkGroupSize.comp
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/localintermediate.h
gtests/AST.FromFile.cpp

Require fixed workgroup size declaration

---

glslang/MachineIndependent/Constant.cpp

Replace the old version math func with C++11 to prevent some presicion issue.
reference link:
https://www.cplusplus.com/reference/cmath/
Signed-off-by: ZhiqianXia <xzq0528@outlook.com>

Replace log2 and exp2 math func.

---

glslang/MachineIndependent/ShaderLang.cpp
glslang/Public/ShaderLang.h

fix variable capitalization. Don't initialize it in the struct's constructor

---

glslang/MachineIndependent/linkValidate.cpp

Don't check precision qualifiers on cross-stage checks

---

SPIRV/GlslangToSpv.cpp
Test/baseResults/spv.bufferhandle1.frag.out
Test/baseResults/spv.bufferhandle10.frag.out
Test/baseResults/spv.bufferhandle11.frag.out
Test/baseResults/spv.bufferhandle12.frag.out
Test/baseResults/spv.bufferhandle13.frag.out
Test/baseResults/spv.bufferhandle14.frag.out
Test/baseResults/spv.bufferhandle15.frag.out
Test/baseResults/spv.bufferhandle16.frag.out
Test/baseResults/spv.bufferhandle18.frag.out
Test/baseResults/spv.bufferhandle2.frag.out
Test/baseResults/spv.bufferhandle3.frag.out
Test/baseResults/spv.bufferhandle4.frag.out
Test/baseResults/spv.bufferhandle5.frag.out
Test/baseResults/spv.bufferhandle6.frag.out
Test/baseResults/spv.bufferhandle7.frag.out
Test/baseResults/spv.bufferhandle8.frag.out
Test/baseResults/spv.bufferhandle9.frag.out
Test/baseResults/spv.coopmat.comp.out
Test/baseResults/spv.intcoopmat.comp.out

Default to KHR extension

---

glslang/Include/intermediate.h

As titled, this PR adds a setter for TInterimSelection.condition.

Add setter for TInterimSelection.condition

---

Test/baseResults/hlsl.includeNegative.vert.out
glslang/HLSL/hlslGrammar.cpp

Issue error when declaration rule fails

---

glslang/Public/ShaderLang.h

Fixes mingw build 
Closes #2460

Dont export inline TObjectReflection::getType()

---

.appveyor.yml
.travis.yml

GenericCodeGen, MachineIndependent and glslang-default-resource-limits
Fixes #2648

Add missing libs to release

---

glslang/MachineIndependent/Constant.cpp

Fixes #2652 
Signed-off-by: Shahbaz Youssefi <ShabbyX@gmail.com>

Fix UBSAN error with negating 0x8000'0000

---

Test/baseResults/vulkan.ast.vert.out
Test/vulkan.ast.vert
glslang/MachineIndependent/ParseHelper.cpp

Add support for float spec const vector initialization

---

SPIRV/GlslangToSpv.cpp
glslang/HLSL/hlslParseHelper.cpp

Fix some instances of -Wunused-but-set-variable.

---

Test/GL_ARB_gpu_shader5.u2i.vert
Test/baseResults/GL_ARB_gpu_shader5.u2i.vert.out
glslang/MachineIndependent/Intermediate.cpp
glslang/MachineIndependent/localintermediate.h
gtests/AST.FromFile.cpp

Signed-off-by: ZhiqianXia <xzq0528@outlook.com>

Support Uint to Int implicit conversions at #extension GL_ARB_gpu_shader5.

---

Test/spv.scalarlayout.frag
glslang/MachineIndependent/ParseHelper.cpp

Allow layout(std430) uniform with GL_EXT_scalar_block_layout

---

glslang/MachineIndependent/ParseHelper.cpp

Run update_precision() on array and matrix constructors.

---

SPIRV/GlslangToSpv.cpp
glslang/MachineIndependent/Constant.cpp
glslang/MachineIndependent/ParseHelper.h
glslang/MachineIndependent/attribute.cpp
glslang/MachineIndependent/glslang.m4
glslang/MachineIndependent/glslang.y
glslang/MachineIndependent/glslang_tab.cpp

Fix -Wsign-compare warnings.
Fix -Wunused-parameter warnings.

Fix GCC warnings

---

Test/baseResults/hlsl.samplebias.offset.dx10.frag.out
Test/baseResults/hlsl.samplebias.offsetarray.dx10.frag.out
glslang/HLSL/hlslParseHelper.cpp
glslang/HLSL/hlslParseables.cpp

Fix SPIR-V for HLSL SampleBias

---

Test/baseResults/link.tesselation.tese.out
Test/baseResults/link.tesselation.vert.out
Test/link.tesselation.frag
Test/link.tesselation.tesc
Test/link.tesselation.tese
Test/link.tesselation.vert
glslang/MachineIndependent/linkValidate.cpp
gtests/Link.FromFile.cpp

Include EvqVaryingIn as part of TessControl/TessEvaluation test in isIoResizeArray()

Fix isIoResizeArray() tessellation stage handling

---

SPIRV/GlslangToSpv.cpp

Fix unreachable code in getSampledType()

---

glslang/MachineIndependent/glslang.m4
glslang/MachineIndependent/glslang.y
glslang/MachineIndependent/glslang_tab.cpp

Fix variable scoping of do-while

---

glslang/Include/Common.h
glslang/MachineIndependent/Constant.cpp
glslang/MachineIndependent/intermOut.cpp

Reverts KhronosGroup/glslang#2803

Revert "Use intermOut.cpp's IsNan and IsInfinity for parse-time constant folding"

---

Test/BestMatchFunction.vert
Test/baseResults/BestMatchFunction.vert.out
glslang/MachineIndependent/ParseHelper.cpp
gtests/AST.FromFile.cpp

Fix the issue https://github.com/KhronosGroup/glslang/issues/2697.

#extension GL_ARB_gpu_shader5 support the implicit conversion ,

---

StandAlone/StandAlone.cpp
Test/baseResults/hlsl.w-recip.frag.out
Test/hlsl.w-recip.frag
Test/runtests
glslang/HLSL/hlslParseHelper.cpp
glslang/MachineIndependent/ShaderLang.cpp
glslang/MachineIndependent/linkValidate.cpp
glslang/MachineIndependent/localintermediate.h
glslang/Public/ShaderLang.h

This reciprocates the w component of SV_Position in HLSL fragment shaders
to provide DirectX compatibility for HLSL shaders in Vulkan.
Fixes #2244

Add --hlsl-dx-position-w option

---

Test/baseResults/iomap.blockOutVariableIn.2.vert.out
Test/baseResults/iomap.blockOutVariableIn.vert.out
Test/baseResults/iomap.variableOutBlockIn.2.vert.out
Test/baseResults/iomap.variableOutBlockIn.vert.out
Test/iomap.blockOutVariableIn.2.vert
Test/iomap.blockOutVariableIn.frag
Test/iomap.blockOutVariableIn.geom
Test/iomap.blockOutVariableIn.vert
Test/iomap.variableOutBlockIn.2.vert
Test/iomap.variableOutBlockIn.frag
Test/iomap.variableOutBlockIn.geom
Test/iomap.variableOutBlockIn.vert
glslang/MachineIndependent/iomapper.cpp
glslang/MachineIndependent/linkValidate.cpp
gtests/GlslMapIO.FromFile.cpp

This PR fixes an issue with separable shader validation.

Fix issue with separable shader validation in iomapper

---

README.md

I had copy/pasted this badge without really thinking about it's
usefulness. It is unnecessary.

Remove unnecessary badge

---

Test/baseResults/hlsl.w-recip2.frag.out
Test/hlsl.w-recip2.frag
Test/runtests
glslang/HLSL/hlslParseHelper.cpp
glslang/HLSL/hlslParseHelper.h

Fix --hlsl-dx-position-w to work for SV_Position embedded in struct

---

SPIRV/GlslangToSpv.cpp
Test/baseResults/spv.ClosestHitShaderMotion.rchit.out
Test/baseResults/spv.MissShaderMotion.rmiss.out
Test/baseResults/spv.RayGenShaderMotion.rgen.out
Test/baseResults/spv.ext.AnyHitShader.rahit.out
Test/baseResults/spv.ext.ClosestHitShader.rchit.out
Test/baseResults/spv.ext.ClosestHitShader_Subgroup.rchit.out
Test/baseResults/spv.ext.MissShader.rmiss.out
Test/baseResults/spv.ext.RayCallable.rcall.out
Test/baseResults/spv.ext.RayConstants.rgen.out
Test/baseResults/spv.ext.RayGenSBTlayout.rgen.out
Test/baseResults/spv.ext.RayGenSBTlayout140.rgen.out
Test/baseResults/spv.ext.RayGenSBTlayout430.rgen.out
Test/baseResults/spv.ext.RayGenSBTlayoutscalar.rgen.out
Test/baseResults/spv.ext.RayGenShader.rgen.out
Test/baseResults/spv.ext.RayGenShader11.rgen.out
Test/baseResults/spv.ext.RayGenShaderArray.rgen.out
Test/baseResults/spv.ext.World3x4.rahit.out

Fixes #2736 
@greg-lunarg to review

Do not output location decoration for certain variables in ray tracing storage classes.

---

Test/baseResults/noMatchingFunction.frag.out
Test/noMatchingFunction.frag
glslang/Include/Types.h
glslang/MachineIndependent/ParseHelper.cpp
gtests/AST.FromFile.cpp

Check types before accessing typeName.
Fix #2848.

Fix seg fault

---

Test/baseResults/xfbUnsizedArray.error.tese.out
Test/xfbUnsizedArray.error.tese
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/linkValidate.cpp
gtests/AST.FromFile.cpp

Unblock unsized error from assert

---

Test/baseResults/150.frag.out
Test/baseResults/floatBitsToInt.vert.out
Test/floatBitsToInt.vert
glslang/MachineIndependent/Initialize.cpp
gtests/AST.FromFile.cpp

fix the issue https://github.com/KhronosGroup/glslang/issues/2698.

Support the floatBitsToint function at GL_ARB_gpu_shader5 Extension.

---

glslang/Public/ShaderLang.h

Specifically, add text to clarify dialect and dialectVersion
Fixes #2872

Fix comment for setEnvInput()

---

SPIRV/SpvTools.cpp
SPIRV/spirv.hpp
StandAlone/StandAlone.cpp
Test/baseResults/hlsl.spv.1.6.discard.frag.out
Test/baseResults/spv.1.6.conditionalDiscard.frag.out
Test/baseResults/spv.1.6.helperInvocation.frag.out
glslang/CInterface/glslang_c_interface.cpp
glslang/Include/glslang_c_shader_types.h
glslang/MachineIndependent/localintermediate.h
glslang/Public/ShaderLang.h
gtests/Hlsl.FromFile.cpp
gtests/Spv.FromFile.cpp
known_good.json

Also update known goods to Vulkan 1.3 support
Also re-enable SPIR-V 1.6 tests with vulkan1.3 target
Also re-cache SPIRV 1.6 header which somehow regressed back to 1.5

Add Vulkan 1.3 support

---

known_good.json

Picking up some spirv-tools bug fixes

Update spirv-tools known good

---

Test/baseResults/150.frag.out
Test/baseResults/gl_FragCoord.frag.out
Test/gl_FragCoord.frag
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/localintermediate.h
gtests/AST.FromFile.cpp

fix issue https://github.com/KhronosGroup/glslang/issues/2898

The first redeclarations of gl_FragCoord must appear before any use.

---

StandAlone/StandAlone.cpp

Depfiles are basically Makefiles, with some special character rules. In particular, the `:` and `\` characters are special, and they will be present in any well-formed path on Windows.
This change adds character escaping to make depfiles work correctly on Windows. Verified with the Meson depfile parser, which can be found here: https://github.com/mesonbuild/meson/blob/master/mesonbuild/depfile.py 
In addition, the duplicate `it` variables were renamed for clarity.

Make depfiles compatible with Windows paths

---

known_good.json

To pick up support for spirv-opt --eliminate-dead-input-components

Update spirv-tools and spirv-headers known good

---

glslang/Include/glslang_c_shader_types.h

Improved comment for glslang_optimization_level_t

---

glslang/MachineIndependent/ParseHelper.cpp

Disable layout error check for RT ops in presence of EXT_spirv_intrinsics

---

Test/baseResults/hlsl.instance.geom.out
Test/hlsl.instance.geom
glslang/HLSL/hlslParseHelper.cpp
gtests/Hlsl.FromFile.cpp

Hi there! 
During my analysis of the MS's DXC behavior on the management of the attribute "instance" for the geometry shader, 
I saw a different result. In the DXC translation, it is translated as 
```
OpExecutionMode %geometry Invocations <number>
```
Instead, in GLSlang, it is ignored (i.e. Invocations is always 1) and it is quite annoying in my scenario (CSM algorithm).
Thus, I propose this "small" change of the "handleEntryPointAttributes" method, with the aims to set the invocations param when the "instance" token is read.
---
This is an example:
```HLSL
#define IVec2 int2
#define IVec3 int3
#define IVec4 int4
#define IMat3 int3x3
#define IMat4 int4x4
#define Vec2 float2
#define Vec3 float3
#define Vec4 float4
#define Mat3 float3x3
#define Mat4 float4x4
#define DVec2 double2
#define …
```

HLSL Instance attribute translated as spirv invocations attribute

---

CMakeLists.txt

Fix build for clang + mingw32-make

---

glslang/MachineIndependent/localintermediate.h

Fix getEnhancedMsgs to work when HLSL not enabled

---

.appveyor.yml

Update release description

---

.github/workflows/continuous_deployment.yml
.github/workflows/continuous_integration.yml

Per https://github.com/actions/virtual-environments/issues/5583
Fix #2984

Update MacOS runner

---

.github/workflows/continuous_deployment.yml

Reverts KhronosGroup/glslang#2988

Revert "Fix: Build arm64 binaries for macOS"

---

glslang/MachineIndependent/linkValidate.cpp

since we are changing the type before the visitBinary now, we need to be comparing against the new type.
Previous test cases worked since the 'unitType' was a shallow copy and ended up getting updated in some cases to match the new type, but not all.

Improve naming in link validation

---

glslang/Public/resource_limits_c.h

Fix include in resource_limits_c.h

---

CMakeLists.txt

Guard AppleClang linker options

---

Test/baseResults/implicitArraySize.vert.out
Test/baseResults/implicitArraySize1.geom.out
Test/baseResults/implicitArraySizeBuiltin.vert.out
Test/implicitArraySize.frag
Test/implicitArraySize.vert
Test/implicitArraySize1.geom
Test/implicitArraySize2.geom
Test/implicitArraySizeBuiltin.geom
Test/implicitArraySizeBuiltin.vert
glslang/Include/Types.h
glslang/Include/arrays.h
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/linkValidate.cpp
gtests/Link.FromFile.cpp

Help to check builtin and other variables if across stages.

[glslang] Refine implicit array size interfaces.

---

CMakeLists.txt

Remove languages from cmake project statement

---

Android.mk
BUILD.bazel

These defines aren't needed anymore

build: Remove AMD_EXTENSIONS / NV_EXTENSIONS defines

---

Test/baseResults/struct.error.frag.out
Test/struct.error.frag
glslang/MachineIndependent/ParseHelper.cpp
gtests/AST.FromFile.cpp

Fix crash on bad structure member reference

---

README.md

Notify users of upcoming default branch rename. See #3107.

Update readme with upcoming branch rename

---

CMakeLists.txt
glslang/CMakeLists.txt

Fix installation of resource limits headers

---

SPIRV/SpvBuilder.cpp
glslang/HLSL/hlslParseHelper.cpp

A couple of small refactors, no functional change.
Fixes #3142.

A couple of small refactors

---

.github/workflows/continuous_integration.yml

ci: Test GCC on MacOS CI

---

Test/baseResults/hlsl.function.frag.out
Test/baseResults/hlsl.init2.frag.out
Test/hlsl.function.frag
Test/hlsl.init2.frag
glslang/HLSL/hlslGrammar.cpp
glslang/HLSL/hlslGrammar.h

Added the ability to define a variable as const after declaring the type of the variable
Fix for Issue: https://github.com/KhronosGroup/glslang/issues/3092

HLSL keyword declaration after declared type

---

CMakeLists.txt

Support MinGW build with Clang, not just GCC

---

.github/workflows/continuous_integration.yml

- Test Ubuntu-22.04
- Use ccache
- Ensure backwards compatibility with Ubuntu-20.04

Modernize linux CI

---

StandAlone/CMakeLists.txt

respect destdir for compat symlink

---

.github/workflows/scorecard.yml
README.md

Closes #3299 
Hi there, here is the configuration file for the OpenSSF Scorecard Action and its badge, let me know if you have any doubts or concerns!

Enable OpenSSF Scorecard and Badge

---

SPIRV/GlslangToSpv.cpp
glslang/Include/SpirvIntrinsics.h
glslang/MachineIndependent/SpirvIntrinsics.cpp

This PR is try to address the review comment:
https://github.com/KhronosGroup/glslang/pull/3253#discussion_r1254932979.

Use std::variant to represent TSpirvTypeParameter

---

SPIRV/CInterface/spirv_c_interface.cpp

This will prevent any recurrence of issues like the one addressed by PR #3364.

Initialize spv_options in glslang_program_SPIRV_generate

---

SPIRV/GlslangToSpv.cpp

Some code paths could be shared.

Add a helper applySpirvDecorate to handle spirv_decorate_xxx directives

---

.github/workflows/continuous_integration.yml

NDK 23.2.8568313 was removed from the latest runner

Fix Android CI

---

CMakeLists.txt

cmake: Cleanup usage of option

---

.github/workflows/continuous_integration.yml

Along with minor commits addressing comments in this file.

Cleanup MacOS CI

---

SPIRV/GlslangToSpv.cpp
SPIRV/SpvBuilder.cpp
SPIRV/SpvBuilder.h

paramNames was going unused in makeFunctionEntry

Fix unused parameter warning

---

CMakeLists.txt

Min is 3.17 checks for 3.16 are no longer needed.

Cleanup ENABLE_PCH

---

.github/workflows/continuous_integration.yml
CMakeLists.txt
External/CMakeLists.txt
README.md
gtests/CMakeLists.txt

1 variable instead of ENABLE_CTEST and BUILD_TESTING.
OFF by default. See README.md for explanation.

Add GLSLANG_TESTS option

---

SPIRV/GlslangToSpv.cpp
Test/spv.maximalReconvergence.vert
glslang/MachineIndependent/attribute.cpp
glslang/MachineIndependent/attribute.h
glslang/MachineIndependent/intermOut.cpp
glslang/MachineIndependent/localintermediate.h

See discussion at https://github.com/KhronosGroup/GLSL/pull/227#discussion_r1467007040.

Fix 'maximally_reconverges' token to match the GLSL spec

---

CMakeLists.txt
README.md

As discussed in https://github.com/KhronosGroup/glslang/pull/3519#issuecomment-1947281793

Document that the only supported dependency commits are the ones in known_good.json

---

SPIRV/GlslangToSpv.cpp
SPIRV/SpvBuilder.cpp
SPIRV/spvIR.h

@jeremy-lunarg,
This PR changes very affect on performance Release and Debug configuration.

Maximum optimization inserts using reserve() for operands

---

README-spirv-remap.txt

Update the "feedback" section with the new preferred feedback channel.

Update the README-spirv-remap.txt

---

SPIRV/GlslangToSpv.cpp

We know the count inserted elements, we can optimize codegeneration.

Using reserve() in GlslangToSpv.cpp

---

README.md

Following the discussion in #3583

readme: added a note about STACK_SIZE Emscripten compiler setting

---

glslang/MachineIndependent/ShaderLang.cpp
glslang/Public/ShaderLang.h

add back layoutLocation to public API

---

Test/baseResults/150.geom.out
glslang/MachineIndependent/ParseHelper.cpp
glslang/MachineIndependent/ShaderLang.cpp

Hello,
While updating the Debian package of glslang, Lintian (the package quality tool) noticed several typos in the source code. Here is a patch that fixes them.

Fix few typos

---

Android.mk

This should fix kokoro Android CI.

Fix typo in Android.mk

---

Test/baseResults/hlsl.buffer-offsets.comp.out

The change was rebased but one test was added in the meantime.

Fix test results after merging #3662

---

glslang/MachineIndependent/ShaderLang.cpp

Propagate errors from symbol table init

---

.gitignore

Add clangd .cache to .gitignore

Ignore clangd .cache

---

StandAlone/StandAlone.cpp

This is for C++ modules build in chromium.

Add missing include headers

---

SPIRV/CMakeLists.txt
glslang/stub.cpp

Fix spirv backcompat

---

.github/workflows/continuous_deployment.yml
.github/workflows/continuous_integration.yml

Update Ubuntu runners

---

CHANGES.md

Fix incorrect date in CHANGES.md
