KhronosGroup/glslang

SPIRV/SPVRemapper.h
Compilation fails if the root folder is anything other than `glslang`.
=> Fix include directive depending on root folder name

glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h, glslang/MachineIndependent/glslang.y
New extensions in glext.h follow the pattern:
#ifndef GL_ARB_texture_rectangle
#define GL_ARB_texture_rectangle 1
#define GL_TEXTURE_RECTANGLE_ARB          0x84F5
#define GL_TEXTURE_BINDING_RECTANGLE_ARB  0x84F6
#define GL_PROXY_TEXTURE_RECTANGLE_ARB    0x84F7
#define GL_MAX_RECTANGLE_TEXTURE_SIZE_ARB 0x84F8
#endif /* GL_ARB_texture_rectangle */
Versions.h tries to declare:
const char* const GL_ARB_texture_rectangle = "GL_ARB_texture_rectangle";
Which means, if you've included glext.h before Versions.h, that the
compiler will see "const char* const 1 = ...", and rightly refuse to
continue.
The ham-fisted approach taken here is to rename the variables in
Versions.h with a leading underscore.  This does sort of undermine the
comment about "better to have the compiler do spelling checks", …
=> Fix incompatibility with <GL/glext.h>

SPIRV/SpvBuilder.cpp, SPIRV/doc.h, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/preprocessor/PpContext.h
This PR fixes the following warnings when compiled with latest clang in Xcode7 on OSX 10.11, there are 2 warnings remaining which I need advice on how to fix (see below).
The tests are running successfully.
```
In file included from /Users/floh/projects/glslang/SPIRV/SPVRemapper.cpp:37:
/Users/floh/projects/glslang/SPIRV/doc.h:217:9: warning: field 'resultPresent' will be initialized after field 'opDesc' [-Wreorder]
resultPresent(true),       // most normal, only exceptions have to be spelled out
/Users/floh/projects/glslang/SPIRV/SpvBuilder.cpp:1217:5: warning: variable 'resultType' is used uninitialized whenever switch default is taken [-Wsometimes-uninitialized]
default:
^~~~~~~
/Users/floh/projects/glslang/SPIRV/SpvBuilder.cpp:1221:57: note: uninitialized use occurs here
Instruction* …
```
=> Fix for most Xcode/clang warnings on OSX

OGLCompilersDLL/InitializeDll.cpp, SPIRV/GlslangToSpv.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/preprocessor/PpScanner.cpp, glslang/OSDependent/Linux/ossource.cpp
I'm not sure if this is desired, but I've made some changes so that glslang doesn't depend any directories being in the include search path (which is default for building the project, but isn't so desirable when including glslang in a larger project).
---
On a related but separate note - the same include path requirement is true for osinclude.h. The include search path needs to be set up to point to either glslang/OSDependent/Linux or glslang/OSDependent/Windows on their respective platforms. I've [changed this locally](https://github.com/baldurk/glslang/commit/c0384798d86774f6ae7c7227ef8a3e25aa9fd4ef) so that osinclude.h is included relatively like so:
```cpp
#include "../glslang/OSDependent/osinclude.h"
```
and that file just contains a simple redirect based on platform macros:
```cpp …
```
=> include by relative path, so root doesn't need to be in the search path

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, glslang/MachineIndependent/Scan.h
There were already many explicit (int) casts, so it looks like this is maybe just new code that slipped through.
=> Fix warnings compiling on x64 with size_t to int casts

glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/Versions.cpp
Lots of places in the code use `extensionsTurnedOn(1, ...)`. This
patch introduces a new method, `extensionTurnedOn()`, for testing
if a single extension is turned on.
=> Simplify function calls for extensionsTurnedOn().

glslang/MachineIndependent/Scan.h
`TInputScanner` advances its internal indices to the next character at
the end of `get()`, which means, after reading in the last character
in the user-provided shader string, internal index (`currentSource`)
will point to the next shader string (`currentSource == numSources`),
which doesn't exist. Then if a location setting method is called,
we will write to some out-of-bound memory.
A test case for this is `#line 10000\n`. The `eval()` method in `CPPline()`
will evaluate `10000`, but at the same time it reads in the next
token, `\n`, and the `currentSource` will be `numSources` in `TInputScanner`.
Then a `parseContext.setCurrentLine()` is called, we are writing to
out-of-bound memory. Another test case will be `#line 10000 0\n`.
=> Protect location setting methods from writing to non-existing strings.

glslang/MachineIndependent/Scan.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h
This allows us to pass through non null-terminated strings.
=> Added a setStringsWithLengths() method to TShader.

SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h, Test/baseResults/spv.dataOutIndirect.vert.out, Test/baseResults/spv.do-simple.vert.out, Test/baseResults/spv.do-while-continue-break.vert.out, Test/baseResults/spv.doWhileLoop.frag.out, Test/baseResults/spv.for-continue-break.vert.out, Test/baseResults/spv.for-simple.vert.out, Test/baseResults/spv.forLoop.frag.out, Test/baseResults/spv.localAggregates.frag.out, Test/baseResults/spv.loops.frag.out, Test/baseResults/spv.loopsArtificial.frag.out, Test/baseResults/spv.switch.frag.out, Test/baseResults/spv.while-continue-break.vert.out, Test/baseResults/spv.while-simple.vert.out, Test/baseResults/spv.whileLoop.frag.out
After construction, the Loop is effectively const.
This perturbs the IDs in SPIR-V tests because the body block
is created before generating any of the loop code, rather than
only when the body is first referenced.
=> spv::Builder::Loop constructor inits all members.

Test/baseResults/preprocessor.extensions.vert.out, Test/preprocessor.extensions.vert, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/preprocessor/Pp.cpp
Preprocessing output shouldn't contain extensions enabled as
dependencies.
=> Only output explicit extension directives in preprocessing.

glslang/MachineIndependent/ShaderLang.cpp
These two patches fix the line number handling in preprocessing. It's the preliminary work mentioned in Issue #37.
=> Preprocessing line number handling

glslang/Include/Common.h
Broke in https://github.com/KhronosGroup/glslang/commit/2f273369e4f78af8c5b1bc558eb7809e1cb69e02 with this error (I think this is a XCode bug):
```c++
In file included from /Users/fkaaman/Dev/glslang/glslang/MachineIndependent/ParseHelper.cpp:37:
In file included from /Users/fkaaman/Dev/glslang/glslang/MachineIndependent/ParseHelper.h:40:
In file included from /Users/fkaaman/Dev/glslang/glslang/MachineIndependent/../Include/ShHandle.h:49:
In file included from /Users/fkaaman/Dev/glslang/glslang/MachineIndependent/../Include/InfoSink.h:38:
In file included from /Users/fkaaman/Dev/glslang/glslang/MachineIndependent/../Include/../Include/Common.h:65:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/unordered_map:724:5: error: …
```
=> Fix missing const qualifier on TUnorderedMap template type

Test/baseResults/preprocessor.cpp_style___FILE__.vert.out, Test/baseResults/preprocessor.cpp_style_line_directive.vert.err, Test/preprocessor.cpp_style___FILE__.vert, Test/preprocessor.cpp_style_line_directive.vert, Test/test-preprocessor-list, glslang/Include/Common.h, glslang/Include/InfoSink.h, glslang/Include/Types.h, glslang/Include/intermediate.h, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/Scan.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h, glslang/MachineIndependent/localintermediate.h, glslang/MachineIndependent/preprocessor/Pp.cpp
According to the GLSL spec, the second parameter to `#line` should be
an integer source string number and `__FILE__` will be substituted
with the integer source string number currently processed. This
patch extends the syntax of `#line` and `__FILE__`. Now `#line` accepts
as the second parameter a filename string quoted by double quotation
marks. And if such a `#line` is set, `__FILE__` will be substituted with
the currently set filename string. The implementation is done via
introducing a new extension `GL_GOOGLE_cpp_style_line_directive` using
the extension framework.
The purpose is to support `cpp`-style `#line` directives, which is
required by `#include`.
This commit falls into the second step listed in Issue #37.
=> Extend the syntax of #line and __FILE__ to support filename strings

glslang/MachineIndependent/Scan.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h
Expose a new method `setStringsWithLengthsAndNames()` in the interface
which allows the caller to set descriptive names for source strings.
The names can then be used in error messages.
This new API will provide a way to set filenames. This is the last commit
for the second step listed in Issue #37. The next pull request will be the
implementation for the `#include` directive.
=> Add mechanism for specifying names for source strings.

glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpContext.h
The `ErrMsg` and `ifloc` members were unused or had no effect.
=> Remove unused members from TPpContext

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Scan.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/preprocessor/PpAtom.cpp, glslang/MachineIndependent/preprocessor/PpContext.h, glslang/MachineIndependent/preprocessor/PpScanner.cpp, glslang/MachineIndependent/preprocessor/PpSymbols.cpp
Some of these fixes are safe & sensible like #ifdef'ing out windows only #pragmas, re-ordering constructor arguments.
The casts between unsigned and signed ints are less clear-cut, so this pull request isn't necessarily to take as-is if you don't want to bandage over things, but to raise these as issues. If there's a refactor that would be better let me know and I can look into doing it, or I can drop them from this PR if you'd rather take just the other fixes.
I also removed an unused variable (fragOutHasLocation) but that's maybe a warning you'd want to ignore.
=> Compile fixes for gcc -Wall

glslang/Include/Common.h, glslang/MachineIndependent/preprocessor/PpTokens.cpp
Check _MSC_VER, defining snprintf triggers a #error in the VS2015 headers. It's already defined and there to use now.
=> Fixed VS2015 build

SPIRV/SPVRemapper.cpp, StandAlone/CMakeLists.txt, glslang/Include/Common.h, glslang/MachineIndependent/intermOut.cpp, glslang/OSDependent/Linux/ossource.cpp
Primarily fix is due to Android not supporting std::to_string().
=> Fixes for compiling glslang on Android.

Test/baseResults/preprocessor.defined.vert.err, Test/preprocessor.defined.vert, Test/test-preprocessor-list, glslang/MachineIndependent/ParseHelper.cpp
=> 'defined' cannot be used as a macro name in #define or #undef.

CMakeLists.txt
Stop forcing CMAKE_INSTALL_PREFIX="install". If the user manually set
CMAKE_INSTALL_PREFIX, then trust that he knows what he's doing.
This patch does NOT change the project's default value ("install") of
CMAKE_INSTALL_PREFIX.
Change-Id: I81b46dd1986427b498fe6316bed03f01689987d4
=> cmake: Don't override CMAKE_INSTALL_PREFIX

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h
There's nothing really special about texelFetch other than the opcode and
some restrictions so adding it is pretty trivial.
This resolves issue #67
=> SPIRV: Add support for texelFetch

SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h
Depending on specific optimization settings VS2013 will sometimes
execute the operands to
new Instruction(builder.getUniqueId(), builder.makeBoolType(), OpPhi)
left-to-right, and sometimes right-to-left. Since makeBoolType can
also call getUniqueId(), the IDs to the OpPhi can sometimes be swapped.
This guarantees an explicit ordering of the Ids so that tests work
reliably.
=> Fixed subtle issue that causes tests to fail in VS2013 in some configs.

glslang/MachineIndependent/preprocessor/Pp.cpp
This fixes compilation in build environments with stricter warnings enabled
=> Replace sprintf() usage with snprintf()

SPIRV/disassemble.cpp, glslang/MachineIndependent/SymbolTable.cpp
Encountered with GCC-4.7.3 in a build environment where warnings are enabled
and treated as errors.
=> Various build fixes when using newer GCC versions with warnings enabled

glslang.vcxproj, glslang.vcxproj.filters, glslang/CMakeLists.txt, glslang/MachineIndependent/unistd.h, glslang_vs2010.vcxproj, glslang_vs2013.vcxproj
The presence of this file can cause build issues when integrating glslang
into other projects.
Note that the VS build projects were hand edited due to tool availability. However, given they've been deprecated, that shouldn't be an issue.
=> Remove obsolete unistd.h file

glslang/MachineIndependent/SymbolTable.cpp
Encountered with GCC-4.7.3 in a build environment using -Werror=extra
=> Fix ordered pointer comparison build warning/error

SPIRV/GlslangToSpv.cpp
When emitting SPIR-V code for frexp, avoid access
beyond the end of the operands vector.  When constructing
the OpExtInst, construct a new arguments vector instead of
modifying the existing operands vector.  In the case of OpFrexp,
well need that last operand later on to generate the store.
Fixes https://github.com/KhronosGroup/glslang/issues/110
Change-Id: Ibc380fadf5e600ac491932e9ecef7afe2d72fd7f
=> Avoid read past end of operands vector for EOpFrexp

glslang/MachineIndependent/Scan.cpp
This causes build failures with -Werror=parentheses
=> Fix compile warning/error due to assignment in while() loop

StandAlone/StandAlone.cpp
I'm running glslangValidator as part of a cmake build. With its current output choices, I either can validate all the shaders in one call (which then outputs every filename even if they succeed), or I do them one at a time (but if one fails, I have no idea which one failed, since cmake/ninja groups them all into a single massive shell call). This pull request outputs the filename even if only validating a single file: as long as compiler output is available (e.g. validation failed, info log, etc).
=> Display the filename if we have output, even if validating  a single file

glslang/MachineIndependent/linkValidate.cpp
This fixes a bug with structs of structs where it wasn't properly applying the last sentence of clause 9 of the std140 UBO packing rules.
=> linkValidate: Round up structure sizes to vec4 in std140

glslang/MachineIndependent/preprocessor/PpTokens.cpp
Found by running glslang with -fsanitize=address in clang.
Also fixes a potential buffer-overrun with return from lReadByte.
=> Removed strcpy that copied a value to itself.

SPIRV/SpvBuilder.cpp
Apparently, older MSVC versions don't support brace-initializers for
function arguments.
Thanks @baldurk for a suggestion on his branch.
=> Fix #137 by avoiding a C++11 feature.

SPIRV/SpvBuilder.cpp
This fixes two Visual Studio warnings/errors which were introduced by recent changes.
=> Fix two new Windows build warnings/errors

glslang/CMakeLists.txt
We cannot just default to use `tools/bison.exe` when it is not on
Windows.
=> Error out if bison is not found on non-Windows operating systems.

glslang/MachineIndependent/intermOut.cpp
fixes #171 
glslang/MachineIndependent/intermOut.cpp used `isinf`,
but it's in `std` namespace, so should use `std::isinf`.
=> fix #171 - error: ‘isinf’ was not declared in this scope

SPIRV/disassemble.cpp, StandAlone/StandAlone.cpp
I figure it's safer to ensure `spv::Parameterize()` and InstructionDesc table is valid before any `spv::Disassemble()` attempt.
=> SPV: Ensure Parameterize is called during Disassemble

SPIRV/SpvBuilder.cpp, SPIRV/disassemble.cpp, SPIRV/doc.h, glslang/Include/ShHandle.h, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/PoolAlloc.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/intermOut.cpp, glslang/OSDependent/Unix/ossource.cpp, glslang/OSDependent/osinclude.h
This fixes various issues related to gcc's strict-aliasing warning
by using unions. It also handles various cases hit with
gcc's missing-declarations warning.
=> Fix warnings/errors for strict aliasing & function prototypes

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, glslang/MachineIndependent/localintermediate.h
These are a few MSVC/GCC/Clang fixes I was sitting on on my local branch. I think they are all simple enough - the last one on getLocalSizeSpecId could be solved by casts in the calling code, but this seemed to be the cleanest fix.
=> Minor warning fixes

SPIRV/GlslangToSpv.cpp, SPIRV/InReadableOrder.cpp, SPIRV/SpvBuilder.cpp, StandAlone/StandAlone.cpp, StandAlone/spirv-remap.cpp, glslang/Include/Common.h, glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/preprocessor/Pp.cpp
This PR contains a handful of tiny changes that allow compilation using the MSVC 2010 compiler.  We still need to support MSVC 2010 for various reasons, and therefore we need to compile glslang with MSVC 2010 in order to be able to link it in.
Most of the changes replace the use of range-based for loops, and one replaces the use of std::tie.
=> Fix compilation issues with MSVC 2010

Test/baseResults/preprocessor.many.endif.vert.err, Test/preprocessor.many.endif.vert, Test/test-preprocessor-list, glslang/MachineIndependent/preprocessor/Pp.cpp
If we are not inside an `if` macro, we cannot simply decrease
`elsetracker`.
Fixes https://github.com/KhronosGroup/glslang/issues/29.
=> Fix array out of bounds bug in processing if-else-endif macros.

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h, SPIRV/spvIR.h
Fix issue #185 by removing OpDecorate instructions whose target IDs are
defined in unreachable blocks and thus not dumped in the generated
SPIR-V code.
Alternative to PR #193
=> Remove decoration of undefined IDs

glslang/MachineIndependent/PoolAlloc.cpp, glslang/MachineIndependent/intermOut.cpp, glslang/OSDependent/Windows/CMakeLists.txt
NOTE: MinGW can't compile googletest, so if https://github.com/KhronosGroup/glslang/pull/190 goes in first, then we must rework this pull request.
Supports Shaderc https://github.com/google/shaderc/pull/169
=> Support Linux-to-Windows cross compile via MinGW

StandAlone/StandAlone.cpp, glslang/MachineIndependent/Scan.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpContext.cpp, glslang/MachineIndependent/preprocessor/PpContext.h, glslang/Public/ShaderLang.h
This plumbs both the current file path and the include depth
back up to the includer. This allows the includer to properly
support relative paths.
This also replaces the string copy that was done during include
with a zero-copy method of accomplishing the same thing. This
prevents 2 extra copies of entire files.
=> Updated the includer interface to allow relative includes.

glslang/Public/ShaderLang.h
This issue is caused by the commit a132af5b78914e4dadcd66a9e8837de10b3a3c9f. VS2012 fails to compile the file `ShaderLang.h`.
=> Parser: Fix a build issue (VS2012).

SPIRV/SpvBuilder.cpp
If supporting VS2010 compilation is still desired, here are a couple of compile fixes needed for latest master code.
I'm not super familiar with the `{param}` syntax but I believe it's equivalent to what I've changed. It'd be good for someone familiar with C++-11 syntax to confirm that.
The tests run cleanly for me, including `spv.specConstantOperations.vert` which was added with the change that added this code.
=> VS2010 compile fixes

gtests/CMakeLists.txt
=> Unit test executable should link to libHLSL

.travis.yml, README.md
AFAICT, Travis CI is approved by the Khronos Group.
With this configuration in, we can have pull requests built and tested before going in.
=> Add configuration for Travis to test on Linux and Mac OS X.

CMakeLists.txt
CMake 2.8.12 added support for `target_include_directories()`, among
other features, and we would like to use it.
Addresses #259.
=> Bump minimum required CMake version to 2.8.12.

OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, hlsl/CMakeLists.txt
We only need one in the top directory CMakeLists.txt.
=> Remove duplicated cmake_minimum_required() calls.

README.md
There are two commits in this PR:
1. Explain how the tests are organized in glslang
2. Remove duplicated tests from `runtests` (those tests are already covered by gtest)
If the second one is supposed to be a long term task, I can drop it and I'm OK to only have the first one in.
=> Explain test organization and deduplication.

CMakeLists.txt, External/CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, gtests/CMakeLists.txt, hlsl/CMakeLists.txt
This adds solution folders that properly group gtest/glslang/hlsl.
This also marks gtest options as advanced so they don't show up
in cmake-gui by default.
=> Updated cmake to better organize folders and options.

Test/baseResults/negativeArraySize.comp.out, Test/negativeArraySize.comp, Test/testlist, glslang/MachineIndependent/ParseHelper.cpp
sizePair.size is unsigned, so the test <=0 was always false if the declared size was negative.
=> fix check for non-positive array size

glslang/OSDependent/Unix/ossource.cpp
Fixes a build warning because the DetachThreadLinux function is still declared on android but then not used.
Also just in case any more code is added to DetachThreadLinux, this will go through the same path on both platforms which is less surprising.
=> Minor android compile warning fix

SPIRV/Logger.cpp, SPIRV/Logger.h, glslang/Include/Common.h, glslang/MachineIndependent/propagateNoContraction.cpp
I'm still a little fuzzy on whether VS2010 compilation is intended to be supported upstream here or not, if it's not then I can just keep this up to date in my own fork.
Anyway for perusal here are fixes for C++11 constructs not supported on VS2010 that should not regress any functionality or anything or break on other compilers, as far as I understand the C++11 semantics anyway.
=> VS2010 compilation fixes

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.matrix.frag.out
Originally, I use this function to perform OpFConvert for matrix. But I find type of the source is not necessarily the same as that of the destination. So this function should be revised accordingly. Otherwise, the generated results are erroneous.
=> SPV: Correct an issue in createUnaryMatrixOperation().

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.430.vert.out, Test/baseResults/spv.localAggregates.frag.out, Test/baseResults/spv.variableArrayIndex.frag.out
This fixes some vulkanCTS tests that use struct arrays as a member of in/out interface blocks.
From Vulkan spec:
> If it is a not a Block, then the structure type must have a Location decoration. Its members are assigned consecutive locations in their declaration order, with the first member assigned to the location specified for the structure type. **The members, and their nested types, must not themselves have Location decorations**
From SPIR-V spec:
>When applied to structure-type members, the Decorations Noperspective, Flat, Patch, Centroid, and Sample can only be applied to the top-level members of the structure type. (Nested objects' types cannot be structures whose members are decorated with these decorations.)
=> SPV: Do not decorate struct members with location or nested members with interpolation qualifiers

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.430.vert.out
Spec for decorating the OpVariable:
> The remaining variables listed by OpEntryPoint with the Input or Output storage class form the user-defined variable interface. These variables must be identified with a Location decoration
Spec for decorating struct type:
> The layout of a structure type used as an Input or Output depends on whether it is also a Block (i.e. has a Block decoration).
> If it is a not a Block, then the structure type must have a Location decoration
=> [WIP]Fix missing location decoration for structures put directly on input/output interfaces

gtests/CMakeLists.txt, gtests/Hlsl.FromFile.cpp, gtests/Link.FromFile.cpp, gtests/TestFixture.h
This PR is another step towards deprecating `runtests`.
Related to #279: I'm leaning towards to use `TOption` like bitmask now.
=> Also do link tests in the GTest framework

Test/450.frag, Test/baseResults/450.frag.out, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/linkValidate.cpp
I have this fragment shader which causes the compilation fails. Redeclaration of `gl_CullDistance `should be allowed.
```
#version 450
layout(location = 0) out float o1;
layout(location = 1) out float o2;
layout(binding = 0) uniform Uniforms
{
int i;
};
in float gl_ClipDistance[6];
in float gl_CullDistance[2];
layout(location = 1) in float in1;
void main()
{
o1 = gl_ClipDistance[3] + gl_CullDistance[1];
o2 = gl_ClipDistance[i] + gl_CullDistance[i] + in1;
}
```
=> Parser: Redeclaration of gl_CullDistance is disallowed mistakenly.

Test/baseResults/reflection.vert.out, Test/reflection.vert, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/reflection.cpp, glslang/MachineIndependent/reflection.h, glslang/Public/ShaderLang.h
This adds support for querying which vertex attributes are specified as inputs in the vertex shader and for querying the number of attributes, their names and types similar to querying uniform variables.
=> Add support for querying vertex attributes in reflection API

glslang/Public/ShaderLang.h
The function ShGetPhysicalAttributeBindings() is declared in the
header, but not defined (or referenced) anywhere in the codebase.
=> Remove declaration for ShGetPhysicalAttributeBindings

StandAlone/ResourceLimits.cpp
This is required to fix the Android build for ARM.
=> atoi comes from stddef.h or cstddef

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.qualifiers.vert.out
I have this fragment shader and the "noperspective" and "sample" qualifiers do not coexist in SPIR-V. TranslateInterpolationDecoration() makes them mutually exclusive. This is unexpected.
```
#version 450
layout(location = 0) out float o1;
layout(location = 1) in noperspective sample float in1;
void main()
{
o1 = in1;
}
```
Problematic line:
`layout(location = 1) in noperspective sample float in1;`
=> SPV: Fix an issue of interpolation decoration.

glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Initialize.h, glslang/MachineIndependent/ShaderLang.cpp, hlsl/CMakeLists.txt, hlsl/hlslParseables.cpp, hlsl/hlslParseables.h
Add base class TParseableBuiltInss for language-dependent intrinsics / builtins generation.  Add stubbed HLSL derivation.  GLSL derivation is still called TBuiltIns (its original name), for historical compatibility.
=> Add base class TParseables for intrinsic / builtin generation.

CMakeLists.txt
=> Produce different names for files in debug builds on MSVC

CMakeLists.txt, StandAlone/CMakeLists.txt, gtests/CMakeLists.txt
Avoids the need to ship basic runtimes like libgcc_s_sjlj-1.dll
with the executables.
=> For MinGW, statically link exes against basic runtimes

SPIRV/SPVRemapper.cpp
this is done by counting op_entrypoint as a use/def
in lieu of a formal regression test for the remapper, I did before/after comparison across the glslang spv test shaders as well as our entire customer shader base.
=> remapper: do not eliminate interface variables in dce by default

Test/hlsl.intrinsics.vert, hlsl/hlslGrammar.cpp
This is a small fix for a segfault in the HLSL parser on empty statements (such as ";;").  HlslGrammar::acceptExpression() would accept them with success, but was leaving "node" pointing to garbage in that case, causing later code to crash.
The PR also adds back in a test case for this as part of the intrinsics tests.
=> Fix for empty statement segfault

Test/baseResults/hlsl.intrinsics.negative.frag.out, Test/baseResults/hlsl.intrinsics.negative.vert.out, Test/hlsl.intrinsics.negative.frag, Test/hlsl.intrinsics.negative.vert, gtests/Hlsl.FromFile.cpp
This adds negative tests for intrinsics that should not appear in some stage, or which should not accept some argument types (for example, that a matrix-only function does not accept scalars or vectors).
=> Add negative intrinsics tests

glslang/OSDependent/Windows/ossource.cpp
AFAIK, `entry` cannot be implicitly converted to `void*`. This fails to compile with clang-3.8.
=> Compilation fix (mingw64)

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.intrinsics.frag.out, Test/baseResults/hlsl.intrinsics.vert.out, Test/hlsl.intrinsics.frag, Test/hlsl.intrinsics.vert, glslang/Include/Types.h, glslang/Include/intermediate.h, glslang/MachineIndependent/intermOut.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h, hlsl/hlslParseables.cpp
Connect some new HLSL intrinsics which require simple decompositions:
clip
dst
isfinite
log10
mul (generic mat/vec/scalar forms)
rcp
saturate
sincos
This PR adds decomposeIntrinsic(), which is either (A) a no-op to pass intrinsics through unmodified to AST opcodes for downstream native handling, or (B) a set of simple decompositions to current AST opcodes, for compatibility with existing downstream code. Only (B) is currently implemented.
* mul is turned into one of the MatrixTimesMatrix, MatrixTimesVector, MatrixTimesScalar, VectorTimesMatrix, VectorTimesScalar, Dot, or Mul opcodes. This is only available with square matrices presently.
* clip is turned into either a test for <0 and branch with pixel kill, or a component-wise test with any() followed by same. The HLSL docs don't specify …
=> Add decompositions for some HLSL intrinsics.

glslang/Include/Common.h
Fixes TMap template.
This is required to build with newer libc++ versions that have a static
assert on const-ness of value_type
=> Tracking allocator must use const key

Test/baseResults/120.vert.out, Test/baseResults/430.vert.out, Test/baseResults/maxClipDistances.vert.out, Test/maxClipDistances.vert, Test/testlist, glslang/MachineIndependent/ParseHelper.cpp
Fixed off-by-one error with gl_MaxClipDistances and similar limits.
I tried to compile the following shader and it failed:
```
#version 450
layout(constant_id = 1) const int numClipDistances = 8;
out gl_PerVertex {
vec4  gl_Position;
float gl_ClipDistance[numClipDistances];
};
```
Based on Vulkan and OpenGL specs array of up to ```maxClipDistances``` should be allowed.
=> Front-end: allow max size built-in arrays like gl_ClipDistance

Test/baseResults/hlsl.intrinsics.frag.out, Test/baseResults/hlsl.intrinsics.vert.out, Test/hlsl.intrinsics.frag, Test/hlsl.intrinsics.vert, glslang/Include/intermediate.h, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h, hlsl/hlslParseables.cpp, hlsl/hlslParseables.h
In this PR:
- Add lerp, which was missing due to an oversight.
- Adds non-square matricies to the HLSL proto generation, except for Nx1 flavors.
- Adds mul() support for VxM, MxV, MxM for non-square mat types.  Tests for these are also added.  Note that GLSL and HLSL have opposite row/col order on mat types.
- Adds return type tests (just for pixel shader fns), e.g to verify an intrinsic that should return a bool or a vec3 really does so.  This resulted in finding a bad return type, which this PR also fixes.
- Adds a translation from HLSL texture semantics to AST semantics.  This is currently untested pending the ability to declare samplers.  E.g: HLSL tx bias modes use the coordinate W as the bias, where it's a separate parameter in AST (& GLSL), and the standard tex1d intrinsics support …
=> HLSL: Add lerp, fix sincos ret, add ret type tests, non-square mats, tx semantics

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.430.vert.out, Test/baseResults/spv.layoutNested.vert.out, Test/baseResults/spv.localAggregates.frag.out, Test/baseResults/spv.variableArrayIndex.frag.out
We encounter a problem from Vulkan conformance tests. This is a tessellation evaluation shader. The "patch" decoration is missing for "block[4]". After investigation, this problem seems much more generic. For instance, you could define a structure and define an input variable with that structure as fragment shader input. When you decorate the input with "flat". The qualifier is not converted to "flat" decoration in SPIR-V tokens.
```
#version 450
layout(quads, equal_spacing, ccw) in;
struct S
{
int   i1;
vec4  f4;
float f1[2];
};
struct TheBlock
{
float f1[3];
S     s[3];
float f1_0;
};
out float f1;
layout(location = 2) in patch TheBlock block[4];
void main()
{
f1 = block[3].s[2].f4.x;
}
```
=> SPV: Certain decorations are missing for structure-typed in/out variables

Test/baseResults/hlsl.templatetypes.frag.out, Test/hlsl.templatetypes.frag, Test/hlsl.templatetypes.negative.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslGrammar.h
This PR adds vector&lt;float, 3&gt; and similar matrix style type parsing.
The simple scalar types are accepted in HlslGrammar::acceptBasicType(), which is used by both of those forms as well as acceptType(). This is because only basic types may appear, and constructs such as vector&lt;vector&lt;float, 2&gt;, 2&gt; are illegal.
A new test for these type declarations is also added.
This is another try for this PR: previously there was a git error during one of the auto-build processes: "fatal: index-pack failed", which happened when the "travis CI" build attempted to check out the branch.
=> HLSL: Add template style constructors for vector & matrix types

SPIRV/GlslangToSpv.cpp, SPIRV/GlslangToSpv.h, StandAlone/StandAlone.cpp
This option makes embedding SPIR-V in source code trivial without the need for additional tools. The Vulkan-Samples repository encourages embedding SPIR-V in the source code to simplify a sample and minimize the build complexity. One of the samples is already using this.
=> Added -x option to save SPIR-V as 32-bit hexadecimal numbers to a text file.

.gitignore, Test/baseResults/hlsl.sample.basicdx10.frag.out, Test/hlsl.sample.basicdx10.frag, glslang/Include/Types.h, glslang/Include/intermediate.h, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslGrammar.h, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h, hlsl/hlslParseables.cpp, hlsl/hlslScanContext.cpp, hlsl/hlslTokens.h
This PR adds:
- Declarations for HLSL sampler and texture types.  Some features such as immediate sampler state declarations are parsed but dropped with a warning.  Only separate declarations are currently allowed, so no DX9 style.
- Method syntax.  The calling object becomes the hidden first parameter.
- A partial implementation of the texture object Sample() method.
- Compiler warning fix from fbarchard
This PR is aimed at a narrow vertical path, which will be broadened in future PRs.  Limitations include:
- Only DX10 style syntax is in place (though DX9 will be added later).
- Only the features seen in Test/hlsl.sample.basicdx10.frag are connected.  Stray outside that, and it won't work.  For example, no arrays, no multisample, no texel offset, no other methods, etc.
=> HLSL: Sampler/texture declarations, method syntax, partial Sample method

CMakeLists.txt, glslang/Include/Common.h, glslang/OSDependent/Unix/ossource.cpp, hlsl/hlslParseables.cpp
This PR adds some warnings to the g++ build which are already enabled in the MSVC build, to prevent code triggering them from escaping notice.
=> Add g++/clang warnings to match some enabled by /W4 in MSVC

SPIRV/SPVRemapper.cpp
Scope and MemorySemantics operands contain IDs as well and may need
remapping.
=> Remap Scope and MemorySemantics IDs in SPIRV remapper

Test/baseResults/hlsl.promotions.frag.out, Test/hlsl.promotions.frag, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/localintermediate.h, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
This PR adds:
- Return type conversion for function returns.  Some of the underpinnings of these were already in place, but not connected.  For example, the currentReturnType was already tracked during function definitions.  This change adds a HlslParseContext::handleReturnValue() function to handle conversions.  Previously, return values were returned "blindly" regardless of the function's return type.  Tests for this are added as part of the new hlsl.promotions.frag test: see the functions beginning with Fn_R_*.  The test also ensures that conversions happen for out params (which was already correct).
- HLSL allows arbitrary basic type conversions on assignment (including, e.g, multiply-assign, etc).  For example, a bool vector can be assigned to a float vector.  hlsl.promotions.frag …
=> HLSL: add implicit promotions for assignments and function returns.

Test/baseResults/hlsl.intrinsics.negative.comp.out, Test/baseResults/hlsl.intrinsics.negative.vert.out, Test/hlsl.intrinsics.negative.comp, Test/hlsl.intrinsics.negative.vert, hlsl/hlslParseables.cpp
It is legal to call e.g, a PS only intrinsic from a VS, as long as it is not called.  Previously, the intrinsics were only in the symbol table for the stages in which they belonged.
This information is still lexically preserved in case of a future validation use, but the mask variables are all set to EShLangAll, which puts them in the common symbol table.
Negative tests for their absence are disabled.
=> HLSL: Put all intrinsics in common stage symbol table

OGLCompilersDLL/InitializeDll.cpp, SPIRV/SPVRemapper.h, SPIRV/SpvBuilder.cpp, SPIRV/disassemble.cpp, SPIRV/doc.cpp, StandAlone/StandAlone.cpp, glslang/Include/Common.h, glslang/Include/InfoSink.h, glslang/Include/PoolAlloc.h, glslang/Include/revision.h, glslang/MachineIndependent/InfoSink.cpp, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpAtom.cpp, glslang/MachineIndependent/preprocessor/PpContext.cpp, glslang/MachineIndependent/preprocessor/PpMemory.cpp, glslang/MachineIndependent/preprocessor/PpScanner.cpp, glslang/MachineIndependent/preprocessor/PpSymbols.cpp, glslang/MachineIndependent/preprocessor/PpTokens.cpp, glslang/OSDependent/Windows/ossource.cpp, glslang/Public/ShaderLang.h, gtests/TestFixture.h, hlsl/hlslParseHelper.cpp, hlsl/hlslScanContext.cpp
Replace PR #366 with a more directed version.
It's mostly a more conservative change, but does take a risk in reducing headers in a few places that don't seem to need them.  Will see how they build on different systems, then pull.
=> Build: C++ headers: Replace PR #366 with a more directed version.

CMakeLists.txt
There are no CMake features that require CMake > 2.8.11 and that is the version that ships on stock CentOS 7. By dropping the CMake version down to 2.8.11 we can build glslang out of the box on stock CentOS 7.
=> bump required CMake version down to 2.8.11

SPIRV/SPVRemapper.cpp, SPIRV/SPVRemapper.h
This PR addresses issue #435, where iteration over the OperandVariableLiteralId argument list class would not cope with multiple word literals.
It also includes a small improvement to dead type elimination which picks up some cases previously dropped.  The algorithm used for this is suboptimal, but it's an offline tool, it was easy to write that way, and it can be further improved later if there is ever a performance concern.
=> SPIRV: Remapper: allow 64 bit literals in OperandVariableLiteralId iteration

SPIRV/SPVRemapper.cpp, SPIRV/SPVRemapper.h
This reverts commit ad08b30f696267ec6243dd0ad68a3db889cd2d21, reversing
changes made to 28660bb580d4c61e16ef75008550a87b3be90b91.
This backs out the pull request
https://github.com/KhronosGroup/glslang/pull/456 because it introduced
several internal errors even on code that only uses 32-bit numeric
types.
=> Revert "Merge pull request #456 from steve-lunarg/remapper-literal64"

hlsl/hlslParseHelper.cpp
As it says, just a warning fix that shows up on MSVC (useful to silence so you can build with warnings-as-errors).
=> fix x64 warning about conversion size_t -> int

StandAlone/ResourceLimits.cpp
`strtok_s()` is suggested by [MSVC](https://msdn.microsoft.com/en-us/library/ftsafwz3.aspx), but it has different signature
than the [C11 standard one](http://en.cppreference.com/w/c/string/byte/strtok). So we just turn off the recommendation
here.
=> Disable C4996 (secure CRT) recommendation on Windows for strtok().

gtests/CMakeLists.txt
This is (solely) a CMakeLists.txt change to move the remapper tests into the glslangtests executable.  The contents of the tests don't change.
=> Remapper: move remapper tests into the glslangtests executable.

StandAlone/StandAlone.cpp, Test/baseResults/hlsl.array.flatten.frag.out, Test/hlsl.array.flatten.frag, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/localintermediate.h, glslang/Public/ShaderLang.h, gtests/Hlsl.FromFile.cpp, gtests/TestFixture.h, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Flatten uniform arrays
This checkin adds a --flatten-uniform-arrays option which can break uniform arrays of samplers, textures, or UBOs up into individual scalars named (e.g) myarray[0], myarray[1], etc.  These appear as individual linkage objects.
Code notes:
- shouldFlatten is replaced with: shouldFlattenArray, shouldFlattenStruct, and shouldFlattenType (which is true if either of the others are).
- There's some error checking around unhandled situations.  E.g, flattening uniform arrays with initializer lists is not implemented.
- This piggybacks on as much of the existing mechanism for struct flattening as it can.  E.g, it uses the same flattenMap, and the same flattenAccess() method.
- handleAssign() has been generalized to cope with either structs or arrays.
- Extended test …
=> Flatten uniform arrays

SPIRV/GlslangToSpv.cpp
The use of capability `CapabilitySubgroupBallotKHR ` requires enablement of SPIR-V extension SPV_KHR_shader_ballot.
=> SPV: Still have to specify SPIR-V extension for gl_SubGroupSizeARB and gl_SubGroupInvocationARB.

Test/baseResults/hlsl.array.implicit-size.frag.out, Test/hlsl.array.implicit-size.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp
In HLSL array sizes need not be provided explicitly in all circumstances.  For example, this is valid (note no number between the [ ]):
// no explicit array size
uniform float g_array[] = { 1, 2, 3, 4, 5 };
This PR does not attempt to validate most invalid cases.
A new test is added to verify the resulting linker objects.
=> HLSL: allow implicit size in array declarations

StandAlone/StandAlone.cpp, hlsl/hlslParseHelper.cpp
Previously the uniform array flattening feature would trigger on loose uniform arrays of any basic type (e.g, floats).  This PR restricts it to sampler and texture arrays.  Other arrays would end up in their own uniform block (anonymous or otherwise).  (Atomic counter arrays might be an exception, but those are not currently flattened).
=> HLSL: Restrict uniform array flattening to sampler and texture arrays

Test/baseResults/spv.buffer.autoassign.frag.out, Test/baseResults/spv.glsl.register.autoassign.frag.out, Test/baseResults/spv.register.autoassign.frag.out, glslang/MachineIndependent/iomapper.cpp, gtests/Spv.FromFile.cpp
Previously, the binding auto-mapping facility was free to use any unused binding.  This change makes auto-bindings use the same offset value as explicit bindings.
=> Change binding auto-map to use provided offsets.

Test/baseResults/hlsl.flatten.return.frag.out, Test/hlsl.flatten.return.frag, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/localintermediate.h, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
If a member-wise assignment from a non-flattened struct to a flattened struct sees a complex R-value  (not a symbol), it now creates a temporary to hold that value, to avoid repeating the R-value.  This avoids, e.g, duplicating a whole function call.  Also, it avoids re-using the AST node, making a  new one for each member inside the member loop.    
The latter (re-use of AST node) was also an issue in the GetDimensions intrinsic decomposition, so this PR fixes that one too.
=> HLSL: fix for flattening assignments from non-symbol R-values.

gtests/AST.FromFile.cpp, gtests/BuiltInResource.FromFile.cpp, gtests/CMakeLists.txt, gtests/Config.FromFile.cpp, gtests/Hlsl.FromFile.cpp, gtests/Link.FromFile.cpp, gtests/Pp.FromFile.cpp, gtests/Remap.FromFile.cpp, gtests/Settings.cpp, gtests/Settings.h, gtests/Spv.FromFile.cpp, gtests/TestFixture.h, gtests/main.cpp
The gtest executable accepts a --test-root option to specify
a root directory for test files.  It defaults to the Test directory
in the source tree from which the executable is built.
For example, this lets us run test exectuables built with MinGW on Linux
on a Windows machine with its own copy of the source tree.
=> Gtests can be run on another source tree

glslang/Include/InfoSink.h, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/preprocessor/PpTokens.cpp, glslang/MachineIndependent/propagateNoContraction.cpp, hlsl/hlslParseHelper.cpp
- Add explicit casts from long to int.
- Comment out method argument names that are unused.
- Always initialize a boolean variable before it's read.
=> Address some compiler warnings.

StandAlone/StandAlone.cpp, Test/baseResults/spv.register.autoassign.rangetest.frag.out, Test/spv.register.autoassign.rangetest.frag, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h, gtests/Spv.FromFile.cpp
Produces an error if IO mapping attempts to apply a binding out of the valid range.
=> Check for out-of-range bindings during IO mapping.

glslang/OSDependent/Unix/ossource.cpp
This allows multithreaded use of multiple TShader instances on Linux.  If I wasn't lazy, I'd also implement OS_CreateThread() and friends, but I don't need them and I already spent hours tracing my crash to the silent lack of a global lock.
=> Use pthread_mutex for global lock on Linux.

SPIRV/GlslangToSpv.cpp
Otherwise compilation fails when ENABLED_AMD_EXTENSIONS is off.
=> Add missing guard to code that uses AMD extensions

Test/baseResults/hlsl.rw.atomics.frag.out, Test/hlsl.rw.atomics.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
This PR will turn Interlocked* intrinsics using rwtexture or rwbuffer objects as the first parameter into the proper OpImageAtomic* operations.
=> HLSL: phase 4 of RWTexture support: add image atomics

Test/baseResults/hlsl.samplecmp.array.dx10.frag.out, Test/baseResults/hlsl.samplecmp.basic.dx10.frag.out, Test/baseResults/hlsl.samplecmp.offset.dx10.frag.out, Test/baseResults/hlsl.samplecmp.offsetarray.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.array.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.basic.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.offset.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.offsetarray.dx10.frag.out, hlsl/hlslParseHelper.cpp
HLSL holds the compare value in a separate intrinsic arg, but the AST wants a vector including the cmp val, except in the 4-dim coord case, where it doesn't fit and is in fact a separate AST parameter.   This is awkward but necessary, given AST semantics.  In the process, a new vector is constructed for the combined result, but this vector was not being given the correct TType, so was causing some downstream troubles.
Now it is.  A similar defect existed in OpTextureBias, and has also been fixed.
=> HLSL: fix defect in EOpMethodSampleCmp* texture decomposition

glslang/MachineIndependent/ParseHelper.cpp
I happened upon numArgs while hunting for unused variables. I suspect
the intent was to apply it as shown in this patch. However, I am not a
compiler dude. Someone more appropriate should grok this change.
=> WIP: apply unused variable

Test/baseResults/hlsl.comparison.vec.frag.out, Test/baseResults/hlsl.doLoop.frag.out, Test/baseResults/hlsl.forLoop.frag.out, Test/baseResults/hlsl.if.frag.out, Test/baseResults/hlsl.shapeConv.frag.out, Test/baseResults/hlsl.whileLoop.frag.out, Test/hlsl.comparison.vec.frag, Test/hlsl.doLoop.frag, Test/hlsl.forLoop.frag, Test/hlsl.if.frag, Test/hlsl.shapeConv.frag, Test/hlsl.whileLoop.frag, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/intermOut.cpp, gtests/Hlsl.FromFile.cpp
This PR only changes a few lines of non-test code, but it's subtle, hence long explanation:
In HLSL, comparison operators (<,>,<=,>=,==,!=) operate component-wise when given a vector operand.  If a whole vector equality or inequality is desired, then all() or any() can be used on the resulting bool vector.
This PR enables this.  Previously, these were producing a scalar bool result, even for vector args.  Existing shape conversion is used when one of the two arguments is a vector and one is a scalar.
Some existing HLSL tests had assumed == and != meant vector-wise instead of component-wise comparisons.  These tests have been changed to add an explicit any() or all() to the test source, thus preserving their original semantic (and in all but one case, also their original SPIR-V).  This …
=> HLSL: Enable component-wise vector comparisons from operators

Test/baseResults/hlsl.logical.binary.vec.frag.out, Test/hlsl.logical.binary.vec.frag, glslang/MachineIndependent/Intermediate.cpp, gtests/Hlsl.FromFile.cpp
HLSL || and && can operate component-wise.
New test added for vec op vec, vec op scalar, and scalar op vec.
=> HLSL: allow component-wise operations for logical || and &&.

hlsl/hlslParseHelper.cpp
In the same vein as #548, VS2010 in particular needs an explicit return type declared for lambdas with multiple statements, as that was added in C++14.
=> Add explicit lambda return types, for compilers without C++14 support

StandAlone/ResourceLimits.cpp
Some Android cross cross-compilers don't have std::stoi.
E.g. i686-linux-android-g++ from Android NDK r10e don't have std::stoi.
=> Use std::atoi instead of std::stoi

glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h
I'm using glslang to retrieve information about GLSL uniforms and vertex attributes for the Vulkan implementation in Banshee Engine (https://github.com/bearishsun/bansheeengine). 
However the current interface seems to be missing a way to retrieve the "location" qualifier from vertex attributes. I exposed a method that returns a TType for attribute to get around that problem (similar to existing methods for uniforms and uniform blocks).
=> A way to query "location" qualifier for vertex attributes, using TProgram reflection API

glslang/MachineIndependent/parseVersions.h, glslang/MachineIndependent/preprocessor/Pp.cpp
Preprocessing HLSL would fail due to missing extension `GL_GOOGLE_include_directive`. It seems that HLSL parsing ignores the shader preamble which is, with GLSL, what implicitly enables `GL_GOOGLE_include_directive` for the desktop profile.
=> Fixed processing #include's when preprocessing HLSL

Test/baseResults/hlsl.entry.rename.frag.out, Test/runtests
Recently added entry point renaming file referred to
test source file hlsl.entry.rename.frag via relative directory.
Change it to be consistent with other tests: assume test
sources are in the current directory.
=> runtests should refer to test files in current directory

glslang/Public/ShaderLang.h
Rather than update the existing ifdef to cover all necessary cases,
get rid of it and always define TShader::~Includer().
=> GLSL: Always define TShader::~Includer().

glslang/MachineIndependent/Intermediate.cpp, hlsl/hlslParseHelper.cpp
Several instances in Visual Studio 2015:
warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
PTAL... I saw mixed use of static_cast and c-style casts so I chose the more modern. I can abandon this if you have no interest in fixing this warning but it is a potential source of errors in some cases.
=> Fix size_t to int cast warnings.

glslang/MachineIndependent/Constant.cpp
This change is helpful for integration with Chromium, which recently
added a compiler option to warn when compiling any source files which
use extended characters. In this case the offending character was a
single unicode dash in a comment.
PTAL.. a single character change. Not strictly necessary I believe, but would
be helpful. My text editor also trimmed the training whitespace from a few lines,
I can revert those parts of the CL you would prefer.
=> Change unicode dash to ASCII.

glslang/MachineIndependent/ParseHelper.h
Probably affects Linux as well with non-standard libc that doesn't bootleg `<stdarg.h>`.
```c++
In file included from C:/Projects/glslang/glslang/MachineIndependent/glslang.y:59:0:
glslang/MachineIndependent/ParseHelper.h:276:24: error: 'va_list' has not been declared
va_list args);
^~~~~~~
```
=> Unbreak build on FreeBSD with GCC/libstdc++ 6.2.0

CMakeLists.txt
Sometimes it's nice to not build the executables when building through CMake, for example when building static libraries for platforms where the executables aren't really useful anyway like Android/iOS.
This creates an option that defaults to ON that builds them, but can be easily set to OFF to avoid building the executables.
=> CMake: Add option to make it possible to not build the executables

glslang/MachineIndependent/preprocessor/PpContext.h, hlsl/hlslParseHelper.h
Clang doesn't like it when you use a mix of using override and not using it.
=> Fix a large number of Clang warnings about inconsistent usage of 'override'

Test/baseResults/hlsl.intrinsics.negative.frag.out, Test/baseResults/hlsl.params.default.frag.out, Test/baseResults/hlsl.params.default.negative.frag.out, Test/hlsl.params.default.frag, Test/hlsl.params.default.negative.frag, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslGrammar.h, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h, hlsl/hlslParseables.cpp
This PR adds support for default function parameters in the following cases:
1. Simple constants, such as void fn(int x, float myparam = 3)
2. Expressions that can be const folded, such a ... myparam = sin(some_const)
3. Initializer lists that can be const folded, such as ... float2 myparam = {1,2}
New tests are added: hlsl.params.default.frag and hlsl.params.default.err.frag (for testing error situations, such as ambiguity or non-const-foldable).
In order to avoid sampler method ambiguity, the hlsl better() lambda now considers sampler matches.  Previously, all sampler types looked identical since only the basic type of EbtSampler was considered.
=> HLSL: default function parameters

CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/MachineIndependent/ShaderLang.cpp
This adds the ability to build glslang without support for HLSL input, which reduces the size of the binary.
Resolves isssue #666
=> Add a CMake option to disable compilation of HLSL input support.

Test/baseResults/hlsl.struct.split.assign.frag.out, Test/hlsl.struct.split.assign.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
When copying split types with mixtures of user variables and buitins, where the builtins are extracted, there is a parallel structures traversal. The traversal was not obtaining the derefenced types in the array case.
=> HLSL: fix dereferencing when copying split structures with arrays

SPIRV/GlslangToSpv.cpp
Added default to the switch() for AMD_EXTENSIONS to avoid a spew
of warning messages.
=> Fix for not-handled-in-switch warnings

glslang/MachineIndependent/ParseHelper.cpp
Also, maybe it would be better to have a NO_NV_EXTENSIONS define instead... why would you want to turn them off anyway?
=> Fix build if NV_EXTENSIONS is not set

glslang/MachineIndependent/Initialize.cpp
GLSL texture clamp functions introduced by ARB_sparse_texture_clamp are only available for fragment shader according to the spec.
=> Semantics: Texture clamp functions are available for fragment shader only

SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h
This allows calling functions with temporary objects like this:
```C++
b.makeCompositeConstant(
vec4_float_type_,
std::vector<Id>({b.makeFloatConstant(1.f), b.makeFloatConstant(1.f),
b.makeFloatConstant(1.f), b.makeFloatConstant(1.f)}));
```
=> SpvBuilder: add const specifier to vector reference arguments

SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt
Makes it easier to include glslang in a larger CMake project: instead of having to call `target_link_libraries(glslang OSDependent OGLCompiler HLSL)`, for example, you only need to call `target_link_libraries(glslang)` and it will pull in the helpers it needs.
This is also better in terms of cleaning up the "public interface", of sorts, for building glslang: end-users probably shouldn't need to know or be explicitly dependent on internal targets.
=> CMake: add target_link_libraries internally

SPIRV/CMakeLists.txt, glslang/CMakeLists.txt
This enables the vulkan loader to be built against an installed glslang.
=> Install headers

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.layout.frag.out, Test/baseResults/spv.float16.frag.out, Test/baseResults/spv.int64.frag.out, Test/baseResults/spv.specConst.vert.out, Test/baseResults/spv.specConstant.vert.out, Test/baseResults/spv.specConstantComposite.vert.out, Test/baseResults/spv.specConstantOperations.vert.out, Test/baseResults/vulkan.ast.vert.out
A somewhat naive attempt at making GlslangToSpv emit friendly names of specialization constants.
=> SPV: Emit names of specialization constants, fixes #710

SPIRV/doc.cpp, Test/baseResults/spv.shaderGroupVote.comp.out
Text for opcodes OpSubgroupAllKHR and OpSubgroupAnyKHR was swapped.
=> Fix mismatched doc string for SPV_KHR_subgroup_vote

glslang/MachineIndependent/SymbolTable.h
Otherwise we get an error when we have both
-Werror and -Winconsistent-missing-override.
This is required for building with NDK r14 betas
=> Add override where needed by clang++

SPIRV/GlslangToSpv.cpp, SPIRV/doc.cpp, Test/baseResults/spv.multiviewPerViewAttributes.tesc.out, Test/baseResults/spv.multiviewPerViewAttributes.vert.out
We have a very simple geometry shader like this:
```
#version 450 core
layout(triangles)                        in;
layout(triangle_strip, max_vertices = 3) out;
void main()
{
for (int n_vertex = 0;
n_vertex < 3;
++n_vertex)
{
gl_Position = gl_in[n_vertex].gl_Position;
EmitVertex();
}
EndPrimitive();
}
```
But the SPV will generate unexpected capabilities, such as 
```
Capability PerViewAttributesNV
Extension "SPV_NVX_multiview_per_view_attributes"
```
Those capabilities are similar to `ClipDistance `and `CullDistance`. The reasonable behavior is that they should be disabled if they are not used (just declare in `gl_PerVertex`).
=> SPV: Unexpected declarations of capabilities from NV extensions.

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.structbuffer.atomics.frag.out, Test/baseResults/hlsl.structbuffer.byte.frag.out, Test/baseResults/hlsl.structbuffer.coherent.frag.out, Test/baseResults/hlsl.structbuffer.fn.frag.out, Test/baseResults/hlsl.structbuffer.frag.out, Test/baseResults/hlsl.structbuffer.rw.frag.out, Test/baseResults/hlsl.structbuffer.rwbyte.frag.out, Test/baseResults/spv.ssbo.autoassign.frag.out, Test/hlsl.structbuffer.fn.frag, glslang/MachineIndependent/SymbolTable.cpp, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
This PR adds the ability to pass structuredbuffer types by reference as function parameters.
It also changes the representation of structuredbuffers from anonymous blocks with named members, to named blocks with pseudonymous members. That should not be an externally visible change.
Local copies of struct buffer references are not currently handled, as in:
StructuredBuffer&lt;uint4&gt; sbuf_copy = sbuf;
=> HLSL: add structuredbuffer pass by reference in fn params

Test/baseResults/hlsl.intrinsics.f1632.frag.out, Test/baseResults/hlsl.intrinsics.negative.frag.out, hlsl/hlslParseHelper.cpp
Due to a cut and paste error, the f16tof32 opcode was indexing a vector with a float 0, rather than an int 0.  It may have made no functional difference due to the identical bit pattern, but code looking at the type could be confused.
=> HLSL: small fix for index type in f16tof32 opcode

glslang/MachineIndependent/preprocessor/Pp.cpp, hlsl/hlslParseHelper.cpp
Use an explicit cast from size_t to int to avoid errors like the following:
glslang\glslang\MachineIndependent\preprocessor\Pp.cpp(1053) : error C2220: warning treated as error - no 'object' file generated
glslang\glslang\MachineIndependent\preprocessor\Pp.cpp(1053) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
affects Pp.cpp, hlslParseHelper.cpp.
Initialize local variable to get rid of warnings about potentially
uninitialized variables:
glslang\hlsl\hlslparsehelper.cpp(3667) : error C2220: warning treated as error - no 'object' file generated
glslang\hlsl\hlslparsehelper.cpp(3667) : warning C4701: potentially uninitialized local variable 'builtIn' used
affects hlslParseHelper.cpp
=> Fix build warnings on some platforms

glslang/Public/ShaderLang.h
`ShaderLang.h` contains declaration for `ShLink` function which is never
defined.
See this grep output:
```
$ grep -Hrn 'ShLink'
glslang/Public/ShaderLang.h:206:SH_IMPORT_EXPORT int ShLink(
glslang/Public/ShaderLang.h:214:SH_IMPORT_EXPORT int ShLinkExt(
glslang/MachineIndependent/ShaderLang.cpp:1268:int ShLinkExt(
```
=> Sanitize ShaderLang.h

hlsl/hlslParseHelper.cpp
Fix another build warning on some platforms
Use an explicit cast from size_t to int to avoid warning.
=> More build fixes

Test/baseResults/spv.deviceGroup.frag.out, Test/baseResults/spv.multiView.frag.out, Test/spv.deviceGroup.frag, Test/spv.multiView.frag, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
GL_KHX_multiview and GL_KHX_device_group don't exist,
they were released as GL_EXT_multiview and GL_EXT_device_group.
https://www.khronos.org/registry/vulkan/specs/misc/GL_EXT_device_group.txt
https://www.khronos.org/registry/vulkan/specs/misc/GL_EXT_multiview.txt
=> Rename KHX_multiview/device_group to EXT_multiview/device to match the released specs

Test/baseResults/hlsl.structbuffer.fn.frag.out, Test/hlsl.structbuffer.fn.frag, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp
This change propagates the storage qualifier from the buffer object to its contained array type so that isStructBufferType() realizes it is one.  That propagation was happening before only for global variable declarations, so compilation defects would result if the use of a function parameter happened before a global declaration.
This fixes that case, whether or not there ever is a global declaration, and regardless of the relative order.
This changes the hlsl.structbuffer.fn.frag test to exercise the alternate order.
There are no differences to generated SPIR-V for the cases which successfully compiled before.
=> HLSL: Fix ordering defect if global SB decl after fn param

Test/baseResults/hlsl.getdimensions.dx10.frag.out, Test/baseResults/hlsl.getdimensions.dx10.vert.out, Test/baseResults/hlsl.intrinsics.promote.frag.out, Test/baseResults/hlsl.intrinsics.promote.outputs.frag.out, hlsl/hlslParseHelper.cpp
The non-LOD form of image size query is prohibited in certain cases: see the OpImageQuerySize and OpImageQuerySizeLod sections of the SPIR-V spec for details.  Sometimes we were generating the non-LOD form when we should have been using the LOD form.  Sometimes the LOD form is required even if the underlying HLSL query did not supply a MIP level itself, in which case level 0 is now queried.
See #697.
=> HLSL: use LOD form of ImageQuerySize when needed.

Test/baseResults/hlsl.gathercmpRGBA.offset.dx10.frag.out, Test/hlsl.gathercmpRGBA.offset.dx10.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
This implements GatherCmpRed in terms of OpImageDrefGather.
There appears to be no way to implement the Green/Blue/Apha forms: see #673.  Those still result in unimplemented errors.
=> HLSL: Enable GatherCmpRed.  Green/Blue/Alpha cannot be supported.

Test/150.vert, Test/baseResults/150.vert.out, glslang/MachineIndependent/Versions.cpp
As stated in the [OpenGL wiki](https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Standard_macros), `GL_core_profile` is always defined as standard macro to "1", and `GL_compatibility_profile` is only defined as standard macro to "1", if the version profile was set to "compatibility".
**Note:**
All standard macros (i.e. `__VERSION__`, `__LINE__`, `__FILE__`, `GL_core_profile`, and `GL_compatibility_profile`) are still not identified in an '#ifdef' or '#if defined' directive!
I.e. the following pre-processor directives will not result in a compiler error, but it should be:
```
#ifdef __VERSION__
#error foo bar
#endif
```
=> Added 'GL_core_profile' and 'GL_compatibility_profile' to macro expansion

Test/baseResults/hlsl.gathercmpRGBA.offset.dx10.frag.out, hlsl/hlslParseHelper.cpp
When mapping HLSL gather intrinsics to GLSL textureGatherXXX() built-in functions, the channel selection value is only valid for non-shadow samplers.
=> HLSL: Additional channel value for textureGatherXXX().

SPIRV/GlslangToSpv.cpp
=> Don't emit NV-specific interface members if NV extensions are disabled.

Test/baseResults/hlsl.domain.2.tese.out, Test/hlsl.domain.2.tese, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
In the hull shader, the PCF output does not participate in an argument list, so has no defined ordering.  It is always put at the end of the linkage.  That means the DS input reading PCF data must also be at the end of the DS linkage as well, no matter where it may appear in the argument list.  This change makes sure that happens.
The detection is by looking for arguments that contain tessellation factor builtins, even as a struct member.  The whole struct is taken as the PCF output if any members are so qualified.
=> HLSL: handle PCF input to DS in arbitrary argument position

Test/baseResults/hlsl.hull.ctrlpt-2.tesc.out, Test/hlsl.hull.ctrlpt-2.tesc, glslang/Include/BaseTypes.h, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslGrammar.h, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Previously, patch constant functions only accepted OutputPatch.  This adds InputPatch support, via a pseudo-builtin variable type, so that the patch can be tracked clear through from the qualifier.
=> HLSL: Support InputPatch variables in patch constant functions

StandAlone/StandAlone.cpp, StandAlone/Worklist.h, glslang/OSDependent/Unix/ossource.cpp, glslang/OSDependent/Windows/ossource.cpp, glslang/OSDependent/osinclude.h
Changes:
- Making WorkList class to have its own mutex instead of the OS specific
global one. The new mutex is the one from std library. The OS specific
code is also removed.
- Using the C++11 std library to handle threads in StandAlone
application
and enabling concurrent processing on non-windows platforms.
- converting the global variable Worklist into local variable workList.
=> Refactor the StandAlone and WorkList files in order to use more C++11 features and remove the dependencies from OS specific code.

Test/baseResults/hlsl.domain.3.tese.out, Test/hlsl.domain.3.tese, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
HLSL requires (or at least allows) vec2 tessellation coordinate declarations in some cases (e.g, isoline topology), where SPIR-V requires the TessCoord qualified builtin to be a vec3 in all cases.  This alters the IO form of the variable to be a vec3, which will be copied to the shader's declared type if needed.  This is not a validation; the shader type must be correct.
=> HLSL: allow non-vec3 tessellation coordinate declarations

Test/baseResults/hlsl.isfinite.frag.out, Test/hlsl.isfinite.frag, hlsl/hlslParseHelper.cpp
The prior decomposition of isfinite was not setting the return type on the sequence node.  (Sequence was used because there's an internal temporary to avoid the complex rvalue problem).
=> HLSL: fix return type for isfinite

StandAlone/StandAlone.cpp, Test/baseResults/hlsl.automap.frag.out, Test/baseResults/hlsl.buffer.frag.out, Test/baseResults/hlsl.layout.frag.out, Test/hlsl.automap.frag, Test/runtests, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/localintermediate.h, glslang/Public/ShaderLang.h, hlsl/hlslGrammar.cpp
Adds --hlsl-iomap option to perform IO mapping in HLSL register space.
--shift-cbuffer-binding is now a synonym for --shift-ubo-binding.
The idea way to do this seems to be passing in a dedicated IO resolver, but that would require more intrusive restructuring, so maybe best for its own PR.
The TDefaultHlslIoResolver class and the former TDefaultIoResolver class share quite a bit of mechanism in a common base class.
~~TODO: tbuffers are landing in the wrong register class, which needs some investigation.  They're either wrong upstream, or the detection in the resolver is wrong.~~  DONE
Addresses #794.
=> HLSL: hlsl register class iomapping

Test/baseResults/hlsl.structbuffer.fn2.comp.out, Test/hlsl.structbuffer.fn2.comp, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
Byte address buffers were failing to detect that they were byte address buffers when used as fn parameters.
Note: this detection is a little awkward, and could be simplified if it was easy to obtain the declared builtin type for an object.
Fixes #845.
=> HLSL: fix for byte address buffers in fn parmeters

Test/baseResults/hlsl.samplecmp.negative.frag.out, Test/baseResults/hlsl.samplecmp.negative2.frag.out, Test/hlsl.samplecmp.negative.frag, Test/hlsl.samplecmp.negative2.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
This adds an error message if a non-comparison sampler is used with comparison sampling methods.  There's no functional change for well formed shaders.
Addresses #698.
=> HLSL: add error for expected comparison sampler in SampleCmp* ops

glslang/MachineIndependent/iomapper.cpp, hlsl/hlslParseHelper.cpp
... due to out of order initializers. 
glslang/MachineIndependent/iomapper.cpp:207:9: error: field 'resolver' will be initialized after field 'stage' [-Werror,-Wreorder]
: resolver(r)
^
glslang/MachineIndependent/iomapper.cpp:263:9: error: field 'resolver' will be initialized after field 'stage' [-Werror,-Wreorder]
: resolver(r)
^
hlsl/hlslParseHelper.cpp:70:5: error: field 'gsStreamOutput' will be initialized after field 'inputPatch' [-Werror,-Wreorder]
gsStreamOutput(nullptr),
^
=> Fix Android build errors

glslang/MachineIndependent/iomapper.cpp, glslang/Public/ShaderLang.h
Adds a notification phase to the io remapper.
The idea behind this is to give the user a
chance to group uniforms and/or in/out variables
for a better pipeline layout sharing for vulkan.
=> Notification phase for io remapper

SPIRV/GlslangToSpv.h, SPIRV/doc.h, StandAlone/StandAlone.cpp, glslang/MachineIndependent/LiveTraverser.h, glslang/MachineIndependent/RemoveTree.h, glslang/MachineIndependent/ScanContext.h, glslang/MachineIndependent/gl_types.h, glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpAtom.cpp, glslang/MachineIndependent/preprocessor/PpScanner.cpp, glslang/MachineIndependent/preprocessor/PpTokens.cpp, glslang/MachineIndependent/propagateNoContraction.h
When glslang is compiled with some other build system that uses lumped/unity/batch builds, it had some compile errors -- mostly due to missing include guards in some headers, and redefinitions of preprocessor macros.
=> Fix for lumped/unity/batch builds

glslang/Include/Types.h, glslang/MachineIndependent/SymbolTable.h, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Marking as WIP since it might deserve discussion or at least explicit consideration, as it touches the TType member data.
During type sanitization, the TQualifier's TBuiltInVariable type is lost.  However, sometimes it's needed downstream.  There were already two methods in use to track it through to places it was needed: one in the TParameter, and another in a map in the HlslParseContext used for structured buffers.
The latter was going to be insufficient when SB types with counters are passed to user functions, and it's proving awkward to track the data to where it's needed. This PR holds a proposal: track the original declared builtin type in the TType, so it's trivially available anywhere needed.
This lets the other two mechanisms be removed (as they are in this PR).  There's also a …
=> track declared builtin type

Test/baseResults/hlsl.tx.overload.frag.out, Test/hlsl.tx.overload.frag, glslang/MachineIndependent/SymbolTable.cpp, gtests/Hlsl.FromFile.cpp
Name mangling did not account for the vector size in the template type of a texture. E.g, Texture2D&lt;float**3**&gt;.  This adds that.  The mangle is as it ever was for the vec4 case, which leaves all GLSL behavior and most HLSL mangling behavior uneffected.  For vec1-3 the size is added to the mangle.  (Review request: as an alternate choice, it could also be added to the mangle in all cases, though probably with a large number of test changes).
Current limitation: textures cannot presently be templatized on structured types, so this works only for textures templatized on vectors of basic types.
Fixes #895.
=> HLSL: allow name mangling based on texture template type

Test/baseResults/hlsl.texture.subvec4.frag.out, Test/hlsl.texture.subvec4.frag, gtests/Hlsl.FromFile.cpp
This changes no functional code.  There was a bit of a testing hole in that textures templatized on sub-vec4 types were not being exercised with intrinsics.  This PR adds one new test for coverage of that case.
=> HLSL: add test coverage for sub-vec4 texture intrinsics

hlsl/hlslParseHelper.cpp
One liner to eliminate a compile warning.
=> HLSL: compilation warning fix: no functional change

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.450.tesc.out
This was redundant in two ways:
1) it replicated algorithms owned in the front end, and
2) it sometimes left location information on both a block and its members.
=> Replace #422: Remove the redundant location setting in AST->SPIR-V.

glslang/MachineIndependent/ParseHelper.h
This fixes TParseContextBase to build without warning with -Wreorder is defined in clang.
```
In file included from external/com_github_KhronosGroup_glslang/glslang/MachineIndependent/ParseHelper.cpp:38:
external/com_github_KhronosGroup_glslang/glslang/MachineIndependent/ParseHelper.h:83:13: warning: field 'limits' will be initialized after field 'parsingBuiltins' [-Wreorder]
limits(resources.limits),
```
=> Fixing initialization order to fix -Wreorder warning in clang.

glslang/MachineIndependent/iomapper.cpp, glslang/Public/ShaderLang.h
- adds stage parameter to end notify (so that the resolver does not need to track it)
- adds begin notify (to be more explicit)
- adds begin resolve (to be more explicit)
- adds end resolve (to be more explicit)
=> io resolver improvements

StandAlone/StandAlone.cpp
find_first_of returns size_t, was overflowing int and triggering some compiler warnings.
=> Fix StandAlone.cpp compilation warnings

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.amend.frag.out, Test/baseResults/hlsl.gatherRGBA.array.dx10.frag.out, Test/baseResults/hlsl.gatherRGBA.basic.dx10.frag.out, Test/baseResults/hlsl.gatherRGBA.offset.dx10.frag.out, Test/baseResults/hlsl.gatherRGBA.offsetarray.dx10.frag.out, Test/baseResults/hlsl.gathercmpRGBA.offset.dx10.frag.out, Test/baseResults/hlsl.getdimensions.rw.dx10.frag.out, Test/baseResults/hlsl.implicitBool.frag.out, Test/baseResults/hlsl.isfinite.frag.out, Test/baseResults/hlsl.load.2dms.dx10.frag.out, Test/baseResults/hlsl.load.array.dx10.frag.out, Test/baseResults/hlsl.load.basic.dx10.frag.out, Test/baseResults/hlsl.load.basic.dx10.vert.out, Test/baseResults/hlsl.load.buffer.dx10.frag.out, Test/baseResults/hlsl.load.buffer.float.dx10.frag.out, Test/baseResults/hlsl.load.offset.dx10.frag.out, Test/baseResults/hlsl.load.offsetarray.dx10.frag.out, Test/baseResults/hlsl.load.rwbuffer.dx10.frag.out, Test/baseResults/hlsl.load.rwtexture.array.dx10.frag.out, Test/baseResults/hlsl.load.rwtexture.dx10.frag.out, Test/baseResults/hlsl.rw.atomics.frag.out, Test/baseResults/hlsl.rw.bracket.frag.out, Test/baseResults/hlsl.rw.scalar.bracket.frag.out, Test/baseResults/hlsl.rw.vec2.bracket.frag.out, Test/baseResults/hlsl.tx.bracket.frag.out
From comment about this:
Adjust alignment for HLSL rules
TODO: make this consistent in early phases of code: adjusting this late means inconsistencies with earlier code, which for reflection is an issue.
Until reflection is brought in sync with these adjustments, don't apply HLSL offsets to $Global,
which is the most likely to rely on reflection, and least likely to rely
implicit layouts.
=> Address part B of #982: $Global will use std140 instead of HLSL offsets.

glslang/MachineIndependent/ParseHelper.cpp
The statement `const TIntermSequence& aggArgs = *argp;` triggers undefined behavior when `argp` is NULL.
While `argp` is never NULL when `aggArgs` gets used, compilers can still assume that `argp` is never NULL under any circumstances due to the unconditional assignment of `aggArgs` and wrongly optimize out (i.e. delete) the `else` branch above.
Credit goes to UndefinedBehaviorSanitizer for spotting this bug: `
/home/polarina/projects/Vulkan-LoaderAndValidationLayers/external/glslang/glslang/MachineIndependent/ParseHelper.cpp:1389:39: runtime error: reference binding to null pointer of type 'const struct TIntermSequence'
`
=> Fix NULL pointer dereference in TParseContext::builtInOpCheck

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.samplecmplevelzero.array.dx10.frag.out
The dref parameter was being used as the LOD.  Now the dref is the dref, and the LOD is the LOD.  Would only have impacted texture cube array form, which uses all 4 components of the vec4 coord.
Fixes #998.
=> Fix dref explicit LOD form of sample with cube texture arrays

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.structbuffer.coherent.frag.out, Test/baseResults/hlsl.structbuffer.frag.out, Test/baseResults/spv.memoryQualifier.frag.out, Test/baseResults/spv.ssbo.autoassign.frag.out
We encounter this problem when the shader is written like this:
```
struct S
{
vec4 f;
};
layout(binding = 0) buffer Buf1
{
readonly S s1;
};
layout(binding = 1) buffer Buf2
{
writeonly S s2;
};
```
In SPIR-V, memory qualifiers are propagated to structure members. So `S.f` have both "readonly" and "writeonly" decorations. This is erroneous.
=> SPV: Memory qualifiers should decorate top-level block members

hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Two non-functional changes:
1. Remove flattenLevel, which is unneeded since at or around d1be7545c6a23657587dfe3bc4b149c91290a66f.
2. Fix build warning about unused variable in executeInitializer().
=> HLSL: Non-functional: warning fix + remove unused member

Test/baseResults/hlsl.matpack-pragma.frag.out, Test/hlsl.matpack-pragma.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
This adds support for #pragma pack_matrix() to the HLSL front end.
The pragma sets the default matrix layout for subsequent unqualified matrices in structs or buffers.  Explicit qualification overrides the pragma value.  Matrix layout is not permitted at the structure level in HLSL, so only leaves which are matrix types can be so qualified.
Addresses #677 (partially)
Note that due to the semantic (not layout) difference in first matrix indirections between HLSL and SPIR-V, the sense of row and column major are flipped.  That's independent of this PR: just a factor to note.  A column_major qualifier appears as a RowMajor member decoration in SPIR-V modules, and vice versa.
=> HLSL: implement #pragma pack_matrix(layout)

Test/baseResults/hlsl.texture.struct.frag.out, Test/hlsl.texture.struct.frag, Test/hlsl.texture.subvec4.frag, glslang/Include/Types.h, glslang/MachineIndependent/SymbolTable.cpp, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Some languages allow a restricted set of user structure types returned from texture sampling operations.  Restrictions include the total vector size of all components may not exceed 4, and the basic types of all members must be identical.
This adds underpinnings for that ability.  Because storing a whole TType or even a simple TTypeList in the TSampler would be expensive, the structure definition is held in a table outside the TType.  The TSampler contains a small bitfield index, currently 4 bits to support up to 15 separate texture template structure types, but that can be adjusted up or down.  Vector returns are handled as before.
There are abstraction methods accepting and returning a TType (such as may have been parsed from a grammar).  The new methods will accept a texture template …
=> HLSL: add methods to handle user structures in texture template type.

SPIRV/GLSL.ext.KHR.h, SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.stereoViewRendering.vert.out, Test/baseResults/spv.viewportArray2.tesc.out, Test/baseResults/spv.viewportArray2.vert.out
I'm unclear on when to require which extension, given there is a choice, and the more general choice (EXT) is available after the specific choice (NV).
Feel free to update, etc.
=> SPV: 1st pass implementation of SPV_EXT_shader_viewport_index_layer.

Test/baseResults/hlsl.clipdistance-1.frag.out, Test/baseResults/hlsl.clipdistance-1.vert.out, Test/baseResults/hlsl.clipdistance-2.frag.out, Test/baseResults/hlsl.clipdistance-2.vert.out, Test/baseResults/hlsl.clipdistance-4.frag.out, Test/baseResults/hlsl.clipdistance-4.vert.out, Test/baseResults/hlsl.clipdistance-5.frag.out, Test/baseResults/hlsl.clipdistance-5.vert.out, Test/baseResults/hlsl.clipdistance-6.frag.out, Test/baseResults/hlsl.clipdistance-6.vert.out, Test/baseResults/hlsl.clipdistance-7.frag.out, Test/baseResults/hlsl.clipdistance-7.vert.out, Test/baseResults/hlsl.clipdistance-8.frag.out, Test/baseResults/hlsl.clipdistance-8.vert.out, Test/baseResults/hlsl.clipdistance-9.frag.out, Test/baseResults/hlsl.clipdistance-9.vert.out, Test/baseResults/hlsl.semantic.vert.out, hlsl/hlslParseHelper.cpp
While adding geometry stage support for clip/cull, it transpired that the existing clip/cull support was not setting the type of the result of indexing into the clup/cull variable.  That's a defect independent of the geometry 
support, so to get a lot of unrelated diffs out of the geometry PR, this problem is addressed separately.  It'll matter more when another indirection is added to the result of this indirection.  In advance of that, it's just qualifier changes.
This doesn't appear to change the generated SPIR-V, but that's probably down to something else being forgiving.
=> HLSL: (minor) fix type on clip/cull index result

glslang/MachineIndependent/Initialize.cpp
The definitions of gl_Layer and gl_ViewportIndex should be independent of vendor implementation.
=> Fix issues of GL_ARB_viewport_layer_array

SPIRV/spvIR.h, glslang/MachineIndependent/iomapper.cpp
Remove complaint about unused function parameter in resolveUniformLocation()
Fix warning about defined but not used variable from spvIR.h.
Fixes #1041.
=> WIP: Linux build warning fix

StandAlone/StandAlone.cpp
This adds `--stdin` which allows you to specify that a file should be provided on stdin. Since we can't parse the filename in that case, we'll have to force the user to specify `-S` as well.
I handled both the legacy and modern ways for stdin and tested both.
I think me providing a dummy WorkItem called "stdin" in case of stdin is not too bad of a hack. I tried to make the best usage of what was already there in order to keep the patch as small as possible.
This also fixes #598 so that's nice.
=> Add stdin option (fixes #598)

hlsl/hlslParseHelper.cpp
Remove an unused 'this' entry from a lambda capture list.
This cleans up a unused-lambda-capture warning.
=> Delete unused 'this' capture

CMakeLists.txt, External/CMakeLists.txt, SPIRV/CMakeLists.txt
Also added known-good mechanism to fetch latest validated spirv-tools.
Also added -Od and -Os to disable optimizer and optimize for size.
Fetching spirv-tools is optional for both glsl and hlsl. Legalization
of hlsl is done by default if spirv-opt is present at cmake time.
Optimization for glsl is currently done through explicit option.
Also includes code from JohnK to disable current workarounds dealing
with writes of opaque types.
=> CMake file changes for SPIR-V legalization for HLSL

Test/baseResults/hlsl.gathercmpRGBA.offset.dx10.frag.out, Test/baseResults/hlsl.samplecmp.array.dx10.frag.out, Test/baseResults/hlsl.samplecmp.basic.dx10.frag.out, Test/baseResults/hlsl.samplecmp.negative.frag.out, Test/baseResults/hlsl.samplecmp.offset.dx10.frag.out, Test/baseResults/hlsl.samplecmp.offsetarray.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.array.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.basic.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.offset.dx10.frag.out, Test/baseResults/hlsl.samplecmplevelzero.offsetarray.dx10.frag.out, Test/hlsl.samplecmp.negative.frag, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Texture shadow mode must match the state of the sampler they are combined with.  This change does that, both for the AST and the symbol table.  Note that the texture cannot easily be *created* the right way, because this may not be known at that time.  Instead, the texture is subsequently patched.
This cannot work if a single texture is used with both a shadow and non-shadow sampler, so that case is detected and generates an error. This is permitted by the HLSL language, however.  See #1073 discussion.
Fixed one test source that was using a texture with both shadow and non-shadow samplers.
Addresses #1073.  (Is not a complete fix, given mismatch between what HLSL allows and what SPIR-V currently requires).
=> HLSL: force textures to shadow modes from combined samplers

glslang/Include/intermediate.h
Every other type of node has a getAsXXXNode() method for them, a getAsLoopNode() for loop node is also necessary.
=> Add getAsLoopNode() method for TIntermLoop

CMakeLists.txt
When including this Project as subdirectory, cmake pushes a warning about the [CMP0048 Policy](https://cmake.org/cmake/help/latest/policy/CMP0048.html). This would be fixed when adding
```cmake
if (POLICY CMP0048)
cmake_policy(SET CMP0048 NEW)
endif()
```
after `cmake_minimum_required(VERSION 2.8.12)`.
Same as KhronosGroup/SPIRV-Tools/issues/864
=> Set cmake-policy CMP0048 to NEW

hlsl/hlslAttributes.cpp, hlsl/hlslAttributes.h, hlsl/hlslParseHelper.cpp
There was some code replication around getting string and integer values out of an attribute map.  This adds new methods to the TAttributeMap class to encapsulate some accessor details.
=> HLSL: nonfunctional: add helper access methods to TAttributeMap

Test/baseResults/invalidSwizzle.vert.out, Test/invalidSwizzle.vert, glslang/MachineIndependent/ParseHelper.cpp, gtests/AST.FromFile.cpp
This seems like an adequate fix, it also makes the result make more sense for vector swizzles which were previously considered "out of range" on void, instead of just not applicable.
Resolves #1108
=> Don't try to swizzle void.

Test/baseResults/cppIntMinOverNegativeOne.frag.out, Test/cppIntMinOverNegativeOne.frag, glslang/MachineIndependent/preprocessor/Pp.cpp, gtests/AST.FromFile.cpp
This is undefined behaviour which raises SIGFPE on x86.
Most C++ preprocessors evaluate this silently to 0.
Resolves #1112
=> Preprocessor: Evaluate INT_MIN / -1 to 0.

StandAlone/StandAlone.cpp, Test/baseResults/hlsl.shift.per-set.frag.out, Test/hlsl.shift.per-set.frag, Test/runtests, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/localintermediate.h, glslang/Public/ShaderLang.h
WIP: still needs ~~interfacing with TProcesses~~, ~~testing~~, ~~documentation of new APIs~~, code cleanup, etc.
This PR adds the ability to provide per-descriptor-set IO mapping shift values.  If a particular binding does not land into a per-set value, then it falls back to the prior behavior (global shifts per resource class).
Because there were already 6 copies of many different methods and internal variables and functions, and this PR would have added 6 more, a new API is introduced to cut down on replication and present a cleaner interface.  For the global (non-set-specific) API, the old entry points still exist for backward compatibility, but are phrased internally in terms of the following.
// Resource type for IO resolver
enum TResourceType {
EResSampler,
EResTexture,
EResImage, …
=> Add per-descriptor-set IO mapping shift values.

glslang/MachineIndependent/localintermediate.h, hlsl/hlslParseHelper.cpp
Two unrelated, minor tweaks:
(1) Use std::array for shiftBindingForSet, rather than a C array.  Now matches shiftBinding.
(2) Add parens in shouldFlatten() to make compiler warning happy.
=> Nonfunctional: minor: use std::array for per-set shifts, fix warning.

Test/baseResults/invalidSwizzle.vert.out, Test/invalidSwizzle.vert, glslang/Include/intermediate.h, glslang/MachineIndependent/ParseHelper.cpp
This should solve all similar issues, for example if it's possible to get glslang to try to swizzle an `EbtBlock`.
Let me know if you figure the conditions for this should be in the `TType`/`TIntermediate` class instead of inline.
Resolves #1117.
=> Only try swizzles on vectors, numbers, and booleans.

.appveyor.yml
Pushing a commit to the master branch will trigger a build on
Appveyor. If the build is successful, the artifacts will be
collected and pushed to GitHub Releases, under the "master-tot"
release.
=> Appveyor: auto deploy build artifacts to GitHub Releases

StandAlone/StandAlone.cpp, Test/runtests, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/localintermediate.h, glslang/Public/ShaderLang.h
**WIP until coordination with all involved parties.**
Per feedback on PR #1111, this reverses the order of the parameters for the setShiftBindingForSet API.
It is now:
void TShader::setShiftBindingForSet(TResourceType res, unsigned int base, unsigned int set);
No test result diffs (but the test source invocation reverses the order).
=> Reverse order of setShiftBindingForSet parameters

Test/validate-shaders.sh
**WIP: This has only been tried in a linux environment so far**
This script will crank a supplied set of glslang test shaders through the spirv-val tool, reporting on the results.
There are some important things to note:
* Like 'runtests', this must be invoked from the 'Test' subdirectory.
* This is mostly useful on the hlsl.* tests, although it is not strictly limited to those.  The reason is that most of the glsl tests either contain validation error cases, and so fail to compile, or are not using a #version  compatible with producing SPIR-V modules.
* Some tests, such as negative tests, or many of the glsl tests, have intentional compilation errors.  This script treats that as OK.  A failure is a successfully compiling shader which proceeds to fail spirv-val.
* spirv-val is looked for …
=> Add script to crank test shaders through spirv-val

OGLCompilersDLL/InitializeDll.cpp, OGLCompilersDLL/InitializeDll.h, StandAlone/StandAlone.cpp, glslang/Include/InitializeGlobals.h, glslang/Include/PoolAlloc.h, glslang/Include/ShHandle.h, glslang/MachineIndependent/PoolAlloc.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/OSDependent/Unix/ossource.cpp, glslang/Public/ShaderLang.h
First commit: Non-functional; clean-up rationalization.
Second commit:  
> Move to a normal model of ownership of memory pools, for new/delete.
> Addresses step 4 of #976, overlaps #916.
> For each pool, now, it is newed, remembered, and freed by the same entity, rather than having a mix (thread finalize freeing current pool) that could  lead to double freeing of the same pool. It is quite rational and simple now.
> This will enable reinstalling process and thread tear down.
Third commit: On it's way, will actually add tear down logic that's been skipped so far
Main issue: Nothing triggering per-thread tear down of additional threads.
=> Memory fixes, round 1

Test/baseResults/hlsl.gs-hs-mix.tesc.out, Test/hlsl.gs-hs-mix.tesc, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp
If a shader includes a mixture of several stages, such as HS and GS, the non-stage output geometry should be ignored, lest it conflict with the stage output.
Fixes #1153
=> HLSL: ignore geometry attributes on non-GS stages.

Test/baseResults/hlsl.mul-truncate.frag.out, Test/hlsl.mul-truncate.frag, glslang/Include/Types.h, gtests/Hlsl.FromFile.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
**WIP: doesn't yet handle mat*mat**
HLSL truncates the vector, or one of the two matrix dimensions if there is a dimensional mismatch in m\*v, v\*m, or m\*m.
This PR adds that ability.  Conversion constructors are added as required.
Fixes #1160
=> WIP: HLSL: matrix and vector truncations for m*v, v*m, m*m

Test/baseResults/hlsl.mul-truncate.frag.out, Test/hlsl.mul-truncate.frag, hlsl/hlslParseHelper.cpp
Goes with PR #1161, and completes the space for mul() implicit truncations.
Note that the v*v and scalar cases are already handled by existing code.
=> HLSL: add implicit mat*mat truncations

Test/baseResults/hlsl.cbuffer-identifier.vert.out, Test/hlsl.cbuffer-identifier.vert, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp
Issue #791 was partially fixed by PR #1161 (the mat mul implicit truncations were its main point), but it still wouldn't compile due to the use of ConstantBuffer as an identifier.  Apparently those fall into the same class as "float float", where float is both a type and an identifier.
This allows struct definitions with such keyword-identifiers, and adds ConstantBuffer to the set.  'cbuffer int' is legal in HLSL, and 'struct int' appears to only be rejected due to the redefinition of the 'int' type.
Fixes #791
=> HLSL: allow keyword-identifiers as cbuffer/struct names.

Test/baseResults/hlsl.cbuffer-identifier.vert.out, Test/baseResults/hlsl.mul-truncate.frag.out, hlsl/hlslParseHelper.cpp
Minor change to add a compilation warning on implicit matrix size truncations.
=> HLSL: minor: add warning for mat() matrix size truncation

known_good.json
This fixes spirv-tools issue 989 where if-break can be incorrectly
deleted from a loop.
=> Update spirv-tools known-good

hlsl/hlslParseHelper.cpp
In DX10/DX11 you can only output RT/Viewport indices from GS; however,
DX11.4/DX12 add support for outputting these from VS as well.
This is supported by Vulkan if the relevant extension is available, and
by MSL and by MSL (which you can cross-compile to via SPIRV-Cross).
=> HLSL: Implement support for RT/Viewport output from VS

glslang/MachineIndependent/ParseHelper.cpp
Fix compilation error under g++ 5.4.0.  Possible g++ defect, or possible difference in behavior.  Either way, this compiles now under that version.
=> compile error fix for g++ 5.4.0

Test/baseResults/hlsl.structbuffer.byte.frag.out, Test/baseResults/hlsl.structbuffer.fn2.comp.out, Test/baseResults/hlsl.structbuffer.rwbyte.frag.out, hlsl/hlslParseHelper.cpp
Set type to r-value resulting from indexing vector, to prevent
float->uint conversion when source is already uint. Resulting
OpConvertFToU would otherwise fail validation because source is
already uint.
=> HLSL: Fix possibly incorrect type conversion in Store2-3-4

SPIRV/GlslangToSpv.cpp
TGlslangToSpvTraverser::getExtBuiltins is only used when AMD_EXTENSIONS
is defined, so only define it in that case to avoid an unused function
warning.
=> Fix unused function warning.

glslang/MachineIndependent/ParseHelper.cpp
An error message should be reported if the interpolant is not an input.
=> Fix an issue of interpolateAtVertexAMD().

glslang/MachineIndependent/Initialize.cpp
EShLangFragment falls through to EShLangCompute, only #ifndef AMD_EXTENSIONS.
This is probably a bug.
=> EShLangFragment falls through to EShLangCompute, only #ifndef AMD_EXTENSIONS.

known_good.json
Contains the following improvements:
Fixes 1341: Atomics (and other instructions with side-effects) removed.
Add folding for redundant add/sub/mul/div/mix operations
Add constant folding rules for floating-point comparison
Add folding of redundant OpSelect insns
Add folding of OpCompositeExtract and OpConstantComposite
=> Update spirv-tools known_good

hlsl/hlslGrammar.cpp
Since GL_KHX_shader_explicit_arithmetic_types_float16/GL_KHX_shader_explicit_arithmetic_types defines float16, min types could be mapped to float16/(u)int16 without AMD_EXTENSIONS.
=> Allow --hlsl-enable-16bit-types to be used without AMD_EXTENSIONS

glslang/Include/Common.h
On some systems sstream defines snprintf, this leads to the a redefinition of sprintf_s if snprintf is defined before checking if it exists in sstream.
=> include/Common.h: reorder includes to avoid redefinition on some platforms

glslang/MachineIndependent/preprocessor/PpScanner.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslScanContext.cpp, hlsl/hlslTokens.h
- Add missing constructor ops to support float16/int16/uint16 types
- Allow half float literals
- Correct two errors of double literal parse in HLSL: extension check and
postfix
=> HLSL: Correct some mistakes for min16 types

glslang/MachineIndependent/iomapper.cpp
Currently there's a few en-dashes in a comment in `iomapper.cpp`, I think because of copy-paste from [this MSDN page](https://msdn.microsoft.com/en-us/library/windows/desktop/dn899207%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). Without a UTF-8 BOM if the system codepage doesn't include the character this can lead to compile warnings - see baldurk/renderdoc#915. I think this change is preferable to adding a BOM and potential headaches from that.
If this change isn't desired then feel free to reject the PR, but I think it's a good idea.
=> Replace en-dash with simple ASCII hyphen

SPIRV/SpvBuilder.cpp, glslang/MachineIndependent/attribute.cpp, hlsl/hlslParseHelper.cpp
glslang/SPIRV/SpvBuilder.cpp:2533:27: error: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
for (int c = 0; c < accessChain.swizzle.size(); ++c)
~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
glslang/hlsl/hlslParseHelper.cpp:69:5: error: field 'cullDistanceInput' will be initialized after field 'clipDistanceOutput' [-Werror,-Wreorder]
cullDistanceInput(nullptr),
^
1 error generated.
glslang/glslang/MachineIndependent/attribute.cpp:85:16: error: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Werror,-Wsign-compare]
if (argNum >= args->getSequence().size())
~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
=> Fix build several build errors

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h
When a matrix is divided by a scalar it tries to take the reciprocal
of the scalar to convert the operation into a multiply. However it was
always doing this by making a 32-bit constant. If the scalar is a
double then this would end up making an FDiv instruction with
different types in the operands.
This patch adds a helper method called makeFpConstant which makes a
floating-point constant of the given type. The code to take the
reciprocal now uses it to make the same type as the result.
Fixes https://github.com/KhronosGroup/glslang/issues/1278
=> Use the correct type for the constant for matrix/scalar division

glslang/MachineIndependent/ParseHelper.cpp
Int64 and uint64 are disallowed as fragment shader outputs, similar to double.
=> Add additional error check for fragment shader outputs

Test/baseResults/spv.debugInfo.1.1.frag.out, Test/baseResults/spv.debugInfo.frag.out, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/localintermediate.h
These patches make --auto-map-locations take into account the size of uniforms (structs and arrays occupy more than one location) and also assign locations to opaque types.
v2: Change the baseResults test data to expect the new uniform decoration when using -G.
=> Improve --auto-map-locations for uniforms (v2)

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, Test/array.frag, Test/baseResults/150.tesc.out, Test/baseResults/310.comp.out, Test/baseResults/310.tese.out, Test/baseResults/310AofA.vert.out, Test/baseResults/310implicitSizeArrayError.vert.out, Test/baseResults/320.tese.out, Test/baseResults/400.tese.out, Test/baseResults/420.vert.out, Test/baseResults/430.comp.out, Test/baseResults/array.frag.out, glslang/Include/Types.h, glslang/Include/arrays.h, glslang/Include/intermediate.h, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/linkValidate.cpp, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Non-functional. Rationalizations enabling future generalizations:
- Use much simpler method to update implicit array sizes.      The previous overly complicated method was error prone.
- Rationalize all use of unsized arrays.
- Combine decorations when generating SPIR-V, to simplify      adding extensions.
=> Array rationalization

glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h
This allows for outside applications to access a uniform block binding number.
=> Added getter for uniform block bindings

CMakeLists.txt, SPIRV/CMakeLists.txt, glslang/CMakeLists.txt, hlsl/CMakeLists.txt
This adds the ability to switch the projects glslang, SPIRV, and HLSL from static to shared libraries by setting ${BUILD_SHARED_LIBS} to ON. ${BUILD_SHARED_LIBS} is set to OFF by default.
(Fixed pull request)
=> Allowed for LIB_TYPE to be set to switch between static and shared libs for glslang, SPIRV, and HLSL

known_good.json
Changes include:
Fix SSA rewrite for nested loops.
Add support for two new extensions:
- SPV_NV_shader_subgroup_partitioned
- SPV_EXT_descriptor_indexing
Legalize OpImageTexelPointer
Copy propagate arrays
=> Update spirv-opt known good

StandAlone/StandAlone.cpp
This patch makes  the validator accept *.stage_name.[g/h]lsl pattern
for file names.
This patch preserves previous behavior (i.e. *.vert/*.frag/etc. in file
names still work).
=> Make glslang validator support files ending in .glsl

SPIRV/GlslangToSpv.cpp
Interpolation functions, using 16-bit interpolants, should always emit this extension string regardless of vulkan enviornment version.
=> Fix issue #1376: SPV_AMD_gpu_shader_half_float is not emitted under vulkan1.1

SPIRV/CMakeLists.txt, glslang/CMakeLists.txt
This makes glslang simpler to embed in larger projects.
=> CMake: use target_include_directories to expose includes

SPIRV/GlslangToSpv.cpp, known_good.json
Includes:
Fold FMix feeding Extract, and use the simplification pass.
Also adds IfConversion and VectorDCE to spirv-opt recipes.
=> Update spirv-tools known-good.

glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/preprocessor/PpTokens.cpp
Fixes a few compilation warnings.  This makes the loop variable type the same as the return type of sizeof() (which is size_t).
No functional changes or test diffs.
=> Fix several signed/unsigned comparison compile warnings.

Test/baseResults/stringToDouble.vert.out, Test/stringToDouble.vert
1e-323 was flushed to zero.
1e-308 is also flushed to zero.
Use 1e-307 instead, which still satisfies the test intent.
Fixes #1400
=> Relax a stringToDouble test for, OSX AppleClang 9.1

SPIRV/SPVRemapper.cpp
=> Add support for OpConstantNull and OpConstantSampler to spirv-remap

update_glslang_sources.py
- remove unused variable to pass pylint
- Use another approach to detect if known-good remote is already
present to avoid the need for "ignore following errors" message.
=> script: Improve update sources script

.appveyor.yml
This would help me downstream in [Shader Playground](http://shader-playground.timjones.io/), where I have a build script that downloads a number of compilers, and it's easier to work with existing CLI binaries.
Of course, if there's a reason why `spirv-remap.exe` isn't (yet) included in the AppVeyor artifacts, I can always build from source in my build script.
=> Include spirv-remap.exe in AppVeyor artifacts

SPIRV/CMakeLists.txt, SPIRV/disassemble.cpp, SPIRV/disassemble.h, StandAlone/CMakeLists.txt, StandAlone/StandAlone.cpp
This allows printing SPIR-V in the standard form, as per SPIR-V tools.  Can be used, for example, like:
```
glslangValidator -V --spirv-dis t.frag  # compile for Vulkan, print SPIR-V assembly via SPIRV-Tools
```
The existing and default uses of glslang are all still as they were.
@dneto0 and @greg-lunarg, or anyone, a few design questions:
- Recommendations for the  option spelling and interactions? Note, I am not yet intending to switch how the regression suites work.
- I reused ENABLE_OPT to know if SPIRV-Tools was present or not, and it seems it had some use like that already. Should we change the name to generalize, or have a two-level hierarchy? Seems the hard part of this change will be managing CMake options and compiler flags. Simple is to just keep using ENABLE_OPT for this, …
=> SPV: Add option to print disassembly in standard form using SPIRV-Tools.

glslang/MachineIndependent/Constant.cpp
Constant.cpp will throw a floating point divide by zero if floating point exceptions are enabled in Win32 causing the program to crash. This fix manually checks the right-hand argument of the division and sets appropriate Infinity, Negative Infinity, or NAN as if the floating point exceptions were disabled.
=> Constant.cpp Floating point divide by zero

Test/baseResults/hlsl.automap.frag.out, Test/baseResults/hlsl.reflection.binding.frag.out, Test/baseResults/hlsl.reflection.vert.out, Test/baseResults/hlsl.shift.per-set.frag.out, Test/baseResults/reflection.vert.out, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/reflection.cpp, glslang/MachineIndependent/reflection.h, glslang/Public/ShaderLang.h
This pull request adds the exposition of the shader stages on uniforms reflection.
This approach seems the only way to get this information.
Is there any other possible implementation?
=> Reflection exposes the Shader Stages where a Uniform is present

.travis.yml
The Travis-CI bot downloads a copy of the Android NDK.  The source
we get it from recently updated to Android NDK r17b which no longer
supports android-12.  So target android-16 instead, since it is
supported by NDK 17b and will not be removed until after NDK r18.
Fixes #1439
=> WIP: Travis-CI: Use Android NDK r13b specifically   

.travis.yml
More recent NDK releases have their own CMake toolchain file.
Use it.
Also, download the NDK from github.com:dneto0/android-ndk.
That is a fork of the repo we used to use, but we have more
control over how long it stays stable.
=> NDK build: Use NDK r17b and its own CMake toolchain file

CMakeLists.txt, SPIRV/CMakeLists.txt
These changes allow for SPVRemapper to not be build (builds by default), and allows for higher up projects to override the default output postfix.
=> CMake options for postfix and SPVRemapper.

CMakeLists.txt
This is totally optional, but lets people build this repo with
ccache to improve rebuild speeds.  It also can help a great deal
on ccache-enabled CI systems like Travis-CI.  We build fixed
revisions of glslang a lot on Travis, so this will be a big help
with CI machine loading.
=> build: Add ccache option to CMake config

known_good.json
Includes the following:
Add Vulkan 1.1 capability sets
Don't merge types of resources
Remove stores of undef.
Make sure the constant folder get the correct type.
=> Update spirv-tools known good

Test/baseResults/spv.separate.frag.out, Test/baseResults/vulkan.frag.out, Test/vulkan.frag, glslang/MachineIndependent/ParseHelper.cpp, hlsl/hlslParseHelper.cpp, hlsl/hlslParseHelper.h
Fixes #854. But, only good if we are not trying to use the same texture for both shadow and non-shadow constructors.
Force the type of the texture to have 'shadow' set when it is constructed with a samplerShadow.
=> GLSL/SPV: If a texture is used with a shadow sampler, force 'shadow'.

glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/reflection.h
1) On some old versions of MSVC:
glslang\MachineIndependent\Constant.cpp(187): warning C4056: overflow in floating-point constant arithmetic
On this platform the definition of INFINITY is as follows:
#ifndef _HUGE_ENUF
#define _HUGE_ENUF  1e+300  // _HUGE_ENUF*_HUGE_ENUF must overflow
#endif
#define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
Moving the negation outside the cast seems to resolve that issue.
2) Some Linux compilers were unhappy with lines 226/227
glslang/MachineIndependent/Constant.cpp: In member function 'virtual glslang::TIntermTyped* glslang::TIntermConstantUnion::fold(glslang::TOperator, const glslang::TIntermTyped*) const':
glslang/MachineIndependent/Constant.cpp:226:99: error: integer overflow in expression [-Werror=overflow]
else if (rightUnionArray[i].getIConst() …
=> Fix various build warnings/errors

SPIRV/CMakeLists.txt, SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h, SPIRV/SpvPostProcess.cpp
When capabilities are needed for specific SPIR-V instructions, it is
fragile to do so based on GLSL/AST usage; it should be based on actual
instructions they got translated to.
=> Non-Functional: Add postprocess as more robust way to add capabilities

known_good.json
Includes:
Update OpPhi instructions after splitting block. (#1783)
Don't change decorations and names in merge return. (#1777)
Transform to combine consecutive access chains
Handle undef literal value in vector shuffle
Fix block ordering in dead branch elim
Fix finding constant with particular type. (#1724)
Fix infinite loop while folding OpVectorShuffle (#1722)
Fix size error when folding vector shuffle. (#1721)
Layout validation: Permit {vec3; float} tight packing
=> Update SPIRV-Tools known good.

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h, SPIRV/SpvPostProcess.cpp, SPIRV/spvIR.h, Test/baseResults/spv.16bitstorage-int.frag.out, Test/baseResults/spv.16bitstorage-uint.frag.out, Test/baseResults/spv.16bitstorage.frag.out, Test/baseResults/spv.8bitstorage-int.frag.out, Test/baseResults/spv.8bitstorage-uint.frag.out
Only when operations stray outside the 8/16-bit storage-capabilities
are the general (pure 8/16-bit) capabilities needed.
=> SPV: only declare the pure 8/16-bit capabilities when needed.

update_glslang_sources.py
This one small change allows the update_glslang_sources.py script to operate correctly with Python 2 and Python 3.
Change the string literal type to "bytes" so that it matches the type returned by the subprocess calls.  Otherwise, under Python 3, the search for "known-good" in the list of remotes always fails.  This is OK for the first execution of update_glsang_sources, since the remote is not there on the first run.  But on subsequent runs, the search still fails to match and the script stops when trying to create a remote that already exists.
=> tooling: Fix update sources script for Python 3

SPIRV/bitutils.h
the following warning gets emitted:
```
In file included from ./Vulkan/glslang/SPIRV/hex_float.h:39,
from ./Vulkan/glslang/SPIRV/SpvBuilder.cpp:49:
./Vulkan/glslang/SPIRV/bitutils.h: In instantiation of ‘Dest spvutils::BitwiseCast(Src) [with Dest = spvutils::Float16; Src = short unsigned int]’:
./Vulkan/glslang/SPIRV/hex_float.h:138:47:   required from ‘T spvutils::FloatProxy<T>::getAsFloat() const [with T = spvutils::Float16]’
./Vulkan/glslang/SPIRV/hex_float.h:821:52:   required from here
./Vulkan/glslang/SPIRV/bitutils.h:29:14: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class spvutils::Float16’; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
std::memcpy(&dest, &source, sizeof(dest)); …
```
=> Fix compiler warning emitted from GCC8

BUILD.gn, SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h, build_overrides/glslang.gni, glslang/MachineIndependent/ParseHelper.cpp
This CL adds the necessary configuration to build glslang inside a
Chromium checkout. Two build warnings were fixed in the process to
make things compile.
=> Add BUILD.gn configuration.

Test/baseResults/spv.GeometryShaderPassthrough.geom.out, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/linkValidate.cpp
For GL_NV_geometry_shader_passthrough extension, the inferred output primitive for ElgTriangles should be ElgTriangleStrip.
Also removed unnecessary relax for GL_NV_geometry_shader_passthrough in link validate
=> Fix inferred output primitive for GL_NV_geometry_shader_passthrough 

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.memoryScopeSemantics.comp.out
This was found by updated spirv-tools validation running against Vulkan CTS.
=> Fix flags.nonprivate to be true for workgroup memory, which is implicitly workgroupcoherent/nonprivate

BUILD.gn
This had no sources and depended on a source_set which is an invalid use
of GN because the source_set gets propagated to dependents of the
static_library instead.
PTAL @johnkslang
=> BUILD.gn: remove the static_library target.

SPIRV/SpvPostProcess.cpp, SPIRV/SpvTools.cpp
This CL removes the current parameters which are unused in order to
fixup the issued clang warnings.
=> Fixup unused parameter warnings

SPIRV/SpvPostProcess.cpp
This would happen in SpvPostProcess when we don't enable AMD extensions.
PTAL @johnkslang
=> Fix MSVC warning C4065: 'default' but no 'case' labels

BUILD.gn
PTAL @johnkslang (FYI @dj2).
Glslang was never build in Chrome so some sanity check for GN files were never run causing this to go unnoticed. After this is landed we can build glslang in chrome in the "all" target (as a dependency of Dawn)
=> BUILD.gn: remove reference to non-existent header

CMakeLists.txt, glslang/CMakeLists.txt, gtests/CMakeLists.txt, hlsl/CMakeLists.txt, known_good.json
This pulls in the latest spirv-tools which has more PCH enabled. A clean Debug glslang build on Windows now takes about a minute on my system.
When I first tried to merge in spirv-tools yesterday, I found that the PCH macros conflicted, so I'm renaming all of them to be unique per-project. I've already renamed spirv-tools.
=> Rename PCH macro to glslang_pch (to avoid name collision) and update to latest spirv-tools

SPIRV/SpvTools.cpp
MergeReturn now requires this or could throw an error.
=> Add DeadBranchElim before MergeReturn in legalization.

SPIRV/GlslangToSpv.cpp
In the case where the if and else if are both false the spv::Id result will be used uninitialized in the builder.addName call. If this happens, return an error instead of attempting to use result.
=> Handle potentially uninitialized result

Test/baseResults/hlsl.type.type.conversion.all.frag.out, Test/baseResults/hlsl.type.type.conversion.valid.frag.out, Test/hlsl.type.type.conversion.all.frag, Test/hlsl.type.type.conversion.valid.frag, glslang/MachineIndependent/Intermediate.cpp, gtests/Hlsl.FromFile.cpp
This fixes some of the type conversion gaps of scalar, vector and matrix type of the HLSL frontend.
All cases of the tests where compiled with D3dcompiler_47.dll v 10.0.17.134.1 to verify which conversions are invalid and which are not (comments after each line contain the compile log of fxc).
=> Updated type conversion rules for HLSL frontend

Test/hlsl.structbuffer.frag, hlsl/hlslParseHelper.cpp
Implemented c register handling, the
c register is a offset into the global
const buffer, each slot is one 4 component
32 bit vector.
Adjusted a test not to use c register for
a structured buffer, they are supposed to
use t registers
Added comments with hints for what are the
register types are used for.
=> HLSL: implemented c register handling

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.int.dot.frag.out, Test/hlsl.int.dot.frag, gtests/Hlsl.FromFile.cpp
Fixes incorrect spir-v on int dot(int, int) by decomposing OpDot into corresponding multiplies and additions.
Fixes #1582
=> [HLSL/Spir-V] fix for incorrect spir-v on int dot(int, int)

Test/baseResults/hlsl.buffer.frag.out, known_good.json
Validator has more refined messages about what kind of block layout
rules have been applied.
=> Update to newer SPIRV-Tools, including VK_EXT_scalar_block_layout

Android.mk, ndk_test/Android.mk, ndk_test/jni/Application.mk, ndk_test/test.cpp
This CL adds Android.mk files to simplify NDK builds for downstream projects. The necessary
files are added so an NDK build can be done inside glslang to test it is functional.
=> Add NDK build files

glslang/OSDependent/Unix/CMakeLists.txt
Would typically be pthreads.
Without this, '-Wl,--no-undefined' would output these errors:
```
/usr/bin/ld: OSDependent/Unix/libOSDependent.a(ossource.cpp.o): in function `glslang::OS_CleanupThreadData()':
/home/akien/Mageia/Sandbox/_rpm/BUILD/glslang-7.10.2984/glslang/OSDependent/Unix/ossource.cpp:83: undefined reference to `__pthread_register_cancel'
/usr/bin/ld: /home/akien/Mageia/Sandbox/_rpm/BUILD/glslang-7.10.2984/glslang/OSDependent/Unix/ossource.cpp:93: undefined reference to `__pthread_unregister_cancel'
/usr/bin/ld: OSDependent/Unix/libOSDependent.a(ossource.cpp.o): in function `glslang::OS_AllocTLSIndex()':
/home/akien/Mageia/Sandbox/_rpm/BUILD/glslang-7.10.2984/glslang/OSDependent/Unix/ossource.cpp:122: undefined reference to `pthread_key_create'
/usr/bin/ld: …
```
=> CMake: Link OSDependent with Threads::Threads

glslang/OSDependent/Unix/CMakeLists.txt
As reported in #1624, Ubuntu 14.04 LTS still uses CMake 2.8.12 which
does not support the Threads::Threads target (added in CMake 3.1).
This could be reverted once the required CMake version is bumped to 3.1+.
Not tested against CMake < 3.1, could you try it @archimedus?
=> CMake: Fix linking pthread of CMake < 3.1

glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/localintermediate.h
The source strings may or may not have a null terminator. We need to
make sure we add one before outputting the source strings as we iterate
over the c-str looking for the null terminator.
=> Make sure source strings are terminated

glslang/OSDependent/Unix/CMakeLists.txt
CMake can't correctly configure the latest code because of an issue with cross-compilation of pthreads:
https://gitlab.kitware.com/cmake/cmake/issues/16920
=> Work around a CMake cross-compilation issue

Test/baseResults/spv.bufferhandle13.frag.out, glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp
Not all memory qualifiers necessarily need the vulkan memory model, e.g. volatile/restrict that correspond to core SPIR-V features do not.
=> More precisely check for the qualifiers that enable the vulkan memory model for buffer references.

hlsl/hlslParseHelper.cpp
I'm running glslang over a large commercial HLSL code base for the first time, to convert it to SPIR-V. Unfortunately I can't post the offending HLSL code, but I can try to make a minimum reproducible shader if that would help.
The changes in this commit were required to prevent glslValidator from crashing when trying to parse these shaders: https://github.com/hodgman/glslang/commit/7ee47fee095fbba6db62d00300eb64a026ec6120
The offending code is based around practices such as this:
`struct TextureSampler2D
{
Texture2D    tex;
SamplerState texSampler;
};
TextureSampler2D CreateTexSampler2D(Texture2D tex, SamplerState texSampler)
{
TextureSampler2D textureSampler;
textureSampler.tex = tex;
textureSampler.texSampler = texSampler;
return textureSampler;
}`
=> Fix crashes in HLSL parsing.

glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h, hlsl/hlslParseHelper.cpp
Glslang has infrastructure to declare what extensions a symbol needs (in Initialize.cpp) and then parsing automatically checks and issues errors when the declared extensions are not present.
However, this infrastructure did not cover members of blocks; e.g., gl_PointSize in an anonymous block or gl_out[] block, etc.
This PR adds that infrastructure, which has multiple uses that should make use of it, as many block members have been added without sufficient checks that the right extensions are declared.
=> Infrastructure: Generalize and broaden per-variable extension checking.

BUILD.gn
Also came up when using the BUILD.gn file with ANGLE.
ANGLE bug: 3088
=> Suppress a MSVC cast warning in GN.

CMakeLists.txt
For nested project builds, writing CMAKE_DEBUG_POSTFIX into the cache
ends up affecting other projects. Caching this value doesn't seem to be
required in practice, so this change removes the cache tag.
=> build: Do not cache debug library suffix

BUILD.gn
Usually this warning is disabled by default. But when turned on Clang
complains about extra semicolons in Glslang headers. Turn this off for
now. See http://crbug.com/926235
=> Disable Clang extra semicolon warning.

SPIRV/SpvPostProcess.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h
Clang warns if an interface specifies override for some overridden functions, but leaves it out for others that do override:
```
glslang/MachineIndependent/SymbolTable.h:348:26: error: 'clone'
overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
virtual TAnonMember* clone() const;
^
glslang/MachineIndependent/SymbolTable.h:88:22: note: overridden virtual
function is here
virtual TSymbol* clone() const = 0;
```
There are also a couple of cases of unsigned/signed integer comparisons that generate `-Wsign-compare`.
=> Fix a couple of warnings clang found

StandAlone/ResourceLimits.h
Adds consistent include behavior across all StandAlone header files.
=> Use relative include paths in StandAlone/ResourceLimits.h

StandAlone/StandAlone.cpp, Test/baseResults/reflection.linked.options.out, Test/baseResults/reflection.options.frag.out, Test/baseResults/reflection.options.geom.out, Test/baseResults/reflection.options.vert.out, Test/reflection.options.geom, Test/reflection.options.vert, Test/runtests, glslang/MachineIndependent/reflection.cpp, glslang/Public/ShaderLang.h
Follow-up to #1684, add an option to apply similar rules to uniform aggregate explosion to input/output block interfaces. The result is that a block interface between shader stages like:
```
in block
{
vec4 Color;
vec4 a;
vec2 b[3];
} In;
```
Will be reflected as `block.Color`, `block.a`, and `block.b[0]` separately, instead of just an opaque `In`. This is particularly relevant for built-ins inside `gl_PerVertex`.
Since block interfaces are different namespaces, we prepend `in` or `out` to the name used for internal lookups to generate unique names. The returned name to the user has no prefix still.
=> Add option to unwrap I/O block aggregates in reflection

Test/baseResults/hlsl.automap.frag.out, Test/baseResults/hlsl.reflection.binding.frag.out, Test/baseResults/hlsl.reflection.vert.out, Test/baseResults/hlsl.shift.per-set.frag.out, Test/baseResults/reflection.linked.out, Test/baseResults/reflection.options.vert.out, Test/baseResults/reflection.vert.out, Test/reflection.options.vert, Test/reflection.vert, glslang/MachineIndependent/reflection.cpp
Minor fix I found while fleshing out my own tests - plain array variables should not have their root array skipped, only blocks.
I've also adjusted the output so that the array size is passed through even when we're not exploding I/O variables.
=> Fix treatment of array input/output variables in reflection

glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpContext.h, glslang/MachineIndependent/preprocessor/PpTokens.cpp
This eliminates a source of fragility, and the proper space tracking is used to more correctly compare macro redefinitions WRT white-space differences.
It could also be the basis for fixing #1605.
=> PP: Remove sub-tokens in macro recording and record spaces correctly.

hlsl/hlslParseHelper.cpp
In decomposeIntrinsic a new TString was being allocated and passed into
a TVariable. That string was leaking. This CL converts the new TString
to call NewPoolTString to allocate from the TString pool.
=> Fixup leak of TString

glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp
Inside the grammar for function_identifier if the .function is null an
empty function name is allocated. This is allocated on the stack and
passed into TFunction as a pointer. TFunction just stores that pointer.
Later, when we access the name we will receive an invalid usage of a
stack allocated variable. This CL switches to using NewPoolTStringn for
the empty function name.
=> Allocate empty function name in the string pool.

Test/baseResults/reflection.options.vert.out, Test/baseResults/reflection.vert.out, Test/reflection.options.vert, Test/reflection.vert, glslang/MachineIndependent/reflection.cpp
I found this because I changed `isReflectionGranularity` to correctly count arrays-of-arrays as not yet fully reflected, however it can happen in specific other cases with arrays-of-structs (as I've added a test for).
In `blowUpActiveAggregate` when walking the list of dereferences in reflection to determine what active uniforms to reflect, the `terminalType` starts at the passed in `baseType` and then is updated with `visitNode->getType()` for each index. This means the dereference from the indirection is already accounted for. For direct indexes the type doesn't change, all that happens is the `offset` and `name` are adjusted to account for the index. For an indirect indexing into an array we go wide and recurse for the remaining dereferences over each possible index that could be.
The …
=> Fix type recursion with EOpIndexIndirect dereferences

SPIRV/GlslangToSpv.cpp
This fixes the build for #1712. I didn't want to add dozens of new ifdefs around all the cooperative matrix code, and it didn't really make sense to move the string to another file, so this seemed like the most straightforward fix (and is in the direction of eventually removing all these ifdefs).
=> Fix NV_EXTENSIONS-disabled build

SPIRV/GlslangToSpv.cpp, glslang/Include/Types.h
This is a better place for it logically, since it is not specific to
glsl->spirv translation. And in a future change I want to use it outside
of glslangtospv.
=> Move getBufferReferenceAlignment to be a method of TType

BUILD.gn
The target was accidentally listed as a source_set.
=> GN: Make glslang_validator an executable.

SPIRV/SpvTools.cpp
The spvtools::Optimizer::Run method glslang is using constructs a default set
of spvtools::OptimizerOptions. This default set of options instructs the
validator to run. That is not quite correct since glslang will invoke the
validator _explicitly_ after the optimization pass.
Change-Id: I30f458304c6e7f81e89fc4ebd25eabbbd8348063
=> Avoid running the validator as part of the optimization pass.

BUILD.gn, SPIRV/SpvPostProcess.cpp
One variable was only used in an 'assert' call. MSVC flagged this
as unused in Release. Suppress the warning and also add a static
cast to void so the variable becomes referenced.
=> Suppress MSVC warning about unused variable.

Test/310.tesc, Test/320.tesc, Test/baseResults/310.tesc.out, Test/baseResults/320.tesc.out, glslang/MachineIndependent/Initialize.cpp
Prior to this change, OES_primitive_bounding_box and EXT_primitive_bounding_box were both recognised as extensions, but only the name gl_BoundingBoxOES could be used. However the EXT version uses the name gl_BoundingBoxEXT instead. In addition, since GLES 3.2, the extension has been included in the core standard and the name gl_BoundingBox may be used instead. This change aims to make both extensions and the 3.2 core version all work.
All my real changes are in Initialize.cpp. The rest is just updating the test framework to cover uses of all three variable names.
One thing I'd appreciate reviewing is whether my change to replace
`symbolTable.setVariableExtensions("gl_BoundingBoxOES", Num_AEP_primitive_bounding_box, AEP_primitive_bounding_box);`
with …
=> Fix tessellation control shader bounding box support.

glslang/MachineIndependent/intermOut.cpp
Accessing a double through a long long pointer invokes undefined behaviour. GCC warns about this (warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]).
=> Avoid undefined behaviour

External/CMakeLists.txt
A project that uses googletest(GTEST) shouldn't include googletest
headers with its artifacts in its install target.  These headers
simply are not needed by the consumers of the install target and
can cause conflicts with other projects that use googletest
themselves and this project's install target.  And they are just not
part of the expected glslang build artifacts.
It is likely that the addition of the googletest headers to the install
target was a simple oversight that happens as a result of adding
googletest as a CMake subdirectory.
For more information on how this causes conflicts with other projects,
please see: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/821.
=> build: Don't ship GTEST headers in install target

SPIRV/SPVRemapper.h, glslang/Include/Common.h
Fixes compilation errors on some platforms.
=> Check if _MSC_VER is defined before using.

glslang/Include/Common.h
On some platforms some of the includers of this header don't have
'atoi' defined after the change in #1749
=> Add cstdlib include

StandAlone/StandAlone.cpp, glslang/Include/Types.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h, glslang/Public/ShaderLang.h
introduces EShMsgBuiltinSymbolTable and corresponding --dump-builtin-symbols command line to output the builtin symbols with all details. The intention is for tools that may want to use the data for auto-completion and tooltips or create the ability to provide overloaded functions.
TSymbol::dump functions have option to do "complete" print
bugfix in TType::getCompleteString, structure can be null for block
=> introduce ability to dump builtin symbol table

glslang/MachineIndependent/Intermediate.cpp
For certain int8/int16/float16 conversions,they are conditionally allowed when extensions defining explicit arithmetic types are enabled.
=> Fix issues of explicit conversions.

BUILD.gn
No behavior changes.  Please see [1] for why this is necessary.
[1] https://bugs.chromium.org/p/chromium/issues/detail?id=964411
=> Remove glslang.y from gn sources

glslang/MachineIndependent/Initialize.cpp
It was mistakenly placed outside !EesProfile guard.
Signed-off-by: Samuel Iglesias Gonsálvez <siglesias@igalia.com>
=> Fix gl_SubGroupSizeARB builtin treatment

BUILD.gn
In order to upgrade the version of glslang used by the
Fuchsia platform source tree, BUILD.gn needs to be
slightly modified to care about the case where it is
not used with the Chromium //build configuration:
- Remove a new compiler warning to ensure proper
compilation with -Werror (which is the default).
- Add a build target for spirv-remap, which is used
by Fuchsia at build time to optimize the precompiled
shaders of some of its graphics libraries.
=> BUILD.gn: Fix file for use with Fuchsia platform build.

StandAlone/spirv-remap.cpp
These macros result in a non-deterministic build.  In chromium, these
macros are specifically set to empty, resulting in a compile error.
Revealed by this change: 1f5799c155d30b90871c79d4ca92f8da4d3f3872
=> Remove __DATE__ and __TIME__ usage

SPIRV/SPVRemapper.h, SPIRV/spvIR.h, glslang/MachineIndependent/Intermediate.cpp
They cause a warning (-Wextra-semi) that can lead to a compile error
(-Werror).
=> Remove extraneous semicolons

CMakeLists.txt
=> Explicitly remove RTTI in the top-level build config

known_good.json
Update the known good SPIRV-Tools commit to eventually propagate the commit (https://github.com/KhronosGroup/SPIRV-Tools/commit/1fedf72e500b7cf72098a3f800c8ef4b9d9dc84f) allowing the ray tracing stages in pass instrumentation to the vulkan validation layers (validation layers depends on glslang which depends on spirv-tools).
=> Update known good SPIRV-Tools commit

known_good.json
Previous known-good contained regression per sperron at Google.
=> Update spirv-tools and spirv-headers known good.

CMakeLists.txt
MSVC uses a different flag for disabling RTTI, so is currently
including RTTI information and throwing warnings.
=> Convert no RTTI rule to be compiler specific

glslang/MachineIndependent/iomapper.h
This is needed for stricter/newer MSVC builds of downstream users.
=> Add in header for uint32_t definition

glslang/MachineIndependent/ParseHelper.cpp
ANGLE compiles with the flag -Wextra-tokens so this change broke the glslang roll into ANGLE.
=> Fix conformance with -Wextra-tokens

BUILD.gn
I believe this is required for the Chromium build.
(Rolling updated Glslang into Chromium is blocked until a fix like this goes in)
=> GN build (for Chromium): enable HLSL

BUILD.gn
The previous fix for this only enabled HLSL internally in glslang which
means that dependent using HLSL, for example shaderc, failed
compilation.
Also contains noop changes done by `gn format`
=> GN build (for Chromium): enable HLSL in dependents.

glslang/MachineIndependent/ParseHelper.cpp
In the current version of the code on non-debug builds these cases
will fallthrough, since assert is a no-op, and eventually make a call
passing in |op| which hasn't been initialized. clang is currently
throwing a warning about this behaviour when integrating downstream.
This patch changes the behaviour, so that in any branch that has an
assert now has a return nullptr, to indicate failure after it and
avoid the uninitialized variable usage.
=> Initialize variable to avoid uninitialized variable warnings in Clang

Test/430.comp, Test/baseResults/430.comp.out, glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/localintermediate.h
Purpose :
According to GLSL SPEC 4.6 ( 4.4.1.4 Compute Shader Inputs), for compute shader input qualifiers, we should declare such qualifiers with same values in the same shader (local_size_x, y and z).
"If such a layout qualifier is declared more than once in the same shader, all those declarations must set the same set of local work-group sizes and set them to the same values; otherwise a compile-time error results."
Why this fix:
If we manually set "local_size_x = 1" and directly following a declaration like "local_size_x = 2", this would not be detected. That is because currently we treat all the '1' as default value and could not restrictly detect whether those are default values.
Test case:
......
layout(local_size_x=1) in;
layout(local_size_x=2) in;
......
=> Add flags for local size values ( compute shader )

BUILD.gn
The Fuchsia build is very picky about newlines at the end of files
and will complain loudly about them. Removing the -Wnewline-eof
warning solves the issue.
=> Fix Fuchsia build.

Test/baseResults/nonuniform.frag.out, Test/nonuniform.frag, glslang/MachineIndependent/ParseHelper.cpp
This makes the type correct from the beginning, which should be more robust.
=> GLSL/SPV: Fix #1900: Drop const on literal when doing an object copy.

glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/reflection.cpp, glslang/MachineIndependent/reflection.h, glslang/Public/ShaderLang.h
[**PURPOSE**]:
The current process design for Uniform / Block / Pipe IO symbols reflection (during program linking) is as following :
1.1 using a global mapper called 'TNameToIndex' to store all the relationship of name (of symbols) to their indexes (in their own MapIndexToReflection vectors).
1.2 TNameToIndex mapper will be used during program linking and helps to check and merge duplicate symbols within each stage ( Uniform, Block and Pipe IO)
1.3 Different types of symbols will have their own index mapping storage. All those symbols will share TNameToIndex as a general searching mapper.
1.4 Only IN in first stage and OUT in last stage will be dealed within traversing functions.
Now, here we meet those problems:
2.1 In and Out variables for pipelines are mapping to different …
=> Reflection will crash when the VS input symbol defines the same name with FS output symbol

glslang/Include/Types.h, glslang/Include/intermediate.h, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/localintermediate.h, glslang/Public/ShaderLang.h
glslang/include/intermediate.h -> Add a new interface to set TIntermBranch's expression.
glslang/include/Types.h -> Add interface to set Type's basicType and add interface to get basicType form a TSampler.
glslang/MachineIndependent/intermediate.cpp -> Part of the code in createConversion been encapsulating as a new function called buildConvertOp
glslang/MachineIndependent/localintermediate.h -> Export createConversion and
buildConvertOp as a public function, and add a new param to control whether force update xbfBufferStride.
glslang/Public/ShaderLang.h -> Add interface to get shader object and shader source.
This change are use for shader dump and Patch AST, we want do some patch on AST when after parser and before SPVGen, add more interface and export some interface to public, can make …
=> Adjusting code interface

Test/130.frag, Test/330.frag, Test/baseResults/130.frag.out, Test/baseResults/330.frag.out, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
This enables usage of explicit location on uniforms without the requirement of GLSL 430 version
Also added tests
=> Add support for GL_ARB_explicit_uniform_location

CMakeLists.txt
find Python and add External subdir only if BUILD_EXTERNAL option was set set (on by default) and /External dir exists
=> find Python and add External subdir only if BUILD_EXTERNAL option was set

CMakeLists.txt
I added an option to make pch enabled in Cmake.
Because PCH causes compile errors when glslang is compiled as a submodule or ExternalProject_Add in cmake
=> Added an option to make pch enabled in Cmake

CMakeLists.txt
This is useful for example when using VisualStudio Code as IDE.
=> [cmake] Enable generation of compile_commands.json

BUILD.gn
The Fuchsia platform build and the Chromium one use a completely
different set of configs to specify default warnings. The previous
version of BUILD.gn worked with Chromium, but failed to build
with Fuchsia.
This CL fixes the issue by identifying said configs and reusing
them consistently.
Change-Id: I7de526a57d2f14eb93c03e06401d2c3059d35e9a
=> BUILD.gn: Fix fuchsia build

CMakeLists.txt
Added CMake option ENABLE_CTEST to skip testing.
Set to ON by default to retain original behavior.
=> Add option ENABLE_CTEST to skip testing

glslang/MachineIndependent/reflection.cpp
Fixed warning: `size_t` to `int` implicit cast.
=> Fix warning: size_t->int implicit cast

BUILD.gn
Detected with ANGLE's export_targets script.
=> Add a couple missing headers to the GN build.

SPIRV/spvIR.h
This is causing the following error:
moving a temporary object prevents copy elision
[-Werror,-Wpessimizing-move]
=> Remove std::move that is breaking chromium roll

README.md
This Cl updates the README.md to reference the deprecation date for the
current SPIRV/ install location.
Issue #1964
=> Add deprecation for SPIRV/ install folder location.

glslang/OSDependent/Web/glslang.pre.js
`['data']`/`['free']` prevents the closure compiler from minifying these variable names, which are part of the public API. (my own bug)
=> Fix compileGLSLZeroCopy accidental minification

SPIRV/SpvBuilder.h, SPIRV/SpvPostProcess.cpp
The SPIR-V post-processing to discover capabilities and
extensions does not apply to WebGPU compilation.  So don't include
that code.
This reclaims some of the code space added by #1943
=> SPIR-V postprocessing: WEB case only needs CFG mods

SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, gtests/CMakeLists.txt
There is a flag to disable the SPVRemapper during the GLSLang build.
That flag is check in some, but not all spots so if you try to build
with SPVRemapper disabled you get CMake errors and compile errors.
This CL fixs up the build so building with -DENABLE_SPVREMAPPER=0 will
complete correclty.
=> Check for ENABLE_SPVREMAPPER flag in CMakeList files.

SPIRV/GlslangToSpv.cpp, SPIRV/doc.cpp, Test/baseResults/spv.specConstant.vert.out, glslang/Include/intermediate.h, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h, glslang/MachineIndependent/intermOut.cpp
The SPIR-V extension landed quite some time ago.  The GLSL extension is at https://github.com/KhronosGroup/OpenGL-Registry/pull/331.  This has been tested with the implementation of the VK extension in Intel's open-source Vulkan driver using the tests at https://gitlab.freedesktop.org/mesa/crucible/merge_requests/59.
=> Implement INTEL_shader_integer_functions2

glslang/Include/PoolAlloc.h
TPoolAllocator is not copy assignable, so this setter could never have
been used. After a recent change (878a24ee2), new versions of Clang
reject this code. Make it compile by removing the method.
=> Remove glslang::pool_allocator::setAllocator

glslang/MachineIndependent/Scan.cpp
Keywords should only have tests like "extension-on || version >= ...", or
"extension-off && version <= ...".
=> Fix: #2014: Don't do "extension-on && version >= ..." keyword checks.

glslang/Include/Types.h, glslang/MachineIndependent/SymbolTable.cpp
Non-HLSL code was using an uninitialized HLSL member.
This commit consistently does not use those HLSL members unless ENABLE_HLSL is on.
=> Fix #2020: PR #1977 broke HLSL member consistency, this fixes it.

Test/130.frag, Test/baseResults/130.frag.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
Version : >= 130
Purpose:
Allow users to use features by enabling this extension, even in low versions. Related features have been already supported by SPIR-V and GLSL, just add extensions for users who want to enable this extension in low versions.
Extension Name: 
ARB_sample_shading
Builtin-variables:
"gl_SampleID"
"gl_SamplePosition"
"gl_SampleMask"
"gl_NumSamples"
Reference:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_sample_shading.txt
=> Add support for ARB_sample_shading

Test/atomic_uint.frag, Test/baseResults/atomic_uint.frag.out, glslang/MachineIndependent/ParseHelper.cpp
atomic counter offset should align to 4
Ref:
glspec46.core - 6.8 BufferObjectState
offset restriction multiple of 4
=> atomic counter offset should align to 4 (compute shader)

Test/140.frag, Test/baseResults/140.frag.out, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
GLSL Version : >= 140
Purpose:
Allow users to use features by enabling this extension, even in low versions. Related features have been already supported by SPIR-V and GLSL, just add extensions for users who want to enable this extension in low versions.
Extension Name:
ARB_texture_multisample
Builtin-variables:
Nah
Builtin-functions:
Nah
Keywords:
sampler2DMS, isampler2DMS, usampler2DMS,
sampler2DMSArray, isampler2DMSArray, usampler2DMSArray
Reference:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_multisample.txt
=> Add support for ARB_texture_multisample

Test/120.vert, Test/baseResults/120.vert.out, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
GLSL Version : >= 120
Purpose:
Allow users to use features by enabling this extension, even in low versions. Related features have been already supported by SPIR-V and GLSL, just add extensions for users who want to enable this extension in low versions.
Extension Name:
ARB_uniform_buffer_object
Builtin-variables:
Uniform
Builtin-functions:
Nah
Keywords:
Nah
Features:
uniform block
Reference:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_uniform_buffer_object.txt
=> Add support for ARB_uniform_buffer_object

Test/410.vert, Test/baseResults/410.vert.out, glslang/MachineIndependent/Initialize.cpp
Add builtin constants:
gl_MaxFragmentUniformVectors and gl_MaxVertexUniformVectors.
They should both be available since version 410 for core.
=> Add builtin constants gl_MaxFragmentUniformVectors and gl_MaxVertexUniformVectors.

Test/450.comp, Test/baseResults/450.comp.out, glslang/MachineIndependent/ParseHelper.cpp
Wrong logic entry,
when declare atomic_uint binding without offset declaration, glslang won't check max atomic uint binding.
=> Modify max binding checks for atomic_uint

glslang/MachineIndependent/Versions.cpp
This micro should been defined 1, if opengl 2.0 is required.
See extension spec https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_blend_equation_advanced.txt
=> Add missing extension defination

StandAlone/StandAlone.cpp, Test/runtests
This still isn't a complete solution.  See #1829.
This is now updated to log processes using --define-macro and --undef-macro.
=> Fix #1829: Allow "--" options for def/undef, for OpModuleProcessed.

Test/150.frag, Test/baseResults/150.frag.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h, glslang/MachineIndependent/glslang.m4, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/parseVersions.h
GLSL Version : >= 150
Purpose:
Allow users to use features by enabling this extension, even in low versions.
Extension Name:
ARB_gpu_shader_fp64
Builtin-variables:
Nah
Builtin-functions:
functions overloaded for this extension, please check registry in reference.
Keywords:
Double
Features:
add support for type "double", also related functions/builtin functions
overloaded for DOUBLE. "double vector" input should be in
ARB_vertex_attrib_64bit
Reference:
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gpu_shader_fp64.txt
=> Add support for ARB_gpu_shader_fp64

SPIRV/GlslangToSpv.cpp
Root cause:
GlslangToSpv use symbol structure's ptr as a map key, but multiple shader object can build a new AST.
In the AST the the same symbol has different ptr point to their structure, so indext map faild.
solution:
Add a new map glslangTypeToIdMap to map ptr to symbol id, and use symbol id to index memberRemapper.
=> Fix glslang can't link multiple AST in a single stage

glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h
GLSL could detect contradictory uniform binding, but missing error reporting, even if we could now observe error message inside infosink.
Add error check when first time validate uniform binding. 
This error check flag will be used during linking time. To quickly report errors like contradictory uniform bindings.
=> Add Error check flag in io mapper

CMakeLists.txt, SPIRV/SpvBuilder.h, glslang/Include/ConstantUnion.h, glslang/MachineIndependent/iomapper.cpp
Changes to make compiler happier regarding `Werror=deprecated-copy` / rule of three related issues.
Fix proposal for #1939
=> Fix for GCC 9 / Werror=deprecated-copy

glslang/MachineIndependent/ShaderLang.cpp
Two similarly named enums led to the wrong one being used here, this
is getting caught in the Chromium and Dawn DEPS rolls.
=> Use correct enum type in case statement

CMakeLists.txt
#1940 added a use of VERSION_GREATER_EQUAL, which requires cmake 3.7. This breaks CTS when I try to update the glslang commit hash. Workaround this by using NOT ... VERSION_LESS, which is supported at least back to cmake 3.0.
=> Use NOT ... VERSION_LESS instead of VERSION_GREATER_EQUAL

glslang/MachineIndependent/iomapper.h
Fix for #2074.
Fixes memory corruption - `EShLangCount` is the correct array length:
```
TVarLiveMap *inVarMaps[EShLangCount], *outVarMaps[EShLangCount],
*uniformVarMap[EShLangCount];
TIntermediate* intermediates[EShLangCount];
```
=> Fix memory corruption in TGlslIoMapper

glslang/CInterface/glslang_c_interface.cpp
This fixes a -Wenum-compare and  "switch doesn't handle case" warnings in GCC9.
=> Avoid enum-compare warning, missing cases in switch

CMakeLists.txt, README.md, glslang/CMakeLists.txt, glslang/OSDependent/Web/CMakeLists.txt, glslang/OSDependent/Web/glslang.js.cpp
This should enable glslang to be used as a dependency of other projects
that target WebAssembly, instead of assuming "EMSCRIPTEN" => "Want
glslang.js".
Should fix #2072.
=> CMake: Split "is emscripten" config from "enable glslang.js"

glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h
Make the C interface consume a user defined `TBuiltInResource`.
Fix for #2075 
Update for PR #2038 
```C++
const glslang_input_t input =
{
.language = GLSLANG_SOURCE_GLSL,
.stage = GLSLANG_STAGE_VERTEX,
.client = GLSLANG_CLIENT_VULKAN,
.client_version = GLSLANG_TARGET_VULKAN_1_1,
.target_language = GLSLANG_TARGET_SPV,
.target_language_version = GLSLANG_TARGET_SPV_1_3,
.code = shaderCodeVertex,
.default_version = 100,
.default_profile = GLSLANG_NO_PROFILE,
.force_default_version_and_profile = false,
.forward_compatible = false,
.messages = GLSLANG_MSG_DEFAULT_BIT,
.resource = &glslang::DefaultTBuiltInResource,
};
glslang_initialize_process();
glslang_shader_t* shader = glslang_shader_create(&input);
...
```
=> Fix for #2075: removed DefaultTBuiltInResource from glslang_c_interface.cpp

glslang/OSDependent/Web/CMakeLists.txt
My bad :)
Tested locally in a build for https://github.com/kainino0x/-webgpu-glslang.
=> Fix typo in Web CMakeLists

glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp
When we use unsized array in shader storage buffer, glslang calculate the offset during delcaring the block, it may lead to incorrect block offsets when its implicit array size changed.
So here is what we do:
1. For GLSL, we add flag explicitOffset in TQualifier, and set it when layout offset is specified explicitly
2. By using this flag we could tell difference as whether it is an explicit offset, and recalculate the block member offset conditionally in OpenGL.
=> Add flag to check whether offset is implicit or explicit

Test/baseResults/spv.atomicCounter.comp.out, Test/spv.atomicCounter.comp, glslang/MachineIndependent/Initialize.cpp, gtests/Spv.FromFile.cpp
I got a bug report that this builtin function generates this validation error in Vulkan:
```
[ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | SPIR-V module not valid: MemoryBarrier: expected Memory Semantics to include a Vulkan-supported storage class
OpMemoryBarrier %uint_1 %uint_1032  
```
I think it was just an oversight that we didn't remove this along with the atomic_uint types. This is arguably either invalid code or a nop, and I think it's best to just forbid it.
See https://github.com/KhronosGroup/GLSL/pull/112 for the corresponding spec change.
=> Forbid memoryBarrierAtomicCounter for Vulkan compiles

glslang/MachineIndependent/parseConst.cpp
On Windows the single quote used in a comment was showing up as some
special character that the Microsoft compiler didn't like.
Bug #2140
=> Fix MSVC build issue - remove invalid character

glslang/MachineIndependent/Initialize.cpp
The indentation implies this was the intention. Noticed the issue while trying to compile our code with -Werror -Wall
=> Add missing braces to if condition

glslang/MachineIndependent/Initialize.cpp
This CL removes two unused variables from the initialization code.
=> Remove unused variables.

glslang/MachineIndependent/localintermediate.h
This is causing downstream users compiler errors if they have Werror or other
particularly restrictive flags turned on.
=> Remove extra semicolons

Test/420.frag, Test/baseResults/420.frag.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
Based on #2183 which should be merged first. And then the file 150.frag.out needs to be updated, before merging the change.
=> Add support for extension GL_ARB_shader_image_size

glslang/MachineIndependent/iomapper.cpp
Xcode was giving a warning about possible comma operator misuse.
=> xcode warnings fix

glslang/MachineIndependent/preprocessor/PpContext.h
Currently glslang fails to compile on clang with the following error:
```
FAILED: hecl/extern/boo/glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/preprocessor/Pp.cpp.o 
/usr/bin/clang++  -DENABLE_OPT=0 -DFMT_EXCEPTIONS=0 -Ihecl -I../hecl/extern/boo/glslang/glslang/.. -g -fPIC   -msse2 -fno-plt -fno-rtti -fno-exceptions -Wall -Wno-multichar -Werror=implicit-fallthrough -Wno-unknown-warning-option -Wno-lto-type-mismatch -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-sign-compare -Wno-unknown-pragmas -Werror -fno-limit-debug-info -Wno-implicit-fallthrough -Wno-strict-aliasing -pthread -std=gnu++2a -MD -MT hecl/extern/boo/glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/preprocessor/Pp.cpp.o -MF …
```
=> TPpToken: Fix compiling on clang-10

Test/420.frag, Test/baseResults/420.frag.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h
Enable below features for GL Core version 420:
* layout qualifier "std430"
* storage qualifier "buffer"
* atomic memory functions
=> Add support for extension GL_ARB_shader_storage_buffer_object.

glslang/MachineIndependent/Versions.h, glslang/Public/ShaderLang.h
This allows casting from and to any unsigned value, previously this was
undefined behavior.
This fixes ubsan complaining in `TParseContext::layoutQualifierCheck`,
where `~EShLangComputeMask` is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/khronosgroup/glslang/2210)
=> Explicitly mark EShLanguageMask as unsigned

glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h
Encapsulate repeated code into functions to reduce code length.
Use a more reliable way to obtain the access name.
=> Code refine.

glslang/MachineIndependent/localintermediate.h
=> Reorder member init to match decl order

SPIRV/GlslangToSpv.cpp, Test/spv.ext.RayGenShader.rgen
Fixes #2247 
I will file a separate bug for enforcing 'binding' qualifier on this type
=> Add default descriptorset decoration for acceleration structure variables.

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.function.frag.out, hlsl/hlslGrammar.cpp, hlsl/hlslParseHelper.cpp
Fixes #2253, which is a rather pressing issue for us.  Feel free to discard this or suggest alternatives if you don't like this approach.
The change in a nutshell: when encountering uniforms in the entry point function parameters, instead of erroneously creating a global input variable for them, it now adds them to the $Global uniform block, from which they are accessed and loaded into the temporary variables in the wrapper function.  Opaque types, like textures, still get added as a global uniform variable of course.
Also contains a fix for use of "uniform in" which is supported in function arguments by FXC and handled as a regular uniform.
=> HLSL: fix handling of uniform qualifier in entry point parameters

Test/baseResults/hlsl.inoutquals.negative.frag.out, Test/hlsl.inoutquals.negative.frag, gtests/Hlsl.FromFile.cpp, hlsl/hlslGrammar.cpp
=> HLSL: Add better diagnostic when using in/out qualifiers in global scope

Test/hlsl.sample.dx9.frag, hlsl/hlslParseables.cpp, hlsl/hlslScanContext.cpp
The type is named samplerCUBE in HLSL.  I have verified that FXC does not accept samplerCube.
=> HLSL: Fix incorrect case in name of DX9 cube sampler type

hlsl/hlslParseables.cpp
This should fix being unable to roll newer versions of glslang into chromium and related projects.
=> Remove unused function, BaseTypeName

hlsl/hlslParseables.cpp
The `isMat` variable is no longer used in the HLSL parser. Removed.
=> Remove unused variable.

SPIRV/CInterface/spirv_c_interface.cpp, SPIRV/CMakeLists.txt, glslang/CInterface/glslang_c_interface.cpp, glslang/CMakeLists.txt, hlsl/CMakeLists.txt, hlsl/stub.cpp
Fixes the building of shared libraries.
This PR holds two changes:
1. Split the SPIR-V C interface to own file.
This breaks a cyclic dependency between the `SPIRV` and `glslang` build targets.
2. Fold the `HLSL` source into the `glslang` target
This breaks the cyclic dependency between the `glslang` and `hlsl` targets (by essentially removing the `hlsl` target).
The `BUILD.gn` and `BUILD.bazel` build rules already pull the `HLSL` source into the `glslang` target.
`Android.mk` is now the only remaining build config that has a (real) dedicated `HLSL` target, but this is explicity static and does not suffer the same link-time issues with the cyclic dependency. We may wish to stub this `HLSL` target too at a later date.
Related issue: #1484, #2147
Related PR: #2267
=> Untangle build target cyclic dependencies (approach #2)

kokoro/android-ndk-build/build-docker.sh, kokoro/android-ndk-build/build.sh, kokoro/android-ndk-build/continuous.cfg, kokoro/android-ndk-build/presubmit.cfg, kokoro/linux-clang-cmake/build-docker.sh, kokoro/linux-clang-cmake/build.sh, kokoro/linux-clang-cmake/continuous.cfg, kokoro/linux-clang-cmake/presubmit.cfg, kokoro/linux-gcc-cmake/build-docker.sh, kokoro/linux-gcc-cmake/build.sh, kokoro/linux-gcc-cmake/continuous.cfg, kokoro/linux-gcc-cmake/presubmit.cfg, ndk_test/jni/Application.mk
Add three new kokoro configurations that can be used to test the CMake and `Android.mk` build rules.
Both `CI-ubuntu-clang-cmake` and `CI-ubuntu-gcc-cmake` take around 2 minutes to complete.
`CI-android-ndk-build` uses the `ndk_test` build script which does not define `APP_ABI`, so builds a [bunch of ABIs by default](https://developer.android.com/ndk/guides/application_mk), and takes around 6 minutes. If we want to shorten this, we can reduce the number of ABIs built by defining the `APP_ABI` parameter in the `Application.mk` file (assuming nothing external is depending on this).
Note: landing this PR does not automatically enable these new presubmit tests - we also need to enable another google-private config (cl/317307422) around the same time that this PR lands.
=> Add more Kokoro configurations

SPIRV/GlslangToSpv.cpp, SPIRV/SpvTools.cpp, SPIRV/SpvTools.h, StandAlone/StandAlone.cpp
Analogous to gcc, -g0 would strip all debug info.  This is done
regardless of whether optimizations are enabled.
Fixes: #2276
=> Add -g0 command line argument

CMakeLists.txt
By default cmake generates cxx_flags with `/GR` parameter.
I updated CMAKE_CXX_FLAGS string and replaced `/GR` -> `/GR-`
How to reproduce:
Visual Studio 2019 x64 command port
mkdir build-msvc2019
cd build-msvc2019
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=install ..
nmake
COMPILATION BEFORE:
Scanning dependencies of target OSDependent
[  1%] Building CXX object glslang/OSDependent/Windows/CMakeFiles/OSDependent.dir/ossource.cpp.obj
cl : Command line warning D9025 : overriding '/GR' with '/GR-'
ossource.cpp
[  3%] Linking CXX static library OSDependent.lib
[  3%] Built target OSDependent
Scanning dependencies of target OGLCompiler
[  4%] Building CXX object OGLCompilersDLL/CMakeFiles/OGLCompiler.dir/InitializeDll.cpp.obj
cl : Command line warning D9025 : …
=> Fixed msvc 2019 nmake compiler warnings with RTTI.

kokoro/linux-clang-cmake/build-docker.sh, kokoro/linux-clang-cmake/build.sh, kokoro/linux-clang-cmake/shared/continuous.cfg, kokoro/linux-clang-cmake/shared/presubmit.cfg, kokoro/linux-clang-cmake/static/continuous.cfg, kokoro/linux-clang-cmake/static/presubmit.cfg, kokoro/linux-gcc-cmake/build.sh, kokoro/linux-gcc-cmake/shared/continuous.cfg, kokoro/linux-gcc-cmake/shared/presubmit.cfg, kokoro/linux-gcc-cmake/static/continuous.cfg, kokoro/linux-gcc-cmake/static/presubmit.cfg
Allows for testing of generation of both static libraries and shared objects.
The old configs are staying in place until I'm confident everything is working correctly.
Issues: #1421, #1484, #2283
=> Kokoro: Split linux cmake cfgs into static/shared

glslang/HLSL/hlslParseables.cpp
Warnings before fix:
[3/7] Building CXX object glslang/CMakeFiles/glslang.dir/HLSL/hlslParseables.cpp.o
../glslang/HLSL/hlslParseables.cpp: In function ‘bool {anonymous}::IsValid(const char*, char, char, char, char, int, int)’:
../glslang/HLSL/hlslParseables.cpp:334:45: warning: unused parameter ‘retOrder’ [-Wunused-parameter]
334 | inline bool IsValid(const char* cname, char retOrder, char retType, char argOrder, char argType, int dim0, int dim1)
|                                        ~~~~~^~~~~~~~
../glslang/HLSL/hlslParseables.cpp:334:60: warning: unused parameter ‘retType’ [-Wunused-parameter]
334 | inline bool IsValid(const char* cname, char retOrder, char retType, char argOrder, char argType, int dim0, int dim1)
|                                                       ~~~~~^~~~~~~ …
=> Fixed GCC -Wunused-parameter in hlslParseables.cpp.

CMakeLists.txt
Without this embedding static libraries into shared libraries may result in link time errors.
Issue: #2283
=> CMake: Compile with -fPIC when building SOs

SPIRV/CMakeLists.txt, glslang/CMakeLists.txt
Add `GenericCodeGen` and `MachineIndependent` static library targets.
Privately import both of these into the `glslang` target.
Privately import `MachineIndependent` into the  `SPIRV` target.
This is done to break the dependency of `libglslang.so` non-public APIs from `libspirv.so`,
which will become problematic once `glslang` hides its non-public symbols.
| File                      | Before     |     After  |
|---------------------------|-----------:|-----------:|
| `libGenericCodeGen.a`     |  -         |   `527716` |
| `libglslang.a`            | `68175944` |   `512938` |
| `libHLSL.a`               |     `1428` |     `1428` |
| `libMachineIndependent.a` |  -         | `67132202` |
| `libOGLCompiler.a`        |    `75908` |    `75908` |
| `libOSDependent.a`        |    `23768` | …
=> CMake: break up glslang into smaller static libs

LICENSE.txt
Ideally we'd unify the licenses in use by changing the licenses in the file headers to BSD-3-clause.
Until then, let's correctly list all the licenses currently in use.
Issue: #2305
=> Add additional licenses in use to LICENSE.txt

CMakeLists.txt, StandAlone/StandAlone.cpp, glslang/CMakeLists.txt, glslang/Public/ShaderLang.h
Default to `-fvisibility=hidden`, and annotate the public glslang interface with `GLSLANG_EXPORT` to change the visibility of these cherry-picked symbols to default.
This is also used by Windows builds for `__declspec(dllexport)`-ing the public DLL interface.
This allows us to classify API changes into those that are publicly backwards compatible, and those that are not.
Note that `libSPIRV` will likely need similar treatment.
Issues: #2283, #1484
=> glslang: Only export public interface for SOs

CMakeLists.txt, glslang/Public/ShaderLang.h
It was incorrectly always being set, causing linker warnings for MSVC builds.
Also simplify the preprocessor nesting in `glslang\Public\ShaderLang.h`
=> Fix GLSLANG_IS_SHARED_LIBRARY define

Android.mk, BUILD.bazel, CMakeLists.txt, ChooseMSVCCRT.cmake, External/CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Web/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, glslang/updateGrammar, gtests/CMakeLists.txt, hlsl/CMakeLists.txt, kokoro/license-check/build-docker.sh, kokoro/license-check/build.sh, kokoro/license-check/continuous.cfg, kokoro/license-check/presubmit.cfg, license-checker.cfg, ndk_test/Android.mk, ndk_test/jni/Application.mk
The `license-checker` is a tool that verifies each file has contains a permitted license header.
See https://github.com/ben-clayton/license-checker for more information.
Issue: #2305
=> Add license checking continuous and presubmit tests

Android.mk, BUILD.bazel, CMakeLists.txt, ChooseMSVCCRT.cmake, External/CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Web/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, glslang/updateGrammar, gtests/CMakeLists.txt, hlsl/CMakeLists.txt, ndk_test/Android.mk, ndk_test/jni/Application.mk
This was a copy-paste screwup, where the first line of the copyright had the company name was updated, but the company name mid way though was not.
=> License headers: s/Google/The Khronos Group

kokoro/license-check/continuous.cfg, kokoro/license-check/presubmit.cfg
Fix stupid typo in https://github.com/KhronosGroup/glslang/pull/2310
=> Kokoro: Correct the `build_file' path to build.sh

CMakeLists.txt
=> Don't use add_link_options() on old CMake versions

CMakeLists.txt
Enables `-fPIC` compiler flag even when building statically.
This is helpful for statically linking a `glslang` target into a shared library.
Simplifies the workarounds seen in google/shaderc#1093 to a `set(GLSLANG_BUILD_PIC 1)`.
=> Add GLSLANG_BUILD_PIC CMake flag

BUILD.gn
To reduce the binary size of ANGLE, a gn override is added
(glslang_angle) which:
- Controls whether ENABLE_OPT=1 is set
- Customizes the build for the Vulkan backend of ANGLE.  As a first
step, this removes HLSL functionality which together with no
optimization shave ~2.5MB off of ANGLE's binary size.
Upcoming changes will add a macro for GLSLANG_ANGLE similar to
GLSLANG_WEB that will strip features from glslang to support only what
ANGLE needs.
Signed-off-by: Shahbaz Youssefi <ShabbyX@gmail.com>
=> gn: Optionally disable optimizations and HLSL

StandAlone/StandAlone.cpp
Being quiet should have been the default, but I guess it's too late
now to change it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/khronosgroup/glslang/2314)
=> Add --quiet option.

BUILD.gn
Dawn tests use shaderc, which assumes glslang has HLSL support.  This
change makes HLSL support also follow template arguments, and changes
the target names such that glslang_sources will remain the "has all
features" target and the new glslang_lib_sources would be what ANGLE
would use.
=> gn: Fix dawn tests in Chromium

.gitignore
`.vscode/` ignores Visual Studio Code user config files.
`bazel-*` ignores bazel build system symlinks.
`out/` ignores the default output directory for Visual Studio generated files.
=> Add new rules to .gitignore

CMakeLists.txt, glslang/CMakeLists.txt
On closer inspection, it appears that nearly all the targets use the `POSITION_INDEPENDENT_CODE` target option anyway.
Simplify all this away by always being PIC.
=> Remove GLSLANG_BUILD_PIC flag

glslang/CMakeLists.txt
`GenericCodeGen` and `MachineIndependent` were missing from the generated visual studio solutions. Add these.
=> Add new static targets to VS solution folders

BUILD.gn
Set the value to false if the environment doesn't declare this variable.
This fixes downstream integration issues for environments that at not aware of/use angle.
=> Make sure glslang_angle has a definition in BUILD.gn

BUILD.gn
It would seem that `glslang_sources` has a private dependency on `glslang_build_info`, so `glslang_validator` cannot transitively `#include` the generated `glslang/build_info.h` header.
Add `glslang_build_info` as a direct dependency to `glslang_validator`.
Also remove the duplicate dependency on `glslang_build_info` in `glslang_sources_common`
Note: This is a speculative fix as I can build Chromium fine without these changes.
Not sure what's different between these build environments.
=> Attempt to fix chromium builds

CMakeLists.txt
`${CMAKE_SOURCE_DIR}` points to the outer project root, not the current directory.
Fixes building of `glslang` when included into another CMake project.
=> Fix CMake rules when nesting CMake projects

glslang/Include/Common.h
currently, due to
```c++
#if (defined(_MSC_VER) && _MSC_VER < 1900 /*vs2015*/) || defined MINGW_HAS_SECURE_API
#include <basetsd.h>
#ifndef snprintf
#define snprintf sprintf_s
#endif
#define safe_vsprintf(buf,max,format,args) vsnprintf_s((buf), (max), (max), (format), (args))
```
defining `snprintf` to `sprintf_s` essentially unconditionally, this will break the
stdio.h+cstdio system header for mingw-w64 g++ in msys2 with shaderc
https://github.com/google/shaderc/issues/1065
an alternative change would be
https://raw.githubusercontent.com/shinchiro/mpv-winbuild-cmake/master/packages/glslang-0001-fix-gcc-10.1-error.patch
in which the `|| defined MINGW_HAS_SECURE_API` part is removed
possibly related https://github.com/KhronosGroup/glslang/issues/2232
=> Common: include standard headers before doing any defines

license-checker.cfg
Fixes license checker presubmit.
=> Add missing comma from license-checker.cfg

CMakeLists.txt
And declare project `LANGUAGES` - should fix the following warning:
```
CMake Warning (dev) at /bin/cmake-3.17.2/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):
Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
target architecture is known.  Please enable at least one language before
including GNUInstallDirs.
```
Also remove `NOTICE` from message() about PCHs - it seems to print this in the actual message, contrary to the documentation where it is used as a severity.
=> CMake: Move project() to top of CMakeLists.txt

Test/runtests
`glslangValidator` will only return [the codes 0..6](https://github.com/KhronosGroup/glslang/blob/b481744aea1ecf52ee4591afaa0f5e270b9d1636/StandAlone/StandAlone.cpp#L117-L125). Fail the test if anything else is returned (like due to the exe crashing).
Also set `LD_LIBRARY_PATH` to contain the `lib` directory before calling glslang.
=> runtests: Check error codes, set LD_LIBRARY_PATH

license-checker.cfg
`license-checker` will be updated to support `**` based wildcards. As part of this, `license-checker` will now traverse into subdirectories that would previously be excluded when the parent directory is excluded.
This change adds new rules that work with both the old version and new, to ease migration.
=> Add new rules for update of license-checker

license-checker.cfg
`license-checker` has been updated to support `**` wildcards simplifying the rules, and multiple license configs.
Add a new config for the bison generated files to ensure their licenses don't change.
=> Update license-checker.cfg with simplified rules

glslang/MachineIndependent/LiveTraverser.h, glslang/MachineIndependent/iomapper.cpp
when traversing the AST to find live UBOs etc, also traverse
module-level variable assignment, not just function calls.
Otherwise for cases such as this at the module level:
`float f = SomeUniform;`
SomeUniform won't be determined to be 'live'.
Is checking for EOpSequence the correct OpType here, or is there something more appropriate?
=> also search global sequences for live variables

CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, glslang/CMakeLists.txt
Also remove `SPIRV/doc.cpp` from the `SPVRemapper` target as this is part of `SPIRV`, causing ODR violations. Instead have
`SPVRemapper` link against `SPIRV`.
Fixes: #2346
=> Limit visibility of symbols for internal libraries

glslang/MachineIndependent/reflection.cpp
The compiler can't see that the loop in the first "if" will always execute at least once.  So it doesn't know that the blockIndex will actually be initialized before return, so the compiler throws a warning.
=> Avoid spurious warning about uninit var

CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, OGLCompilersDLL/InitializeDll.cpp, OGLCompilersDLL/InitializeDll.h, SPIRV/CMakeLists.txt, glslang/CMakeLists.txt, glslang/Include/InitializeGlobals.h, glslang/MachineIndependent/PoolAlloc.cpp
iOS 8 does not support `thread_local`, which is still in use.
Another approach will have to be found.
This change is a revert of the following changes:
a3845240 - "Simplify PoolAlloc with use of thread_local."
abf92c80 - "Deprecate InitializeDll functions"
33585c87 - "Limit visibility of symbols for internal libraries"
Issue: #2346
=> Revert changes that migrate to `thread_local`.

BUILD.gn, SPIRV/GlslangToSpv.cpp, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h, glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/localintermediate.h, glslang/MachineIndependent/parseVersions.h, glslang/MachineIndependent/reflection.cpp, glslang/MachineIndependent/reflection.h, glslang/Public/ShaderLang.h, gtests/Link.FromFile.Vk.cpp, gtests/TestFixture.h
This change strips a few features similar to GLSLANG_WEB but doesn't
remove every detail like the latter.  It also hardcodes profile/version
to core/450.
In particular, TBuiltIns::initialize is specialized to remove most of
what is not supported or won't be supported by ANGLE.  The result of
this function is parsed with TParseContext::parseShaderStrings which is
a performance bottleneck.
This change shaves about 300KB off of ANGLE's binary size and reduces
the cost of SetupBuiltinSymbolTable to nearly a sixth.
=> Use GLSLANG_ANGLE to strip features to what ANGLE requires

.appveyor.yml, README.md, WORKSPACE, gtests/AST.FromFile.cpp, gtests/Config.FromFile.cpp, gtests/HexFloat.cpp, gtests/Hlsl.FromFile.cpp, gtests/Link.FromFile.Vk.cpp, gtests/Link.FromFile.cpp, gtests/Pp.FromFile.cpp, gtests/Remap.FromFile.cpp, gtests/Spv.FromFile.cpp
These have a new spelling: INSTANTIATE_TEST_CASE_P -> INSTANTIATE_TEST_SUITE_P
=> Build/Test: Dropping VS 2013 allows using the latest googletests

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.bufferhandle17_Errors.frag.out, Test/baseResults/versionsErrors.frag.out, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/glslang.m4, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/glslang_tab.cpp.h, glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/localintermediate.h, glslang/MachineIndependent/parseVersions.h
Correct style is to recognize all of GLSL, and for optional features, after the feature is recognized, put a check for the right extensions being present in that path.  (Not to see what features are present and then go down different paths while parsing.)
See #2366 for more detail.
There were two main cases, a few checks for GL_EXT_buffer_reference2, and then a whole bunch of checks for what conversions are allowed.
This is draft until getting them all fixed.
=> Remove incorrect style of extension-based semantic checking.

SPIRV/CInterface/spirv_c_interface.cpp, glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h
Fixes FFI breakage introduced in #2283
=> GLSLANG_EXPORT for C APIs.

BUILD.bazel
The current implementation makes tests fail when it is imported from a different Bazel workspace.
We fix that by using the --test-root flag to pass the rootpath to the tests.
=> Use --test-root to pass files to Bazel tests.

SPIRV/doc.cpp
- OpExecutionModeId is not supported in disassembly.
- Some execution modes are missing in disassembled strings.
=> SPIRV: Fix some disassembly issues

glslang/MachineIndependent/Versions.cpp
The names of some extension macros are wrong because of coding typos.
=> Parser: Fix wrong names of extension macros

Test/baseResults/rayQuery-initialization.Error.comp.out, Test/rayQuery-initialization.Error.comp, glslang/MachineIndependent/ParseHelper.cpp, gtests/Spv.FromFile.cpp
This PR adds an error check to prevent initialization of ray query objects via assignment, since there are no valid constructors for the ray query object, and ray query objects cannot be copied. Without this change, the code in the new test generates an OpLoad/OpStore pair, which is invalid.
=> Error when initializing rayQuery with assignment

CMakeLists.txt
glslang build failed for missing python interpreter when cross-compile glslang for ios
https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake defines a handy find_host_package macro
If it exsits, use find_host_package, like how SPIRV-Tools handle it here
https://github.com/KhronosGroup/SPIRV-Tools/blob/726af6f78f80988271c8b558ae9cc84fa5a65016/CMakeLists.txt#L181
=> Find python interpreter from host when cross-compiling

Test/100scope.vert, Test/baseResults/100scope.vert.out, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/glslang.m4, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp
1. Add tokens related to IMAGE SHADOW.
2. Allow redefinition with a same name in parameter list. Only in ES 100.
" If it is declared as a parameter in a function definition, it is scoped until the end of that function definition.  A function body has a scope nested inside the function’s definition."
=> Fix scope definition in ES 100.

SPIRV/SPVRemapper.cpp, SPIRV/disassemble.cpp, SPIRV/doc.cpp, SPIRV/doc.h
According to the extension SPV_GOOGLE_decorate_string,
OpDecorateString (or OpMemberDecorateString) ought to be capable of
supporting multiple literal strings. Each literal strings are padded
with null terminator to make word alignment. The layout is:
`Inst | Target | Decoration | Literal String, Literal String, ...`
=> SPIRV: Add disassembly support for multiple literal strings

SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h
Add more builder functions to OpExecutionMode, OpExecutionModeId,
OpDecorateString, OpMemberDecorateString.
According to SPIR-V, OpExecutionMode and OpExecutionModeId could
take variable extra operands. Current implementation doesn't support
this and assumes at most 3 operands are extra operands. It is not
true. Similarly, OpDecorateString and OpMemberDecorateString could
support multiple strings either as literal strings or as string
operands. Further, OpDecorate and OpDecorateId have the same problem,
taking variable extra operands.
=> SPIRV: Add more utility functions to build some opcodes

BUILD.gn
The glslang public includes dir contains headers with implicit
conversion issues. Add -Wno-conversion to glslang's public config.
Bug: 60140
Bug: 58162
Change-Id: Iec27cb4242e9fdceddd6a3e02044a0bccfa0ce36
Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/glslang/+/429054
Reviewed-by: Petr Hosek <phosek@google.com>
=> [Wconversion] Suppress glslang issue

SPIRV/SPVRemapper.cpp
There's a statement that intends to generate a 32-bit hashcode, but due
to integer promotion, the intermediate values can trigger signed integer
overflow, which is undefined behavior.
To avoid this, cast at least one operand to unsigned int before
multiplying, which will cause the result to be promoted to unsigned int
instead of signed int.
With this patch, I'm able to build core for qemu-x64 with host_asan-ubsan.
Fixed: 60128
Change-Id: Idd644e534116bf29dca8013936ac39901bbe68fc
Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/glslang/+/428254
Reviewed-by: John Bauman <jbauman@google.com>
=> [spirv-remap] Fix undefined behavior in hashing

SPIRV/SpvTools.cpp, SPIRV/SpvTools.h, StandAlone/CMakeLists.txt, gtests/CMakeLists.txt
This addresses the problems highlighted in: #2405
- Add more flexible SpirvToolsDisassemble interface to allow specifying spv_target_env for disassembly output.
- Improve documentation on existing SpirvToolsDisassemble interface.
=> Add new SpirvToolsDisassemble API interface + Improve Doc on existing API interface

SPIRV/disassemble.cpp
disassemble.cpp appears not to be using anything from SpvTools.h, but the inclusion of it prevents standalone building of the SPIR-V portion (for instance, when needed purely for generation and disassembly) without SPIRV-Tools dependency.
=> SPIR-V: Remove SpvTools.h include from disassemble.cpp

glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/localintermediate.h
TIntermediate was constructed without initializing any of the `resources` fields, and `TProgram::linkStage()` was not calling `TIntermediate::setLimits()` after constructing new `TIntermediate`s for non-first stages.
Fields of `resources` were then read in `TIntermediate::finalCheck()` triggering undefined behavior.
This CL makes three changes:
1. `TIntermediate::setLimits()` is now called for non-first stages by copying the `firstIntermediate`'s limits. This ensures that the `resources` fields is initialized, fixing the bug.
2. `TIntermediate::resources` is now wrapped in a `MustBeAssigned<>` helper struct, asserting in non-release builds that this field is always initialized before reading.
3. `TIntermediate::resources` is now zero-initialized, so that if the `TIntermediate::resources` …
=> Fix uninitialized use of TIntermediate::resource

.gitignore, .gn, DEPS, README.md, build_overrides/build.gni, build_overrides/spirv_tools.gni, standalone.gclient
This allows glslang to be build standalone using the gn build system.
To build with gn:
```
gclient sync --gclientfile=standalone.gclient
gn gen out/default
cd out/default
ninja
```
Issue: #2421
=> Add basic GN configurations

.gitignore, DEPS, README.md, kokoro/linux-clang-gn/build.sh, kokoro/linux-clang-gn/continuous.cfg, kokoro/linux-clang-gn/presubmit.cfg
Add missing `.cfg` files for GN presubmit.
Add missing `recursedeps` in the `DEPS` file.
Call `./update_glslang_sources.py` before attempting to build.
Add more GN spew to the `.gitignore` file.
Fixes https://github.com/KhronosGroup/glslang/issues/2421
Related: https://github.com/KhronosGroup/glslang/issues/2413
=> Fix GN build and presubmits

SPIRV/SpvTools.cpp, known_good.json
Since spirv-opt will remove PropagateLineInfoPass and
RedundantLineInfoElimPass, glslang should not use it. spirv-opt will
propagate the line instructions and eliminate the redundant lines by
default in IR loading/emission.
=> Do not use PropagateLineInfoPass and RedundantLineInfoElimPass

BUILD.gn
Getting error about undefined symbol (include_dir) at line 320.
Was trying to append to a non-existant variable.
Bug #2445
=> Fix build error with Chromium & ANGLE

SPIRV/GlslangToSpv.cpp, Test/baseResults/300layout.vert.out, Test/baseResults/310.frag.out, Test/baseResults/310.vert.out, Test/baseResults/320.vert.out, Test/baseResults/410.geom.out, Test/baseResults/hlsl.structbuffer.append.fn.frag.out, Test/baseResults/hlsl.structbuffer.fn.frag.out, Test/baseResults/link.vk.multiBlocksValid.0.0.vert.out, Test/baseResults/link.vk.multiBlocksValid.1.0.geom.out, Test/baseResults/spv.specConstant.vert.out, glslang/Include/intermediate.h, glslang/MachineIndependent/IntermTraverse.cpp, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h, glslang/MachineIndependent/glslang.m4, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h, glslang/MachineIndependent/localintermediate.h, glslang/MachineIndependent/reflection.cpp
Fix io mapping issue:
1. refine usage of access name.
2. add validation of interfaces & buffer & uniforms
3. split nest level, for member check of invariant qualifier
4. use new id level setting, help to identify builtins
5. fix issues introduced by vector and usage of for_each in io mapping
=> 8. io mapping refine & qualifier member check & resolver expand

Test/baseResults/tokenPaste.vert.out, Test/tokenPaste.vert, glslang/MachineIndependent/preprocessor/Pp.cpp
Fixes #2443.  Macros resulting from token-pasting were not working correctly in macros used in `#if`, whereas it was working for other macros.
Thanks for considering this PR, it would be a big help since it is not trivial for us to work around.
=> Fix token-pasting macros not working in preprocessor directives.

glslang/MachineIndependent/linkValidate.cpp
no longer causes an incorrect error if the current unit has local_size
set, but the incoming unit does not
=> tweak local_size comparison a bit

glslang/MachineIndependent/reflection.cpp
Hi, KhronosGroup glslang Team.
I fixed compile warning for build with disabled HLSL.
Could you review and accept my changes, pls?
[339/369] Building CXX object glslang/CMakeFiles/MachineIndependent.dir/MachineIndependent/reflection.cpp.o
../glslang/MachineIndependent/reflection.cpp:1130:60: warning: unused parameter 'intermediate' [-Wunused-parameter]
void TReflection::buildCounterIndices(const TIntermediate& intermediate)
^
1 warning generated.
[369/369] Linking CXX executable gtests/glslangtests
You can see this warning online here:
https://github.com/Tencent/ncnn/runs/1556708847?check_suite_focus=true
Best regards, Proydakov Evgeny.
=> Fixed compile warning in reflection.cpp for ENABLE_HLSL = 0 build. [-Wunused-parameter]

CMakeLists.txt
When cmake is executed from MSVC with empty `CMAKE_CXX_FLAGS`, `string(REGEX...)` fails because not enough parameters are passed.
=> Fix option replacement when flags are empty

license-checker.cfg
The license classification rules in github.com/google/licensecheck have been updated.
=> license-checker.cfg: Update rules

glslang/MachineIndependent/Intermediate.cpp
UBSAN rightly complains on `push_front` here:
glslang/MachineIndependent/localintermediate.h:100:8: runtime error: load of value 160, which is not a valid value for type 'bool'
#0 in glslang::TCall::TCall(glslang::TCall&&) glslang/MachineIndependent/localintermediate.h:100
#1 in void __gnu_cxx::new_allocator<std::_List_node<glslang::TCall> >::construct<glslang::TCall, glslang::TCall>(glslang::TCall*, glslang::TCall&&) /usr/include/c++/10/ext/new_allocator.h:150
#2 in void std::allocator_traits<std::allocator<std::_List_node<glslang::TCall> > >::construct<glslang::TCall, glslang::TCall>(std::allocator<std::_List_node<glslang::TCall> >&, glslang::TCall*, glslang::TCall&&) /usr/include/c++/10/bits/alloc_traits.h:512
#3 in std::_List_node<glslang::TCall>* std::__cxx11::list<glslang::TCall, …
=> callGraph.push_front -> emplace_front to fix UBSAN

glslang/MachineIndependent/localintermediate.h
The extra semicolon causes a build failure if warnings are turned up high, and
warnings-as-errors is on. (-Werror=extra-semi)
=> Remove useless semicolon

CMakeLists.txt, build_info.h.tmpl, build_info.py, parse_version.cmake
Hi, GLSLANG Team.
I implemented fix to project version detection from CHANGED.md without python with approach 4.
https://github.com/KhronosGroup/glslang/issues/2496
Could you review and accept my changes, pls?
Best regards, Proydakov Evgeny.
=> Fixed issues 2496. Used option 4: parse_version.cmake to avoid python3 usage.

known_good.json
This is being done to allow Vulkan validation layers to pick up
the new differentiated error code support in spirv-tools for
GPU-AV.
=> Update spirv-tools and spirv-header known good.

glslang/MachineIndependent/ShaderLang.cpp
This PR fixes #2374 by passing environment through `TShader::preprocess` -> `PreprocessDeferred` -> `ProcessDeferred`. Previously, a default environment was used which causes preprocessing to fail when the shader uses extensions which aren't available in that environment.
=> Pass environment through PreprocessDeferred

glslang/MachineIndependent/SymbolTable.h
```
glslang/MachineIndependent/SymbolTable.h:892:41: error: comparison of integers of
different signs: 'int' and 'const uint32_t' (aka 'const unsigned int') [-Werror,-Wsign-compare]
uint64_t level = currentLevel() > MaxLevelInUniqueID ? MaxLevelInUniqueID : currentLevel();
~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
1 error generated.
```
=> Fix warning in build

glslang/MachineIndependent/ParseHelper.cpp
glslang don't report the errors: atomic counter can not specified with location.
```
#version 310 es
precision highp float;
layout(location = 3, binding = 0, offset = 0) uniform atomic_uint uni0;
in highp vec4 dEQP_Position;
out float out0;
void main()
{
out0 = 0.0;
gl_Position = dEQP_Position;
}
```
Signed-off-by: ZhiqianXia <xzq0528@outlook.com>
=> Cannot specify atomic counter with location.

CMakeLists.txt
Hi, GLSLANG Team.
Then I'm trying to regenerate project build files I see cmake warning.
As I see from kitware cmake main repo we should use 'cmake_minimum_version' before 'project' directive:
https://github.com/Kitware/CMake/blob/master/CMakeLists.txt
Could you verify and accept my changes, pls?
[BEFORE]:
% cmake ..
CMake Warning (dev) at CMakeLists.txt:35 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
CMAKE_PROJECT_VERSION
CMAKE_PROJECT_VERSION_MAJOR
CMAKE_PROJECT_VERSION_MINOR
CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
-- …
=> Fixed cmake generation warning for regeneration project build files.

CMakeLists.txt
By default cmake generates cxx_flags with /EHsc parameter.
I updated CMAKE_CXX_FLAGS string and removed /EHsc, also I added compile defenitions _HAS_EXCEPTIONS=0, it is mandatory for noexcept build with MSVC STL implementation.
Output files became smaller.
How to reproduce:
Visual Studio 2019 x64 command port
mkdir build-msvc2019
cd build-msvc2019
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=install ..
nmake
CXX FLAGS BEFORE:
-- CMAKE_C_FLAGS:   /DWIN32 /D_WINDOWS /W3
-- CMAKE_CXX_FLAGS: /DWIN32 /D_WINDOWS /W3 /GR- /EHsc
-- CMAKE_CXX_FLAGS_DEBUG:   /MDd /Zi /Ob0 /Od /RTC1
-- CMAKE_CXX_FLAGS_RELEASE: /MD /O2 /Ob2 /DNDEBUG
-- ENABLE_RTTI:       OFF
-- ENABLE_EXCEPTIONS: OFF
OUTPUT SIZE BEFORE:
Build folder size: 61,8 MB (64 808 580 bytes)
GLSLANG SIZE BEFORE: …
=> Fixed msvc 2019 nmake noexcept build.

SPIRV/GlslangToSpv.cpp
Using const char* is not a good choice. We assume strings are always
from spv::E_SPV_XXX definitions. However, it is not the case. We can
store the name strings of extended intruction set in local variables.
=> SPV: Change the key of extBuiltinMap to std::string

CMakeLists.txt
Hi, GLSLANG Team.
I changed this logic here: https://github.com/KhronosGroup/glslang/pull/2526/commits/05798c17fb17d339d66e064a407e75ceae4c0316
It was originally fixed here: https://github.com/KhronosGroup/glslang/commit/967fa92d14acea305267574faf63ebe753de98c4
Could you review & accept small change, pls?
Best regards, Proydakov Evgeny.
=> Returned using find_host_package for PythonInterp 3 instead of find_pachage.

Test/420.vert, Test/baseResults/420.vert.out, glslang/MachineIndependent/ParseHelper.cpp
The problem was only with arrays of samplers.
Fixes #2552
=> Fix off-by-1 bug in gl_MaxCombinedTextureImageUnits check

SPIRV/doc.cpp
Add it to GLSLang disassembler.
=> SPV: The capability string for RayTracingProvisionalKHR is missing

Test/baseResults/vk.relaxed.changeSet.vert.out, Test/vk.relaxed.changeSet.frag, Test/vk.relaxed.changeSet.vert, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/localintermediate.h, gtests/VkRelaxed.FromFile.cpp
Avoid adding global uniform blocks to stages that don't already have it.
Otherwise multiple stages point to the same block object, and a
remapping that occurs later on will change the mapping on multiple
stages.
This fixes an issue reported by @lance-loong where setResourceSetBinding() wasn't being respected due to one staging having default uniforms and another having none.
=> Fix issue with remapping global uniform blocks

Test/baseResults/link.vk.inconsistentGLPerVertex.0.vert.out, Test/link.vk.inconsistentGLPerVertex.0.geom, Test/link.vk.inconsistentGLPerVertex.0.vert, glslang/Include/Types.h, gtests/Link.FromFile.Vk.cpp
gl_SecondaryPositionNV and gl_PositionPerViewNV are inconsistently declared inside and outside of gl_PerVertex. This breaks interface block matching. For now ignore these errors since it should be fixed with how they are declared.
#2578
=> Partial fix for inconsistencies re: #2578

SPIRV/doc.cpp
The last operand for `OpGroupNonUniformQuadSwap` is incorrectly marked as literal, it's actually an id (see https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpGroupNonUniformQuadBroadcast)
As a result, running:
```
spv::spirvbin_t remapper(0);
remapper.remap(result, spv::spirvbin_base_t::MAP_FUNCS);
```
Will produce invalid SPIR-V when given the following as input:
``` 
%58 = OpTypeInt 32 0
%84 = OpConstant %58 0
%489 = OpGroupNonUniformQuadBroadcast %16 %101 %488 %84
```
The remapper will strip `%84` and just treat `84` as literal input to `OpGroupNonUniformQuadBroadcast`, resulting in invalid SPIR-V.
=> Fixed OpGroupNonUniformQuadBroadcast Direction operand being marked as a literal

BUILD.bazel
Only having `cmd` rather than separate `cmd_bash` and `cmd_bat` (or
`cmd_ps`) requires bash to be installed on Windows. So adding support
for `cmd_bat` makes glslangValidator easier to compile on Windows.
=> Add cmd_bat action to bazel export_spirv_headers target

glslang/Include/Types.h, gtests/VkRelaxed.FromFile.cpp
Warnings in public headers can trigger warnings-as-errors.
=> Fix warnings about int comparisons of different signness

Test/440.frag, Test/baseResults/440.frag.out, glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp
Packing qualifiers have no practical effect on scalars or vectors
so this is unnecessary and its confusing tools downstream that
consume the AST.
=> Do not propagate packing qualifiers to scalars or vectors

glslang/MachineIndependent/Versions.cpp
These got lost in the wash with my last revert but are still relevant.
=> Fix table key and whitespace

StandAlone/CMakeLists.txt
This way the limits are available to clients that link statically, which might be necessary due to the ORD problem https://github.com/KhronosGroup/glslang/issues/2346.
=> Removed condition for glslang-default-resource-limits instalation.

glslang/Include/Common.h, glslang/MachineIndependent/ParseHelper.cpp, gtests/CMakeLists.txt, gtests/Common.cpp
Replace uses of floating point log2 when we want an integer result from
an integer operand.  This avoids concerns about accuracy of floating
point library functions.
=> Add IntLog2 and use it

glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp
Nearly all the arithmetic builtin functions for non-32-bit types were missing. This commit adds them.
This is a fix to address one problem raised in https://github.com/google/shaderc/issues/1177.
=> Fix builtins for GL_EXT_shader_explicit_arithmetic_types for es

glslang/Public/ShaderLang.h
Fixes a typo in a comment in ShaderLang.h.
=> Typo in ShaderLang.h

Test/baseResults/textureoffset_sampler2darrayshadow.vert.out, Test/textureoffset_sampler2darrayshadow.vert, glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp, gtests/AST.FromFile.cpp
Hi ,
glslang should report an error about textureOffset , because textureOffset not support sampler2DArrayShadow sampler until 430.
shader
#version 300 es
precision mediump float;
in highp vec4 dEQP_Position;
uniform mediump sampler2DArrayShadow s;
void main()
{
gl_Position = vec4(textureOffset(s, vec4(0), ivec2(0)));
gl_Position = dEQP_Position;
}
Reference:
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.20.pdf
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf
=> TextureOffset not support sampler2DArrayShadow sampler until 430.

StandAlone/DirStackFileIncluder.h, StandAlone/StandAlone.cpp, Test/baseResults/hlsl.dashI.vert.d.out, Test/baseResults/hlsl.include.vert.d.out, Test/runtests
The output is similar to gcc -MMD and can be used by build systems like meson to automatically recompile shaders if an included header was changed.
Meson integration example:
```meson
shader_src = [
'foo.frag',
'bar.vert',
]
glsl_compiler = find_program('glslangValidator')
glsl_generator = generator(
glsl_compiler,
output    : [ '@BASENAME@.h' ],
arguments : [ '-V', '--vn', '@BASENAME@', '@INPUT@', '-o', '@OUTPUT@', '--depfile', '@DEPFILE@' ],
depfile   : '@DEPFILE@',
)
shaders = glsl_generator.process(shader_src)
```
=> Add a --depfile option in Standalone mode

StandAlone/StandAlone.cpp
This PR exposes the automatic Texture*D and SampleState merging introduced in #856 to the StandAlone application via --hlsl-sampled-textures. This closes #2611.
Since the new C++ API is only used in link mode, I am not sure whether exposing this functionality is possible via ShCompile. I only implemented it for link mode.
=> Exposed #856 as --hlsl-sampled-textures in the StandAlone

CMakeLists.txt
CMAKE_SYSTEM_NAME variable might evaluate to existing variable such as
CYGWIN. This setting also matches with SPIRV-Tools.
Warning was introduced with commit https://github.com/KhronosGroup/glslang/commit/17a83a9b33aa84addf51b7d2ee6e7ce2aec158ca
```
CMake Warning (dev) at glslang/glslang/CMakeLists.txt:36 (elseif):
Policy CMP0054 is not set: Only interpret if() arguments as variables or
keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
Quoted variables like "CYGWIN" will no longer be dereferenced when the
policy is set to NEW.  Since the policy is not set the OLD behavior will be
used.
```
SPIRV-Tools commit regarding `CMP0054` was: …
=> Set CMake policy CMP0054 to NEW to silence warning

Test/baseResults/matrix.frag.out, Test/matrix.frag, glslang/MachineIndependent/parseConst.cpp
As described in #2645, 4x2 matrices constructed with a scalar are handled improperly and contain an additional unwanted scalar value. This PR adds a test for this issue and fixes the constant-matrix handling code.
=> Fix mat4x2(scalar) constructor.

SPIRV/SpvBuilder.cpp
In a matrix constructor that takes a number of components, as many
components as necessary must be taken, with the rest discarded, as GLSL
allows more components than necessary to be specified.  For example, the
following:
mat4 m4 = mat4(v4, v4.yzwx, v4.zwx, v4.zwxy, v4.wxyz);
is equivalent to:
mat4 m4 = mat4(v4, v4.yzwx, v4.zwx, v4.zwxy, v4.w);
glslang takes the components from the constructor and builds the single
components of the matrix in a 2D array before constructing the matrix
itself.  It however did not check for extra parameters and was thus
writing OOB to said 2D array.  This is fixed in this change
Signed-off-by: Shahbaz Youssefi <shabbyx@gmail.com>
=> Fix OOB write in matrix constructor

glslang/Include/intermediate.h
Following up on #2600, this should allow us to manipulate selection nodes more cleanly than having to recreate them.
=> Add setters for true and false blocks of selection nodes, copying the pattern already used for the condition.

SPIRV/SPVRemapper.cpp
SPIR-V Remapper doesn't properly remap the instruction set ID, instead it'll just jump over it. This can be easily triggered by a shader that uses debug printf and then running SPIR-V remapper with `MAP_FUNCS`. This change simply calls the ID function on the instruction set ID as well, then jumps over the known literal.
=> Fix SPIR-V remapper not remapping OpExtInst instruction set IDs

Test/baseResults/150.frag.out, Test/baseResults/150.vert.out, Test/baseResults/400.frag.out, Test/baseResults/430scope.vert.out, Test/baseResults/450.vert.out, Test/baseResults/cppSimple.vert.out, Test/baseResults/link.multiAnonBlocksInvalid.0.0.vert.out, Test/baseResults/link.multiAnonBlocksValid.0.0.vert.out, Test/baseResults/link.multiBlocksInvalid.0.0.vert.out, Test/baseResults/link.multiBlocksValid.1.0.vert.out, Test/baseResults/specExamples.frag.out, Test/baseResults/specExamples.vert.out, Test/baseResults/specExamplesConf.vert.out, Test/baseResults/versionsErrors.vert.out, glslang/MachineIndependent/Initialize.cpp
avoid declaring them in GLSL 1.50+ if core profile is chosen by the version statement
fixes #2663
It seems like the ARBCompatibility variable is meant to act as if the hosting GL context was created with WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB. However I think this should only be inherited into the GLSL compiler for GLSL 1.40. 1.50+ should use what is declared by the #version statement. 
For the test cases that were changed, here are my thoughts:
430scope.vert
cppSimple.vert
link.multiAnonBlocksInvalid.0.0.vert
link.multiAnonBlocksValid.0.0.vert
link.multiBlocksInvalid.0.0.vert
link.multiBlocksValid.1.0.vert
versionsErrors.vert:
New output seems correct, the variables are just no longer declared:
150.vert:
core profile - gl_ClipVertex shouldn't be declared, new error is correct. …
=> only declare compatibility gl_ variables in compatibility mode

glslang/MachineIndependent/preprocessor/PpScanner.cpp
Remove an unused variable that causes build failures in downstream
repository.
=> Remove unused variable Num_string_literal_EXTs

Android.mk
It was missing, and was breaking the build for Android.mk.
=> Android.mk: Add SpirvIntrinsics.cpp

glslang/MachineIndependent/Initialize.cpp
```
#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(std430) buffer Output {
int data; 
} g_out;
void main() 
{ 
g_out.data = gl_MaxVaryingVectors; 
}
```
https://github.com/KhronosGroup/glslang/issues/2682
=> Add support for gl_MaxVaryingVectors for ogl.

StandAlone/StandAlone.cpp
Currently usages like this don't work at all:
```bash
glslangValidator -V --shift-UBO-binding 16 1 # add offset 16 to set 1 only
```
Seems to be a simple parsing problem.
=> Fix per-set argument parsing in standalone

SPIRV/SpvBuilder.cpp
Problem seen with += and ++ ops on swizzled lvalues. Was using stale access chain.
Fixes #2725.
=> Fix seperate stores to swizzled lvalue.

Test/atomicCounterARBOps.vert, Test/baseResults/atomicCounterARBOps.vert.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h, gtests/AST.FromFile.cpp
There are some atomicCounterXXXARB  built-in functons not supported at glslang.
**shader**
```
#version 450 core
#extension GL_ARB_shader_atomic_counters: enable
#extension GL_ARB_shader_atomic_counter_ops:enable
layout(binding = 0) uniform atomic_uint counter;
out highp vec4 vsColor;
void main(){
vec4 outColor = vec4(1.0);
uint ret;
ret = atomicCounterAddARB(counter, 4u);
ret = atomicCounterSubtractARB(counter, 4u);
ret = atomicCounterMinARB(counter, 4u);
ret = atomicCounterMaxARB(counter, 4u);
ret = atomicCounterAndARB(counter, 4u);
ret = atomicCounterOrARB(counter, 4u);
ret = atomicCounterXorARB(counter, 4u);
ret = atomicCounterExchangeARB(counter, 4u);
ret = atomicCounterCompSwapARB(counter, 4u, 4u);
uint after = atomicCounter(counter);
if (after == ret)
outColor = vec4(0.0);
vsColor …
```
=> Support the atomic_counter_xxxARB  built-in functons at #extension GL_ARB_shader_atomic_counter_ops.

glslang/Include/Common.h
MINGW_HAS_SECURE_API can be defined as 0, but this will be ignored here without this change.
=> Change MINGW_HAS_SECURE_API checks.

glslang/MachineIndependent/ParseContextBase.cpp
When using GL_EXT_vulkan_glsl_relaxed, check to see if a
uniform already exists in the block uniform block, and if so,
ensure they are the same type. If they are the same, avoid growing the block
with a duplicate. If they are different, throw an error.
=> GL_EXT_vulkan_glsl_relaxed - avoid growing the global uniform block with duplicates

glslang/Include/Types.h, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h, glslang/MachineIndependent/linkValidate.cpp
Add ability for the IO remapping to change the backing of a uniform buffer block to push_constant if it fits within a specified maximum size.
=> Auto push constant blocks

glslang/MachineIndependent/ParseHelper.cpp
the ol430 spec says:
**_Fall through labels are allowed, but it is a compile-time error to have no statement between a label and the end of the switch statement._** 
So if the glsl version <=430 , glslang should report a error for Feature: last case/default label not followed by statements'. 
**shader:**
```
#version 430
precision mediump float;
in highp vec4 dEQP_Position;
void main ()
{
switch (1)
{
case 0: break;
case 1:
}
gl_Position = dEQP_Position;
}
```
**specs:**
[1] https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf
[2] https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.40.pdf
=> glslang should report a error for Feature: last case/default label not followed by statements'. 

glslang/CInterface/glslang_c_interface.cpp
Currently, setting GLSLANG_TARGET_VULKAN_1_2 means falling back to GLSLANG_TARGET_VULKAN_1_0.
=> Add support for targeting Vulkan 1.2 in the C API

glslang/MachineIndependent/ShaderLang.cpp, glslang/OSDependent/Unix/ossource.cpp
I noticed that the current process initializer is extremely thread-unsafe, in multiple ways, despite ostensibly taking a mutex.
=> Thread safety fixes

Test/baseResults/link.redeclareBuiltin.vert.out, Test/link.redeclareBuiltin.geom, Test/link.redeclareBuiltin.vert, glslang/Include/Types.h, glslang/MachineIndependent/linkValidate.cpp, gtests/Link.FromFile.cpp
Whenever a built in block such as gl_PerVertex is explicitly redeclared glslang has slightly different behavior depending on whether or not the block is anonymous. For blocks that have an instance name any members absent from the redeclaration are simply deleted, while for anonymous blocks any members absent from the redeclaration are instead "hidden". Most of the codebase handles hidden members correctly but the sameStructType() function does not. As a result of this whenever identical redeclarations of gl_PerVertex with one or more members omitted appear in both the vertex and geometry stages sameStructType() will incorrectly report that the types do not match. This change fixes the logic in sameStructType() to correctly skip hidden members when comparing structures.
=> Fix incorrect link time validation for unused gl_PerVertex members

glslang/ExtensionHeaders/GL_EXT_shader_realtime_clock.glsl, glslang/MachineIndependent/Initialize.cpp
It was not visable via glslang library interface. Blocking SDK build.
=> Revert port GL_EXT_shader_realtime_clock to GL_EXT_spirv_intrinsics

glslang/Include/Common.h, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/intermOut.cpp
(Updated variant of #2802 that fixes build issues in Windows).
There were two implementations of isInf() and isNan(), in Constant.cpp
and in intermOut.cpp. The former only works on little-endian systems,
the latter is a wrapper for library functions and works regardless of
endianness. Move the second version into Common.h and adopt it in both
places. Thereby avoid the duplication and fix for big-endian systems.
In the ill-fated #2802 I had missed a required header for builds on Windows, which surfaced as build failures in Chromium's ANGLE (reported in #2808). I have put together a Windows build environment for ANGLE, reproduced the build failure, and build-tested this new PR there.
On s390x, this fixes the test case
Glsl/CompileToAstTest.FromFile/constFold_frag.
Fixes #2802
=> Use intermOut.cpp's IsNan and IsInfinity for parse-time constant folding (updated)

glslang/MachineIndependent/Intermediate.cpp
The signedness of type char is implementation-defined in C++. The conversion to (signed) int8 currently uses a cast to char, which is undefined for negative values when the type char is implemented as unsigned (e.g., on s390x). Thus, fix to cast to "signed char", which has the intended semantic on all implementations.
Fixes #2807
Tested on Linux on s390x and x86-64 and Windows on x86-64.
=> TIntermediate::promoteConstantUnion(): fix conversion to int8

glslang/MachineIndependent/SymbolTable.h
Using non-default flags for clang for memory sanitizer disclosed uses of uniqueId where it was uninitialized.
=> Initialize member TSymbol::uniqueId.

SPIRV/SPVRemapper.cpp, SPIRV/disassemble.cpp, SPIRV/spvIR.h
Per SPIR-V spec, a string literal's UTF-8 octets are encoded packed into
words with little-endian convention. Explicitly perform that encoding
instead of assuming that the host system is little-endian.
Note that this change requires corresponding fixes in SPIRV-Tools (proposed in PR https://github.com/KhronosGroup/SPIRV-Tools/pull/4622)
Fixes #202
Tested on x86-64 and s390x, no regression in google test-backed tests or in ./runTests-backed tests.
=> Fix encoding/decoding of string literals for big-endian systems

LICENSE.txt
* This license is used by:
* SPIRV/GLSL.ext.AMD.h
* SPIRV/GLSL.ext.EXT.h
* SPIRV/GLSL.ext.KHR.h
* SPIRV/GLSL.ext.NV.h
This was flagged by our internal tooling as a missing license from LICENSE.txt.
=> Add missing license to LICENSE.txt

CMakeLists.txt
`CMAKE_INSTALL_PREFIX` variable is only useful when you want to run the CMake "install" target so this variable should only be overridden when it is necessary.
It will prevent issue https://github.com/KhronosGroup/glslang/issues/1015 on projects which include glslang but don't need to install it (using SKIP_GLSLANG_INSTALL) .
=> Override CMAKE_INSTALL_PREFIX only if ENABLE_GLSLANG_INSTALL is ON

Test/EndStreamPrimitive.geom, Test/baseResults/150.geom.out, Test/baseResults/EndStreamPrimitive.geom.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp, gtests/AST.FromFile.cpp
Fix the issue https://github.com/KhronosGroup/glslang/issues/2734.
=> EndStreamPrimitive not supported when there is #extension GL_ARB_gpu_shader5

CMakeLists.txt
Closes #2861
This PR adds a few minor changes for building with gcc on Mac OS X. It changes the default for `ENABLE_PCH` to `OFF` for that particular configuration and avoids adding the --no-undefined linker flag since it isn't valid for the default MacOS linker.
I changed the default for ENABLE_PCH rather than disabling entirely so that it would still be configurable and existing builds shouldn't break. However, it should now work out-of-the-box after cloning.
=> #2861 macos gcc build failures

glslang/Public/ShaderLang.h, gtests/Hlsl.FromFile.cpp, gtests/Spv.FromFile.cpp
These tests will be re-enabled when a Vulkan version is released that
supports spirv1.6.
Fixes #2858
=> Temporarily disable spirv1.6 tests

BUILD.gn
Fuchsia GN build requires all "action" targets to be hermetic, and they should correctly and fully state their inputs and ouptuts in "sources" and "outputs" fields (see https://fuchsia.dev/fuchsia-src/development/build/hermetic_actions
for details).
This change adds "sources" field to "glslang_extension_headers" build target so that it states all its input files in its GN target build rule.
TEST=fx set workstation.x64 --args=build_should_trace_actions=true
fx build
=> build: Make action targets hermetic

Test/baseResults/vk.relaxed.stagelink.0.0.vert.out, Test/vk.relaxed.stagelink.0.0.frag, Test/vk.relaxed.stagelink.0.0.vert, Test/vk.relaxed.stagelink.0.1.frag, Test/vk.relaxed.stagelink.0.1.vert, Test/vk.relaxed.stagelink.0.2.frag, Test/vk.relaxed.stagelink.0.2.vert, glslang/MachineIndependent/linkValidate.cpp, gtests/VkRelaxed.FromFile.cpp
For GL_EXT_vulkan_glsl_relaxed. When merging the default uniform block,
there were cases where symbols in the tree wern't updated to match the
new block structure after merging blocks together.
This change traverses the symbol tree and updates any references to the
merged block.
=> fix cases where symbols in the tree didn't get updated during block merging

glslang/Include/Types.h
There is apparently a hole in the initialization of sampler in TType
so that a simple comparison which should pass might fail. Until the
hole is found, also test that both types are samplers before comparing
the sampler field for equality.
Fixes #2875
=> Fix sameElementShape test of sampler

glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h
uniform blocks that are upgraded to push_constants shouldn't have
set/binding etc. decorations applied to them
=> avoid leaving decorations on auto-push-constants

Test/baseResults/spv.textureError.frag.out, Test/runtests, Test/spv.textureError.frag, glslang/MachineIndependent/ParseHelper.cpp
For recent GLSL versions, if texture2D function call appears, the error
message reports an unsupported type constructor. Change message to
unsupported function. Likewise for other removed texture* function calls.
=> Improve error message for image/sampler functions under enhanced-msgs

Test/baseResults/coord_conventions.frag.out, Test/coord_conventions.frag, glslang/MachineIndependent/ParseHelper.cpp, gtests/AST.FromFile.cpp
1. refine the check for "origin_upper_left" and "pixel_center_integer"
2. gl_FragCoord can be used at ogl140 with extension "GL_ARB_fragment_coord_conventions".
Signed-off-by: ZhiqianXia <xzq0528@outlook.com>
=> Fix the issue for GL_ARB_fragment_coord_conventions extension.

Test/baseResults/vulkan.frag.out, Test/vulkan.frag, glslang/MachineIndependent/ParseHelper.cpp
The [WG agreed](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5080) that the following shader makes no sense
```glsl
layout(push_constant) uniform PushData {
float a;
} data[2];
void main() {
float x = data[1].a;
}
```
So I have a [spirv-val](https://github.com/KhronosGroup/SPIRV-Tools/pull/4742) patch ready as well when the VUID appears in a future release. The Vulkan spec change is just waiting on deciding how to best word this restriction
=> Prevent Push Constant blocks being an array

StandAlone/StandAlone.cpp, Test/baseResults/glsl.versionOverride.comp.out, Test/baseResults/glsl.versionOverride.frag.out, Test/baseResults/glsl.versionOverride.geom.out, Test/baseResults/glsl.versionOverride.tesc.out, Test/baseResults/glsl.versionOverride.tese.out, Test/baseResults/glsl.versionOverride.vert.out, Test/glsl.versionOverride.comp, Test/glsl.versionOverride.frag, Test/glsl.versionOverride.geom, Test/glsl.versionOverride.tesc, Test/glsl.versionOverride.tese, Test/glsl.versionOverride.vert, Test/runtests, glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h, gtests/TestFixture.h
PR to address question assekd in ##2850.
This change list allows a user to override the GLSL version from the
command line or through the C and C++ interfaces. This will override the
override happens in ProcessDeferred() before DeduceVersionProfile() so
the process should still error out if the version is insufficient for
the shader code.
- Added --glsl-version <version> to CLI.
- Added parameter to route glslVersion as override version to
preprocessor and parse functions to C++ interface.
- Updated C interface with function to override GLSL version.
=> Added GLSL version override functionality and CLI

README.md
While looking for the ray tracing shaders file extensions I had to look inside the source code to find them
https://github.com/KhronosGroup/glslang/blob/2c7c84c8ac996b16b2645046dd1757043669ed52/gtests/TestFixture.cpp#L49
Since the rasterization filename extensions are already listed why not include the ray tracing ones?
=> Update README.md with ray tracing shader stages filename extensions

CMakeLists.txt
Pre compiled headers lead to `internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:192: MapViewOfFileEx: Attempt to access invalid address`.
closes https://github.com/KhronosGroup/glslang/issues/2922
=> CMake: fix MinGW build

README.md
ANDROID_NDK_ROOT is claimed to deprecated, update to use ANDROID_NDK_HOME to align with VulkanSamples repo.
=> Change ANDROID_NDK_ROOT to ANDROID_NDK_HOME in README.md

Test/baseResults/hlsl.waveprefix.comp.out, glslang/HLSL/hlslParseHelper.cpp
It was counting bits up to the current lane included, whereas the
documentation says it should be excluded. This now matches dxc's behavior
as well.
Fix #2929
=> Fix WavePrefixCountBits() being off by one.

SPIRV/SPVRemapper.cpp, SPIRV/SPVRemapper.h, StandAlone/spirv-remap.cpp, gtests/TestFixture.h
We are currently using glslang and spirv-remap for a project we would like to open source and as part of the compilation step, we need the ability to not strip out some "unused" functions in the SPIRV. We currently do this by passing in a whitelist file to the remapper. It would greatly simplify things if we could get this also added to the glslang codebase.
=> Add whitelist filtering for debug comments in SPIRV-Remap.

glslang/MachineIndependent/linkValidate.cpp
For EOpIndexDirectStruct binaries, we want to visit the left symbol (the
structure) before we visit the binary, so it gets updated first.
That way we are comparing the updated structure against the target
'unitType', not the original structure.
=> fix structure indexing reassignment during block merging

Android.mk, README.md
Both `glslang/CInterface` and `SPIRV/CInterface` files are missing from `Android.mk`.
Added missing documentation.
=> Add CInterface files and documentation

SPIRV/SPVRemapper.cpp, SPIRV/SPVRemapper.h
Fixes ABI breakage caused by #2933
=> Restore legacy interface for remap()

SPIRV/CInterface/spirv_c_interface.cpp, glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h
The C interface was lacking support for adding `OpSource` source code information instruction to the resulting SPIR-V.
This PR adds C interface counterparts of `TIntermediate::addSourceText`, `TIntermediate::setSourceFile` and `SpvOptions`.
I opted not to change the signature of `glslang_program_SPIRV_generate` so as not to break existing code,
instead adding a variant `glslang_program_SPIRV_generate_with_options` which additionally takes the `SpvOptions` counterpart,
and restructured `glslang_program_SPIRV_generate` to be implemented in terms of the latter to avoid code duplication.
=> Add OpSource support to the C interface.

build_info.h.tmpl
These were defined backwards to the usual convention.
#if GLSLANG_VERSION_GREATER_THAN(11, 10, 0)
This reads as "if glslang version is greater than 11.10.0" to any
reasonable sane programmer, and should therefore expand to
"glslang_version > macro_argument".
Yet the check it references was actually written as "macro_argument >
glslang_version", thus expressing the completely opposite condition of
"if glslang version is *less than* 11.10.0". This is definitely
backwards and extremely, dangerously surprising behavior to any
programmer familiar with such version macros.
I'm not sure if anybody actually ever used them. I certainly didn't, on
account of them being backwards. I could not find a single reference to
them on GitHub (other than in copies of this header) - every project I
found just …
=> Fix version check macros

.github/workflows/continuous_deployment.yml
The workflow used to only zip files in `include/glslang/*`, which does not respect subdirectories. Also including `include/glslang/**/*` fixes this issue. If you look at the current builds, you can precisely observe this behaviour as `build_info.h` in the root directory is actually zipped. The `${SUFFIX}` seems to also have been blindly copied from the old CI which has no usage anymore. This workflow never worked. I fully tested this on Ubuntu 20.04 in WSL and on my macOS 13 Mac.
Also, I've rewritten the GitHub workflow to also build for Windows, but is there any reason why VS 2015 is strictly *required*? GitHub workflow only offers VS Enterprise 2017, VS Enterprise 2019, or VS Enterprise 2022.
Fixes #2658.
=> Fix #2658: Properly include all headers in deployments

glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h
When rewriting function calls atomicCounterIncrement and
atoicCounterDecrement, clone the parameters so that the TParameter
'type' field is cloned.  This avoids double-free when both the original
and transformed functions are deleted by the parser.
Fixes a ubsan failure.
=> Avoid double-free in functions cloned for vulkan relaxed mode

CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, gtests/CMakeLists.txt, hlsl/CMakeLists.txt
This PR introduce a new and unified `glslang` CMake config package, all `glslang` targets are exposed through `glslang::` CMake namespace.
Prior to this PR there were several exported CMake target under various name, no package.
With those changes, and when set properly, any CMake project  should be able to consume `glslang` by simply calling `find_package(glslang CONFIG)` and then pick whatever targets they need (e.g. `glslang::glslang`, `glslang::SPIRV`, etc.)
Note that as I am not really sure which existing projects uses existing exported CMake targets via direct includes, I still provide a layer of backward compatibility and issue a warning.
I see that there are a number of pending PR/issues already (#1978, #2751, #2750, #2778 and maybe more ?) but they seems to be on hold as I do not …
=> Add unified `glslang` CMake config collecting `glslang-targets` targets

.github/workflows/continuous_deployment.yml
x86_64 binaries cannot be linked when building solely for arm64. This uses the matrix to build separately for x86_64 and arm64. I specifically opted for this instead of building a universal binary as there seems to be no guarantee that universal binary 2 files can be read and understood by older linkers, and the fact that a universal binary will effectively have two copies of the library/executable wasting a considerable amount of space. Also, upgrading the runner to `macOS-11` in 457d11ebd86c089f00a934e579f9c4dc76921e71 was required for this to work.
=> Fix: Build arm64 binaries for macOS

CMakeLists.txt, OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, gtests/CMakeLists.txt, hlsl/CMakeLists.txt
As glslang ships architecture dependant files, the Config file should be installed to `libdir`, not `datadir`. See https://github.com/KhronosGroup/glslang/pull/2989#discussion_r955367103 for more details.
Here's the diff between the install tree before and after this patch:
$ diff <(tree install-datadir) <(tree install)
1c1
< install-datadir
---
> install
74,99c74,98
<         ├── lib
<         │   ├── cmake
<         │   │   ├── glslang-default-resource-limitsTargets.cmake
<         │   │   ├── glslangTargets.cmake
<         │   │   ├── glslangValidatorTargets.cmake
<         │   │   ├── HLSLTargets.cmake
<         │   │   ├── OGLCompilerTargets.cmake
<         │   │   ├── OSDependentTargets.cmake
<         │   │   ├── spirv-remapTargets.cmake
<         │   │   ├── SPIRVTargets.cmake
< …
=> build: install glslang-config.cmake to libdir

SPIRV/GlslangToSpv.cpp
Dereferencing a type-punned pointer breaks type aliasing rules, leading to undefined behavior as in this statement:
```
unsigned literal = *reinterpret_cast<unsigned*>(&floatValue);
```
This can be fixed with `std::bit_cast`, but I use `memcpy` for compatibility with C++11 (and `static_assert` for safety):
```
unsigned literal;
static_assert(sizeof(literal) == sizeof(floatValue), "sizeof(unsigned) != sizeof(float)");
memcpy(&literal, &floatValue, sizeof(literal));
```
=> Fix strict aliasing violation

glslang/OSDependent/Unix/ossource.cpp, glslang/OSDependent/osinclude.h
I was building glslang for a platform that doesn't support `PTHREAD_CANCEL_ENABLE` and during the investigation about what it was being used for I realized that its only use belongs in an unused function — `OS_CleanupThreadData`.
=> Remove the unused `OS_CleanupThreadData`

glslang/Include/Common.h
Since 12e27e17deb3102f1f6f08ec19caf5e32becb3f8, it was assumed that the
MINGW_HAS_SECURE_API macro was unconditionally defined. This is not
always the case, and GCC produces -Wundef warnings when that happens.
Fix this, by first checking if MINGW_HAS_SECURE_API is defined, and if
so, also check that it does not evaluate to zero.
As a drive-by, place parentheses around _MSC_VER for consistency.
=> Fix -Wundef warnings for MINGW_HAS_SECURE_API

CMakeLists.txt
At least on openSUSE, the usual installation location for cmake support files is ${CMAKE_INSTALL_LIBDIR}/cmake/<name>
$ find /usr/lib64 -name '*.cmake' | grep /cmake/ | wc -l
834
$ find /usr/lib64 -name '*.cmake' | grep -v /cmake/ | wc -l
8
which is also used by glslang with these changes.
=> cmake: Use common installation directory for cmake support files.

OGLCompilersDLL/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt
The glslang cmake build system installs static libraries in addition to the dynamic glslang library, which are required when used in a package that uses glslang when calling find_package().
Distributions such as openSUSE (and perhaps others) use a "shared only" strategy, which conflicts with the current state of the glslang build system.
The static libraries mentioned are already all included in glslang and thus not needed. With this commit, these will no longer install the associated cmake support files when glslang is built shared.
See https://build.opensuse.org/request/show/1001407 for a related issue description.
=> cmake: Do not install static libraries in shared build mode

glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h
The C interface was lacking support for using the preamble feature.
This PR adds a C interface counterpart of `TShader::setPreamble`.
=> Add preamble support to the C interface.

SPIRV/SpvTools.cpp
It can't be safely used unilaterally on other stages, since that will result in output/input mismatches between stages. They arn't having their output variables eliminated accordingly.
=> only use dead input elimination on vertex shaders

glslang/MachineIndependent/ParseHelper.cpp
When GL_EXT_mesh_shader is enabled, the check of layout qualifiers 'max_vertices' and 'max_primitives' should use
gl_MaxMeshOutputVerticesEXT and gl_MaxMeshOutputPrimitivesEXT.
=> Fix incorrect parse message of mesh shader

BUILD.bazel, StandAlone/ResourceLimits.cpp, StandAlone/StandAlone.cpp, StandAlone/resource_limits_c.cpp, glslang/CInterface/glslang_c_interface.cpp, glslang/CMakeLists.txt, glslang/Public/ResourceLimits.h, glslang/Public/resource_limits_c.h, gtests/BuiltInResource.FromFile.cpp, gtests/Config.FromFile.cpp, gtests/TestFixture.h
New interface allows users to generate ResourceLimits for interface so that additions to TBuiltInResource do not break the ABI.
Users should use the glslang-default-resource-limits library and the Public/ResourceLimits.h header. Similar changes have been made to the C interface. Use Public/resource_limits_c.h.
Fixes #2822
=> Improve ResourceLimits interface to be more forward compatible

BUILD.gn, SPIRV/GlslangToSpv.cpp, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/SymbolTable.h, glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/localintermediate.h, glslang/MachineIndependent/parseVersions.h, glslang/MachineIndependent/reflection.cpp, glslang/MachineIndependent/reflection.h, glslang/Public/ShaderLang.h, gtests/Link.FromFile.Vk.cpp, gtests/TestFixture.h
ANGLE no longer links with glslang.  This change reverts 1ef2e250fc36d862573cc5e92f04b1d0e2d89867 which added a flag to strip glslang to reduce its binary size.  This flag is no longer needed.
=> Remove GLSLANG_ANGLE

OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, gtests/CMakeLists.txt, hlsl/CMakeLists.txt
In https://github.com/KhronosGroup/glslang/pull/3027, the installed cmake files were stuck into a /cmake subdir but this isn't reflected in these compatibility shims. The shims were added in https://github.com/KhronosGroup/glslang/pull/2989.
=> Fix locations of cmake files in side compat shims

SPIRV/SpvTools.cpp, SPIRV/SpvTools.h
Also eliminates dead output variables and unused output variable components. Finally calls aggressive dead code elimination.
AnalyzeDeadOutputStores also supplied to be called on the following shader to provide input for the Eliminate* function.
=> Add EliminateDeadOutputStores to API.

glslang/Include/PoolAlloc.h
On Windows, _DEBUG is defined by CMake if CMAKE_BUILD_TYPE is Debug. But on other platforms, this is not the case and thus in debug mode, the guard checks are not enabled.
Instead, rely on the NDEBUG define, which is always defined in release mode (Release, RelWithDebInfo and MinSizeRel). This works reliably on all platforms: It is also used to enable or disable assertions.
=> Include: PoolAlloc: do not rely on CMake define

SPIRV/SpvTools.cpp
This eliminates a compiler warning in some configurations.
=> Remove the name of unused formal paramters

StandAlone/ResourceLimits.cpp, glslang/Include/glslang_c_interface.h, gtests/BuiltInResource.FromFile.cpp
This PR fixes two issues introduced with the addition of support for MaxDualSourceDrawBuffersEXT.
First, glslangValidator's ResourceLimits.cpp was never updated to support the newly defined MaxDualSourceDrawBuffersEXT limit, causing the following warning to be output whenever glslangValidator is invoked with a default configuration file generated by glslangValidator's -c argument:
> Warning: unrecognized limit (MaxDualSourceDrawBuffersEXT) in configuration file.
This PR adds the appropriate check to recognize and apply this limit.
Second, the option for MaxDualSourceDrawBuffersEXT was added to the glslang_resource_s struct with inconsistent capitalization compared to all other members of the same struct (and indeed the entire C interface). This PR updates the struct definition with a …
=> Fix issues with MaxDualSourceDrawBuffersEXT

.appveyor.yml
SPIRV-Tools now requires 3.17.2 or higher. The version provided by Visual Studio 2015 is 3.16.2.
=> Update appveyor environment

Test/baseResults/120.vert.out, glslang/MachineIndependent/ParseHelper.cpp
GLSL 1.20 and prior stated that "the attribute qualifier can be used only with float, floating-point vectors, and matrices" and likewise for varying.
Fixes: #3111
=> Reject non-float inputs/outputs with version < 120

Test/baseResults/hlsl.wavebroadcast.comp.out, Test/baseResults/hlsl.waveprefix.comp.out, Test/baseResults/hlsl.wavequad.comp.out, Test/baseResults/hlsl.wavequery.comp.out, Test/baseResults/hlsl.wavereduction.comp.out, Test/baseResults/hlsl.wavevote.comp.out, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h
...From TParseContext used only by GLSL, to TParseContextBase inherited by both GLSL and HLSL paths. It caused compilations from HLSL to SPIR-V 1.3+ to use BufferBlock decoration which is no longer valid.
=> Move check if useStorageBuffer needs to be set

.appveyor.yml, .github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml, .github/workflows/deploy.js, README.md
Update CI and README to reflect rename.
Update News:
* Notify users of rename.
* Update minimum required VS compiler to 2019.
* Remove notice about versioning. This has been completed.
* Remove notice about SPIRV folder relocation. It has been 2.5 years
since this occured.
Fix #3107
=> Rename master to main and update news

glslang/MachineIndependent/Constant.cpp
New versions of Clang warn:
```
glslang/MachineIndependent/Constant.cpp(216,114):
error: overflow in expression; result is -9223372036854775808 with type 'long long' [-Werror,-Winteger-overflow]
else if (rightUnionArray[i].getI64Const() == -1 && leftUnionArray[i].getI64Const() == (long long)-0x8000000000000000ll)
^
glslang/MachineIndependent/Constant.cpp(217,61):
error: overflow in expression; result is -9223372036854775808 with type 'long long' [-Werror,-Winteger-overflow]
newConstArray[i].setI64Const((long long)-0x8000000000000000ll);
^
2 errors generated.
```
Using LLONG_MIN instead avoids the problem. I think it's also more clear, and the code for EOpMod further down already does this.
=> GLSL: Fix integer overflow warnings in Constant.cpp

kokoro/linux-clang-gn/build-docker.sh
In the docker build script that Kokoro runs, the directories are owned by a different user.  Git complains about that and in the GN flow GN will error out.
In this docker flow we don't care about that warning, so within the docker config set a git global option to ignore the issue.
=> kokoro: avoid git permissions issue that GN fails on

CMakeLists.txt, README.md
Remove cmake condition. The minimum is 3.14. The condition is no longer required.
C++17 is now required. Update the landing page.
=> Fix outdated cmake conditional

kokoro/linux-clang-gn/build.sh
If the CI goes into abort state, the logs are locked. This should allow the CI to correctly fail with the build failure state.
=> ci: fix CI going into abort state when it's a build failure.

Test/baseResults/preprocessor.function_macro.vert.out, Test/preprocessor.function_macro.vert, glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpContext.h, glslang/MachineIndependent/preprocessor/PpScanner.cpp, glslang/MachineIndependent/preprocessor/PpTokens.cpp
Macro arguments were getting expanded twice, causing issues when a macro's name appeared in its definition.
Fixes #3112
I was a bit skeptical that this is the correct fix, but it does fix the issue and doesn't cause any problems in any of the testing I have done.
=> Fix double expansion of macro parameters

CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt
Fix #3125 (also reported in vcpkg: https://github.com/microsoft/vcpkg/issues/27121).
The CMake target `OSDependent` requires `Threads::Threads` on Unix, but the requirement of Threads is not exported in the installed Config.cmake file. This PR adds the necessary `find_dependency(Threads REQUIRED)` to the installed Config.cmake file.
Further the OSDependent CMake includes workarounds with seem outdated with the currently required minimum version of 3.14.0. The check if( < 3.1) could be just removed. The second mentioned issue about cross compiling was closed upstream over 5 years ago and I verified that the mentioned fix commit is contained in CMake 3.10.0. So I assume should be also save to remove if CMake 3.14 is required anyway, but I do not have a cross compilation toolchain to …
=> Fix CMake for OSDependent install

Test/baseResults/440.frag.out, glslang/HLSL/hlslParseHelper.cpp, glslang/MachineIndependent/ParseHelper.cpp
The I thought there was a bug in GLSL but once I printed the values in the error message it made sense it was my shader
error message diff
```patch
- ERROR: struct.vert:16: 'offset' : must be a multiple of the member's alignment
+ ERROR: struct.vert:16: 'offset' : must be a multiple of the member's alignment (layout offset = 8 | member alignment = 16)
```
=> Improve error message of alignment offset

Test/baseResults/hlsl.emptystructreturn.tesc.out, Test/hlsl.emptystructreturn.tesc, glslang/HLSL/hlslParseHelper.cpp, gtests/Hlsl.FromFile.cpp
fix crash, when converting HLSL return of hull shader into spirv/glsl like arrayed output.
#fixed 2914
=> fix crash in HLSL frontend

.github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml
This removes the need for AppVeyor in this repository. This workflow however runs on windows-2016, meaning that by default these are being built with Visual Studio Enterprise 2017. If that's not acceptable, this can wait until VS 2015 is deprecated by you. Also includes some nice things that weren't ported in the original migration.
Also, note that the AppVeyor auth token was always public in the .appveyor.yml config :) https://github.com/KhronosGroup/glslang/blob/607771c3622dc5c01e2e2ec088324383db1964fc/.appveyor.yml#L99
=> Fix: Migrate Windows CI to GitHub Actions

Test/baseResults/300layout.vert.out, glslang/MachineIndependent/ParseHelper.cpp
Vertex shaders can have pipeline inputs that are arrays, but not structure
inputs. (GLSL 4.5 section 4.3.4)
But the error message for struct inputs says "cannot be a structure or array".
This PR removes the "or array" part.
Note: The array case is handled immediately after the check for
structure type.
=> fix error message for vertex struct input

CMakeLists.txt
OpenBSD does not link shared libs against libc so it is expected that the use of --no-undefined when linking will fail.
=> Fix building on OpenBSD when building shared libs

OGLCompilersDLL/CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, gtests/CMakeLists.txt, hlsl/CMakeLists.txt
According to
https://cmake.org/cmake/help/v3.25/module/GNUInstallDirs.html, CMAKE_INSTALL_LIBDIR can be an absolute path. For instance, Nixpkgs [defined it to an absolute path in /nix/store](https://github.com/NixOS/nixpkgs/blob/3d17b4c305cefef284109fa9d426b00f3e5072c6/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L101). The output in this case is:
include("${CMAKE_CURRENT_LIST_DIR}/../..//nix/store/3mif2zibig0cilk5dbz334278n0vlq9s-glslang-1.3.231.0/lib/glslang/glslang-targets.cmake")
Signed-off-by: Chuang Zhu <git@chuang.cz>
=> Use CMAKE_INSTALL_FULL_LIBDIR in compat cmake files

StandAlone/CMakeLists.txt
On QNX, pthread APIs are provided as part of libc and a separate pthread library does not exist.
This change updates the makefile of glslang to not link with pthread on QNX, thereby enabling glslang to be built for QNX platforms.
=> glslang: Do not link with pthread on QNX

kokoro/windows-msvc-2019-release-bazel/build.bat, kokoro/windows-msvc-2019-release-bazel/continuous.cfg, kokoro/windows-msvc-2019-release-bazel/presubmit.cfg
The `windows-msvc-2015-release-bazel` build config name is misleading.
It now runs VS2019. We should rename it. This is the first part: create
the new config files.
=> Add windows-msvc-2019-release-bazel CI config

CMakeLists.txt
They no longer happen "all over" as the comment suggests, and downstream builds have them enabled already.
=> Enable constructor reorder warnings

SPIRV/SPVRemapper.cpp, SPIRV/SPVRemapper.h, SPIRV/hex_float.h, StandAlone/spirv-remap.cpp, glslang/Include/Common.h, glslang/MachineIndependent/preprocessor/PpTokens.cpp
Since https://github.com/KhronosGroup/glslang/commit/58d302cfa28d04efafab64025d7b7ad5e5029ba7, the minimum VS version was raised to VS2019. Adjust the README, and remove some workarounds for older VS versions.
=> Remove workarounds for older MSVC versions

glslang/Include/glslang_c_interface.h
=> glslang_c_interface: use valid C function prototypes

kokoro/android-ndk-build/build-docker.sh, ndk_test/jni/Application.mk
Vulkan was introduced in Android API 24.
Test against that API level.
NDKs drop support for older APIs
Google-internal BUG=285134453
=> ndk-build: test Android API 24

glslang/Include/Types.h, glslang/MachineIndependent/SymbolTable.cpp
Fix some potentially uninitialized uses that are reported by GCC 13 with `-O3`.
=> Fix -Wmaybe-uninitialized warnings

glslang/MachineIndependent/Versions.cpp
As per spec, the extension defines [GL_NV_shader_invocation_reorder](https://github.com/KhronosGroup/GLSL/blob/f7f0724d62b701c4f13b03999f81c02315407f7b/extensions/nv/GLSL_NV_shader_invocation_reorder.txt#L136) as 1. There is no GL_NV_shader_execution_reorder.
=> Fix GL_NV_shader_invocation_reorder #define typo

CMakeLists.txt, StandAlone/CMakeLists.txt
The FindPythonInterp and FindPythonLibs modules, which have been deprecated since CMake 3.12, have been removed by policy CMP0148. Port projects to FindPython3, FindPython2, or FindPython.
=> cmake: Fix CMake 3.27 warnings

CMakeLists.txt
This PR prevents CMake from attempting to add the `--no-undefined` option when compiling on macOS with a compiler other than `AppleClang`. On Mac OS X 10.9 and older, Apple Clang cannot be used to compile glslang, because the Clang inside of Xcode is so old that the C++17 standard isn't supported. So instead, an updated version of Clang must be used, such as through [MacPorts](https://www.macports.org/) or [Homebrew](https://brew.sh).
However, the `--no-undefined` linking option doesn't exist on the Mac platform, regardless of which Clang is being used, so using a "non-Apple Clang" Clang to build glslang will result in the following error during linking:
```
ld: unknown option: --no-undefined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This is the …
=> Fix linking error "ld: unknown option: --no-undefined" on macOS

SPIRV/SpvBuilder.cpp
The `function` parameter is only used by an assert currently, so mark it as "maybe unused".  Alternatively the parameter could be removed, but avoid such public API churn for now.
=> Fix unused parameter warning in Release builds

README.md
Remove the usage of C++ STL types in the C-only interface example.
Fixes #3239.
=> Fix C example in README

SPIRV/doc.cpp
There was a race condition in this function as it used a static variable to attempt to ensure global initialization was only done once, which was not thread-safe. Instead, use std::call_once, which was added to C++11 for this exact case.
Fixes #342
=> Use std::call_once in spv::Parameterize()

glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h
Ensure we traverse the entire tree and upgrade all references to the given symbol so it can be upgraded to push_constant. Without this change only one instance was upgraded, and others were left as uniform buffers.
=> Rework how auto push_constant upgrading works a bit.

glslang/OSDependent/Web/glslang.js.cpp
add missing initialization members.
maxMeshOutputVerticesEXT -> maxMeshOutputVerticesNV
=> missing initialization members for web

CMakeLists.txt, README-spirv-remap.txt, README.md, StandAlone/CMakeLists.txt, StandAlone/StandAlone.cpp, Test/baseResults/size, Test/glsl.versionOverride.geom, Test/glsl.versionOverride.tesc, Test/glsl.versionOverride.tese, Test/glslangValidator, Test/makeDoc, Test/runtests, Test/validate-shaders.sh, Test/web.runtests, gtests/TestFixture.h
Rename glslangValidator to glslang and adds a glslangValidator symlink to the build and install directories.
Closes #47.
=> cmake: Rename glslang to glslangValidator

StandAlone/CMakeLists.txt
Copy the old glslangValidator name on Windows rather than creating a symlink. While cmake 3.13 and above supports creating symlinks on Windows, a security policy change is required in general to allow the creation of symlinks for non-trusted users. See https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links
Fixes #3268.
=> cmake: Fix symlink on Windows

glslang/MachineIndependent/SpirvIntrinsics.cpp
The parameter could be removed, but keep it for consistency with other `makeSpirvTypeParameters` overloads.
=> Silence unused parameter warning

.gitignore
CMakeUserPresets.json can be useful for developers and is not meant to be checked in.
=> git: Ignore CMakeUserPresets.json

StandAlone/CMakeLists.txt, glslang/MachineIndependent/ShaderLang.cpp, glslang/OSDependent/Unix/ossource.cpp, glslang/OSDependent/Windows/ossource.cpp, glslang/OSDependent/osinclude.h
The usage of GetGlobalLock/ReleaseGlobalLock/InitGlobalLock is replaced by std::lock_guard which is available as of c++11, and the functions are removed from the OSDependent ossource.cpp files.
std::lock_guard is already used in `StandAlone/WorkList.h` and has been there since 2017.
=> Replace GlobalLock functions with std::mutex

.github/workflows/continuous_integration.yml, README.md
Adds a build-only (no test) job for testing the emscripten (web) build on github actions.
=> Add emscripten build to CI

CMakeLists.txt
This allows to build with optimizer enabled, if external SPIR-V tools libraries are available in the system. It is quite common in *nix world to package spirv-tools and glslang separately.
=> Look for external SPIR-V Tools build, if not building in-tree

StandAlone/CMakeLists.txt
The functionality of `libSPVRemapper` is only used by the `spirv-remap` executable, so don't link it into the `glslang` executable.
=> cmake: Don't link SPVRemapper into glslang executable

README.md
Replaces the appveyor build (which is no longer used) with a badge pointing to the continuous_integration.yml job status.
=> Fix CI build badge

glslang/Include/PoolAlloc.h, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Initialize.h, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/PoolAlloc.cpp, glslang/MachineIndependent/preprocessor/Pp.cpp
On a shared build, these symbols exist in both libglslang.so and libSPIRV.so, leading to an ODR violation at runtime.
Detected through ASAN.
=> Fix ODR violations

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.buffer_ref_parameter.comp.out, Test/hlsl.buffer_ref_parameter.comp, gtests/Hlsl.FromFile.cpp
Make sure that an id represents a variable before adding it to an entry point's interface.
Fixes #3297.
=> Fix ByteAddressBuffer as function parameter

.github/dependabot.yml, .github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml, .github/workflows/scorecard.yml
Closes #3321 
I've used step security tool to help on getting the hash commits, but also I've manually validate them 
https://github.com/lukka/get-cmake/commit/4dcd3eb73017c61159eb130746fbca35d78a3d5f - v3.27.4
https://github.com/actions/checkout/commit/f43a0e5ff2bd294095638e18286ca9a3d1956744 -  v3.6.0
https://github.com/actions/setup-python/commit/61a6322f88396a6271a6ee3565807d608ecaddd1 - v4.7.0
https://github.com/actions/github-script/commit/d7906e4ad0b1822421a7e6a35d5ca353c962f410 - v6.4.1
https://github.com/hendrikmuhs/ccache-action/commit/ca3acd2731eef11f1572ccb126356c2f9298d35e - v1.2.10
https://github.com/mymindstorm/setup-emsdk/commit/29ba4851d6da084ffdc1e0fc390efadbd75df9d1 - v12
I've configured the dependabot with a maximum of 3 PRs per week. Though, it is also possible to …
=> Hash pin and auto-update workflow dependencies

glslang/CMakeLists.txt
=> Revert "CMake: Make glslang-default-resource-limits STATIC"

CMakeLists.txt, kokoro/linux-clang-cmake/build-docker.sh, kokoro/linux-gcc-cmake/build-docker.sh
This makes it more clear to users when SPIR-V optimization is disabled because SPIRV-Tools could not be found, and suggests alternatives for finding it.
=> cmake: add more verbose messages if SPIRV-Tools is not found

.github/dependabot.yml
I've added the apache-2.0 license header. Let me know if the file should be actually under another license
=> Add license to dependabot.yml

Test/baseResults/atomicAdd.comp.out, Test/baseResults/spv.atomicRvalue.error.vert.out, Test/spv.atomicRvalue.error.vert, glslang/MachineIndependent/ParseHelper.cpp, gtests/Spv.FromFile.cpp
Makes sure that we have an l-value before checking the storage type of the mem argument passed to an atomic memory operation.
Fixes #3332.
=> Fix segfault with atomic arg check

.github/workflows/continuous_integration.yml, StandAlone/StandAlone.cpp
Add jobs for testing with -fsanitize=address and -fsanitize=thread.
=> Add ASAN and TSAN integration testing

SPIRV/GlslangToSpv.cpp, Test/baseResults/hlsl.structcopylogical.comp.out
SPIR-V 1.6 added the LocalSizeId execution mode that allows using spec constants for setting the work-group size, however it does not deprecate the LocalSize mode. This change causes the LocalSizeId mode to only be used when at least one of the workgroup size is actually specified with a spec constant.
Fixes #3200
=> spirv: only set LocalSizeId mode when necessary

SPIRV/CInterface/spirv_c_interface.cpp
Looks like the `compile_only` struct field of `glslang_spv_options_t` is not being set, so it's just holding garbage memory and causing unwanted behaviour by implicitly resolving to `true` most times.
=> Add missing initialization of `compile_only` field for SPIRV C interface

.github/workflows/continuous_integration.yml
The Windows tests job in Github Actions was incorrectly reporting 'success' on failed runs. This change ensures a single command is run in each test 'step' to help remove any guesswork w.r.t. the shell behavior on each platform.
This change also takes the oppportunity to make the formatting more consistent in continuous_integration.yml.
=> Fix Windows GHA Tests

StandAlone/CMakeLists.txt, StandAlone/StandAlone.cpp, glslang/GenericCodeGen/CodeGen.cpp, glslang/GenericCodeGen/Link.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h
The debug options passed down from the public ShConstruct* functions to internal code is unused. This change removes the internal debugOptions fields and attempts to make it more obvious these fields are not used.
This change does not change the public-facing interface.
This change also adds the -Wshorten-64-to-32 warning to the StandAlone build in order to avoid unwanted 64-to-32 bit conversions in the future.
Closes #3348.
=> Remove debugOptions from internal classes

Test/baseResults/vk.relaxed.errorcheck.vert.out, Test/vk.relaxed.errorcheck.frag, glslang/MachineIndependent/ParseContextBase.cpp
avoids nullptr crash from reading memberType's name, and more user friendly error message.
=> tweak error behavior for redeclared uniforms for vulkan-relaxed

.github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml, README.md, known_good.json, known_good_khr.json
https://github.com/google/googletest/issues/3128
Seems like at one point googletest had an issue with an older version of Xcode. I wasn't able to repro the build failure with v1.14.0
This adds googletest to the known_good.json to simplify CI / developer workflow
=> Use googletest version 1.14.0

SPIRV/GlslangToSpv.cpp, glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/iomapper.cpp
hasSprivDecorate => hasSpirvDecorate
=> GL_EXT_spirv_intrinsics: Fix a typo in function naming

update_glslang_sources.py
The distutils package was removed in Python 3.12, however its only usage in this script can easily be replaced with functionality available in the builtin os package in Python 3.2 and later.
Fixes #3393
=> Fix update_glslang_sources.py to not use distutils

Test/400.frag, Test/baseResults/400.frag.out, glslang/MachineIndependent/Initialize.cpp
Ensure that GL_ARB_shader_storage_buffer_object is available from version GL 400 to GL 420.
Closes #3263.
=> Fix GL_ARB_shader_storage_buffer_object version

Test/baseResults/glsl.interpOp.error.frag.out, Test/glsl.interpOp.error.frag, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/localintermediate.h, gtests/AST.FromFile.cpp
The restriction of no swizzling and no struct fields as an interpolant were not being checked when using the ES profile.
Fixes #3277.
=> Fix interpolant ES error

SPIRV/CMakeLists.txt, SPIRV/GlslangToSpv.cpp, SPIRV/GlslangToSpv.h, SPIRV/SPVRemapper.h, SPIRV/SpvTools.h, StandAlone/StandAlone.cpp, glslang/CMakeLists.txt, gtests/TestFixture.h
Only the headers that are part of glslang's public interface are installed. Previously, all of its headers were installed, which exposed a lot of internal implementation details and made it difficult to maintain backward compatiblity. This reduces the API surface somewhat and will make it easier to maintain API and ABI compatibility.
This PR also makes some changes to header files to remove dependencies on things outside the "public API" set listed in #3320. The only exception not on that list but still used is `SPIRV/spirv.hpp`.
=> cmake: only install public headers

SPIRV/SpvBuilder.cpp, SPIRV/SpvBuilder.h, Test/baseResults/spv.debuginfo.const_params.glsl.comp.out
For passing-by-value semantic, DebugDeclare cannot be used for parameters because there's no pointer.
=> Support NonSemantic DebugValue and generate it for const arg

Test/baseResults/overflow_underflow_toinf_0.out, Test/overflow_underflow_toinf_0.frag, Test/runtests, glslang/MachineIndependent/Intermediate.cpp
…40 and 1.0e-50 are normal values.
Shader1：
precision highp float;
out vec4 my_FragColor;
void main()
{
// Out-of-range floats should overflow to infinity // GLSL ES 3.00.6 section 4.1.4 Floats:
// "If the value of the floating point number is too large (small) to be stored as a single precision value, it is converted to positive (negative) infinity" float correct = isinf(1.0e40) ? 1.0 : 0.0;
my_FragColor = vec4(0.0, correct, 0.0, 1.0);
}
precision highp float;
out vec4 my_FragColor;
void main()
{
// GLSL ES 3.00.6 section 4.1.4 Floats:
// "A value with a magnitude too small to be represented as a mantissa and exponent is converted to zero." // 1.0e-50 is small enough that it can't even be stored as subnormal. float correct = (1.0e-50 == 0.0) ? 1.0 : 0.0;
my_FragColor = vec4(0.0, correct, …
=> Out-of-range floats should overflow to infinity

SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, gtests/CMakeLists.txt
The build is currently broken when using external SPIRV-Tools. This happens when `find_package(SPIRV-Tools-opt)` is used here: https://github.com/KhronosGroup/glslang/blob/589431af5c86b0be3cc23175258451be1f5d25b3/CMakeLists.txt#L271
The problem is using `${spirv-tools_SOURCE_DIR}`. This variable is defined by CMake on [a project() command](https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html). But a spirv-tools project() command is only present when using spirv-tools via `add_subdirectory`. Therefore, when using external spirv-tools via find_package, the variable is just empty and no include dirs are set.
This PR is trying to fix this by linking the spirv-tools-opt target instead, which should set the include directories automatically and will work with using …
=> Fix CMake spirv-tools dependency

glslang/Include/Common.h, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/intermOut.cpp
Use the ones from the <cmath> header instead, now that that is available on all the currently supported versions of MSVC.
=> Remove custom implementations of isinf and isnan

.github/workflows/continuous_integration.yml, CMakeLists.txt
Fix iOS build as well as minor Android cleanup since the problems for both platforms are so similar
=> Add iOS build to CI

CMakeLists.txt
XCode 15 includes a completely new linker implementation. Hence some flags are deprecated.
The default is now error so we can simply remove the linker option.
=> Fix Xcode 15 linker warning

CMakeLists.txt, StandAlone/CMakeLists.txt
Originally added in https://github.com/KhronosGroup/glslang/pull/2395
With the rational of causing issues when cross-compiling for iOS.
This is no longer the case.
=> Remove find_host_package macro

SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt
It seems there is no `External` directory installed. This leads to include dir not found CMake errors when glslang is used from other tools with find_package().
=> No external install include dir

CMakeLists.txt, known_good.json
As of KhronosGroup/SPIRV-Tools/pull/5482
SPIRV-Tools builds cleanly for Android/iOS by default
=> cmake: Remove SPIRV-Tools workaround

Test/baseResults/vk.relaxed.frag.out, Test/vk.relaxed.frag, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/localintermediate.h
This PR is a companion to another PR we recently opened on `KhronosGroup/GLSL` : https://github.com/KhronosGroup/GLSL/pull/218
It implements the procedure described in the suggested changes to `GL_EXT_vulkan_glsl_relaxed`.
Samplers are extracted out of structures and moved to the topmost level available. In the context of uniform, that's the global uniform block. For structures passed as function parameters, we create invisible parameters and properly route arguments to them.
We also extend the `vk.relaxed.frag` test shader to demonstrate these added capabilities.
=> Implement relaxed rule for opaque struct members

.github/workflows/continuous_integration.yml, CMakeLists.txt, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ParseHelper.h, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp
Adds a cmake BUILD_WERROR option to enable warnings as errors. This option is off by default, but is enabled for CI runs.
This change also cleans up a few more compiler warnings.
=> Add BUILD_WERROR option

Test/baseResults/overflow_underflow_toinf_0.frag.out, Test/overflow_underflow_toinf_0.frag, Test/runtests, gtests/AST.FromFile.cpp
Add test cases that will make explicit ±0.0 and ±INF appear in the AST output to make sure those cases are handled correctly.
Also, move overflow_underflow_toinf_0 from runtests to gtest. gtest is the preferred framework for simple tests that don't require    passing special command-line options to glslang.
=> Improve overflow_underflow_toinf_0 test somewhat

glslang/Include/intermediate.h, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/preprocessor/PpContext.h, glslang/ResourceLimits/resource_limits_c.cpp
This requires a small change to to use strncpy() instead of strcpy(), as well as change of include paths to not use "..". The other warnings are just not being hit anymore.
=> Remove various warning suppression pragmas

CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt, gtests/CMakeLists.txt
Further remove installing glslangtests. There isn't a need to do that. glslangtests isn't a deliverable.
=> Only install/test if PROJECT_IS_TOP_LEVEL

External/CMakeLists.txt
Currently glslang will build everything from spirv-tools regardless of if it needs to.
EXCLUDE_FROM_ALL dramatically improves the build performance.
Compiling 446 files to 292
Furthermore only the targets we need to install are installed.
=> SPIRV-Tools EXCLUDE_FROM_ALL

External/CMakeLists.txt
libSPIRV-Tools.a and libSPIRV-Tools-opt.a aren't being installed.
=> Fix continous_deployment

glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/Versions.cpp
As mentioned in issue https://github.com/KhronosGroup/glslang/issues/3223, the support for `GL_ARB_bindless_texture` results in confusing error messages, where a user is asked to enable an extension that is actually unavailable to them.
This PR amends one such error message to be clearer. It also moves the unconditionnal definition of the `GL_ARB_bindless_texture` macro so it isn't defined when targeting SPIR-V, since defining it anyway could break shader code that relied on it to test for the extension's availability.
=> Advertise GL_ARB_bindless_texture as unavailable for SPIR-V outputs

glslang/MachineIndependent/Constant.cpp
@arcady-lunarg U64 value type was incorrectly checked, commit fixed this.
=> Fixed check uint64 before set bool

glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/span.h
Removes some of the pointers/"end markes" used in the BuiltInFuntion versioning, replacing them with std::arrays and spans.
NOTE: The span class used is a copy of the span class that has been in use in the Vulkan-ValidationLayers as a temporary solution until C++20 is available.
NOTE: The std::arrays could be constexprs, but this requires some extra work pre-C++20, and is therefore not included in this change, but could be done in a follow up PR.
=> Use C++ containers for builtin versioning

Test/GL_ARB_texture_multisample.vert, Test/baseResults/GL_ARB_texture_multisample.vert.out, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/ParseHelper.cpp, gtests/AST.FromFile.cpp
This extension allows the use of "texelFetch" and "textureSize" with 2DMS sampler.
#version 140
out float result;
uniform sampler2DMS data;
uniform sampler2DMSArray data1;
void main()
{
result = texelFetch(data, ivec2(0), 3).r;
ivec2 temp = textureSize(data);
result = texelFetch(data1, ivec3(0), 3).r;
ivec3 temp1 = textureSize(data1);
}
=> support GL_ARB_texture_multisample extension.

SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt
These files have had a deprecation notice for a few years now and the cmake find_package mechanism should be used instead.
=> cmake: remove generation of deprecated *Targets.cmake files

CMakeLists.txt
The generated `glslang-targets.cmake` file (for static glslang targets) contains this:
```cmake
set_target_properties(glslang::SPIRV PROPERTIES
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:glslang::MachineIndependent>;\$<LINK_ONLY:SPIRV-Tools-opt>"
)
```
The `SPIRV-Tools-opt` here is as CMake target, but also the name of a real library file (`libSPIRV-Tools-opt.so` or `libSPIRV-Tools-opt.a`) which will be linked with (missing its dependency `SPIRV-Tools`) if the target is nonexistent. The `find_dependency` will import the target automatically.
`REQUIRED` is not needed in `find_dependency`, otherwise `find_package(glslang)` without `REQUIRED` will produce a fatal error if `Threads` is not found.
=> cmake: add missing SPIRV-Tools-opt dependency

CMakeLists.txt, SPIRV/CMakeLists.txt, StandAlone/CMakeLists.txt, glslang/CMakeLists.txt, glslang/OSDependent/Unix/CMakeLists.txt, glslang/OSDependent/Windows/CMakeLists.txt
Expose GLSLANG_TESTS and GLSLANG_ENABLE_INSTALL as options that can be controlled from an enclosing project, or from the command line.
They retain the prior default behaviour. In particular, if Glslang is not the top level project, then they default to OFF.
Fixes: #3507
=> Allow external control of whether Glslang will be tested or installed

SPIRV/CInterface/spirv_c_interface.cpp
Each time you call `glslang_program_SPIRV_generate`, it appends the output to whatever has been previously generated.  Here's an example:
```c
#include "glslang_c_interface.h"
#include "resource_limits_c.h"
#include <stdlib.h>
#include <stdio.h>
int main() {
const char* source = "#version 460\n"
"void main() { gl_Position = vec4(1.); }";
glslang_initialize_process();
glslang_program_t* program = glslang_program_create();
glslang_input_t input = {
.language = GLSLANG_SOURCE_GLSL,
.stage = GLSLANG_STAGE_VERTEX,
.client = GLSLANG_CLIENT_VULKAN,
.client_version = GLSLANG_TARGET_VULKAN_1_1,
.target_language = GLSLANG_TARGET_SPV,
.target_language_version = GLSLANG_TARGET_SPV_1_6,
.code = source,
.default_version = 460,
.default_profile = GLSLANG_NO_PROFILE,
.forward_compatible = true,
.resource …
```
=> Make C interface SPIR-V generation idempotent

glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp, glslang/MachineIndependent/iomapper.cpp, gtests/Spv.FromFile.cpp, gtests/VkRelaxed.FromFile.cpp
Like with the last few PRs from me, it fixes a warning that's commonly enabled in downstream projects that might want to consume glslang via FetchContent or equivalent.
It doesn't actually enable the warning, but that might be desirable.
I think I found a bug in the Spv.FromFile.cpp tests that would have been prevented had this warning been enabled all along. I had to guess the value for the missing field, so went for the most common one in the list. The only test case that used a different value before had an RWTexture1D, so if baseImageBinding is meaning the same kind of image as image load store in OpenGL, it would make sense that that would be the only one to need a non-zero value for the binding.
I'm a little concerned that the test wasn't previously failing with the …
=> -Wmissing-field-initializers fixes

Test/runtests
This means it won't die if the build path contains spaces.
I've got the build directory in the VS Code CMake extension set to `${workspaceFolder}/build/${buildKit}` so I can have MSVC and MSYS2 (MinGW UCRT) build systems without having to clone the repo twice and sync my changes back and forth for testing. `${buildKit}` contains spaces, and there's apparently nothing I can do to stop that, so it's preferable that the tests can handle the build directory having spaces.
=> Quote paths in runtest

SPIRV/GlslangToSpv.cpp, SPIRV/SpvPostProcess.cpp, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/reflection.cpp
This is intended so that downstream projects consuming glslang with FetchContent or similar means can use `-Wimplicit-fallthrough` without getting warning spam.
I've used my best judgement to determine whether the implicit fallthrough was desired, or was simply unreachable code. `std::unreachable` is unavailable until C++23, but I saw places where `default: assert(0);` was used, so copied that. There were a few places where some code might actually have been reachable and intended to return a value that represented an error, so someone should double check that kind of thing.
I've run the tests, and get a single failure that also fails on main, so it doesn't look like I broke anything, but I don't know how exhaustive the tests are.
This doesn't enable `-Wimplicit-fallthrough`, but that …
=> Remove implicit fallthrough

CMakeLists.txt, SPIRV/GlslangToSpv.cpp, SPIRV/disassemble.cpp, glslang/HLSL/hlslGrammar.cpp, glslang/HLSL/hlslParseHelper.cpp, glslang/MachineIndependent/Initialize.cpp, glslang/MachineIndependent/Intermediate.cpp, glslang/MachineIndependent/ParseContextBase.cpp, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/SymbolTable.cpp, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/intermOut.cpp, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/reflection.cpp
This follows up on work done by @AnyOldName3 in #3518, clang is a bit pickier than gcc when it comes to fallthrough comments.
=> Fix implicit-fallthrough warnings and enable the warning flags in CMakelists.txt

SPIRV/GlslangToSpv.cpp, Test/baseResults/spv.nvAtomicFp16Vec.frag.out
I'm also clarifying the spec at https://github.com/KhronosGroup/SPIRV-Registry/pull/241
=> Change fp16_vector_atomic to not require other SPIR-V atomic extensions

Test/baseResults/preprocess.arb_shading_language_include.vert.err, Test/baseResults/preprocess.include_directive_missing_extension.vert.err, Test/baseResults/preprocessor.include.disabled.vert.err, Test/preprocess.arb_shading_language_include.vert, Test/preprocess.include_directive_missing_extension.vert, glslang/MachineIndependent/Versions.cpp, glslang/MachineIndependent/Versions.h, glslang/MachineIndependent/parseVersions.h, glslang/MachineIndependent/preprocessor/Pp.cpp, gtests/Pp.FromFile.cpp
Add support for GL_ARB_shading_language_include. Usage is identical to the way GL_GOOGLE_include_directive currently works glslang (since GL_ARB_shading_language_include is inherently a runtime feature and glslang is an offline compiler).
Users can simulate their runtime environment by using a custom glslang::TShader::Includer or using filenames that match their GL runtime names.
Closes #249.
=> Add support for GL_ARB_shading_language_include

glslang/Include/Types.h
Fix #3538.
Visual Studio 2022 added a new warning to detect when enumerators can not be represented within the given bit field width. This warning is disabled by default but can be enabled using the flag /w15249. This PR increases the width by one to accommodate the signed maximum value of EvqLast, which is currently 32.
Perhaps a future improvement would be to use scoped enums; however, that is more work as the typing is more strict and would require more changes.
=> Increase TStorageQualifier bitfield width

StandAlone/StandAlone.cpp, Test/UTF8BOM.vert, Test/baseResults/UTF8BOM.vert.out, Test/runtests
This PR allows glslangvalidator to consume the byte-order mark (BOM) when it appears at the start of a text stream.  The Unicode spec, Version 9.0, Section 23.8, reads: "Systems that use the byte order mark must recognize when an initial U+FEFF signals the byte order. In those cases, it is not part of the textual content and should be removed before processing,"
=> Support files with UTF8BOM character

.github/workflows/continuous_integration.yml
This is needed because newer linux kernels cause problems for the sanitizers.
=> build: fix CI sanitizer failures

Test/baseResults/vk.relaxed.frag.out, glslang/MachineIndependent/ParseHelper.cpp, glslang/MachineIndependent/glslang.y, glslang/MachineIndependent/glslang_tab.cpp
This change is introduced in an attempt to fix issue #3536.
Even though top-level opaque type variables are semantically valid under Vulkan semantics, previous versions would mistakenly move them around, resulting in unnecessary complex binaries.
=> Branch out of relaxed rules on opaque arguments declared at top-level

Test/baseResults/positive_infinity.frag.out, Test/positive_infinity.frag, glslang/MachineIndependent/preprocessor/PpScanner.cpp, gtests/AST.FromFile.cpp
Even for a double precision float, the largest valid exponent is 308, so
clamp exponents to 500 when parsing to avoid overflow of the parsed
exponent value if the exponent is too big.
Also add a test for this case courtesy of @jimihem.
=> Check for exponent overflow in float parser

SPIRV/GlslangToSpv.cpp, SPIRV/SpvBuilder.cpp, Test/baseResults/hlsl.inf.vert.out, Test/baseResults/spv.bufferhandle13.frag.out, Test/baseResults/spv.ext.ClosestHitShader_Subgroup.rchit.out, Test/baseResults/spv.memoryQualifier.frag.out, Test/baseResults/spv.nvAtomicFp16Vec.frag.out, Test/baseResults/vk.relaxed.frag.out, Test/baseResults/vk.relaxed.link1.frag.out, Test/baseResults/vk.relaxed.stagelink.vert.out, known_good.json
* Update SPIRV-Tools
* https://github.com/KhronosGroup/SPIRV-Tools/pull/5641 added validation that caught errors
* Modified glslang to prevent duplicate Restrict and Coherent decorations
=> Prevent duplicate SPIR-V decorations

Test/baseResults/hlsl.inf.vert.out, Test/hlsl.inf.vert
Test/hlsl.inf.vert tests parsing and some constant math on infinities, including (-1.#INF * 0.0).
By IEEE 754 rules, that result is a NaN, but its sign is not significant. The test output assumes a negative-NaN is in the generated SPIR-V.
However, the math library on some platforms (like macOS 14, a.k.a. Sonoma) will produce a positive NaN instead.
This PR adjusts the test so it takes the absolute value of the NaN, to ensure we the emitted SPIR-V has the NaN with a 0 for it sign bit.
=> Adjust hlsl infinity-constant test

Test/baseResults/index_outside_sample_mask_range.frag.out, Test/index_outside_sample_mask_range.frag, glslang/MachineIndependent/ParseHelper.cpp, gtests/AST.FromFile.cpp
index outside gl_SampleMask range, compiler need report error.
#version 320 es 
layout (location = 0) out mediump vec4 fs_color; 
void main() 
{ 
const highp int invalidIndex = (gl_MaxSamples + 31) / 32; 
highp int invalidValue = gl_SampleMask[invalidIndex]; 
fs_color = vec4(1.0f, 0.0f, 0.0f, 1.0f); 
}
=>  index outside gl_SampleMask range, compiler need report error.

glslang/MachineIndependent/localintermediate.h
In 0bbec2e8f, the code started using usedIo[4], however it never increased the size of the array to make that index actually valid.
=> Increase the TIntermediate::usedIo array

SPIRV/CMakeLists.txt, glslang/CMakeLists.txt
This makes things consistent between when glslang is installed and imported versus when it's included as nested CMake project. You can now use `glslang::glslang` in both cases instead of needing the non-namespaced version sometimes and the namespaced one other times.
Resolves one of the problems discussed in https://github.com/KhronosGroup/glslang/issues/3509
Note: Some downstream projects may be using system-installed glslang as `glslang` instead of `glslang::glslang`, but this is fragile and isn't actually supposed to work - when passing an un-namespaced library name to `target_link_libraries`, if it's not an existing CMake target, CMake won't emit an error, and will fall back to just adding an extra linker flag like `-lglslang`. If you've already got the right library directory enabled …
=> Add aliases for the public libraries

glslang/MachineIndependent/ParseHelper.cpp
Original Issue Reported: https://github.com/KhronosGroup/glslang/issues/3616
This change affects the following type of shaders (which do identity conversion for 8/16 bit types):
```
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
#define TYPE float16_t
layout(binding = 0) readonly buffer A { TYPE data_a[]; };
layout(binding = 1) writeonly buffer D { TYPE data_d[]; };
void main() {
const uint i = gl_GlobalInvocationID.x;
data_d[i] = TYPE(data_a[i]);
}
```
Earlier (before this fix), it generated incorrect SPIR-V convert instructions.
**Ran `ctest` and it reports all tests are passsing:**
Test project /home/ravi/OpenSource/glslang/build
Start 1: glslang-testsuite
1/2 Test #1: glslang-testsuite ................   Passed   30.53 sec
Start 2: glslang-gtests
2/2 Test #2: …
=> [BugFix] Skip identity conversions for 8-bit and 16-bit types

glslang/Include/Common.h, glslang/MachineIndependent/PoolAlloc.cpp, glslang/MachineIndependent/ShaderLang.cpp
I was looking into compiling glslang for [WASM WASI](https://wasi.dev/) target, and I successfully did so by removing some reference to threads as WASI does not support threads yet. 
So here is a small PR that disable thread safety in order to allow compilation for WASI, the preprocessor guarding is safe so this should not impact anything other than WASI target.
=> Fix compilation for WASI target

SPIRV/spirv.hpp
I build my engine with Zig, which enables LLVM's [Undefined Behavior Sanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) by default in debug builds. UBSAN caught undefined behavior during shader compilation at the following location:
```
0.  0x000000000426e391 in spv::operator& (a=spv::MemoryAccessMaskNone,
b=(spv::MemoryAccessVolatileMask | spv::MemoryAccessAlignedMask | spv::MemoryAccessNontemporalMask | spv::MemoryAccessMakePointerVisibleMask | spv::MemoryAccessNonPrivatePointerMask | spv::MemoryAccessAliasScopeINTELMaskMask | spv::MemoryAccessNoAliasINTELMaskMask | unknown: 0xfffcffc0)) at SPIRV/spirv.hpp:2804
1.  0x00000000041e81e0 in (anonymous namespace)::TGlslangToSpvTraverser::accessChainLoad (this=0x7fffffffcbb8, type=...) at SPIRV/GlslangToSpv.cpp:5127
2. …
```
=> Fixes undefined behavior due to unspecified bitflag enum backing

StandAlone/CMakeLists.txt
This caused the `glslang[tools]` vcpkg feature to not install properly, because the `glslangValidator` executable didn't exist for tool installation.
=> Fix `glslangValidator` installation

kokoro/linux-clang-cmake/build-docker.sh, kokoro/linux-gcc-cmake/build-docker.sh
=> kokoro: use Python 3.12 for Linux builds

.github/workflows/continuous_deployment.yml
Our github continuous delivery workflow appears to be failing for macOS, possibly because the requested version of the OS is too old.
=> Update macOS requirement from 11 to 12 in github CD workflow

Test/baseResults/matrixCompMult.vert.out, Test/matrixCompMult.vert, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/Intermediate.cpp, gtests/AST.FromFile.cpp
glslang report error for  "const mat2 cval = matrixCompMult(mat2(1.0), mat2(1.0));".
Spec says:
The value returned by certain built-in function calls whose arguments are all constant expressions is also constant expressions.
=> Support constant expression calculated by matrixCompMult.

.github/workflows/continuous_integration.yml, glslang/HLSL/hlslParseHelper.cpp, glslang/MachineIndependent/Constant.cpp, glslang/MachineIndependent/localintermediate.h, glslang/MachineIndependent/preprocessor/Pp.cpp
This fixes a couple of integer overflows in parsing as well as removes the construction of a null reference that never got dereferenced.
This PR also adds UBSAN testing to CI.
Fixes #2795
=> Fix undefined behaviors caught by ubsan

glslang/MachineIndependent/linkValidate.cpp
This adds some documentation of the checkTypes() function to make clearer what exactly it is checking. A bit of a cleanup after #3661.
=> Add some comments and rename a helper function

glslang/MachineIndependent/ShaderLang.cpp
This PR adds missing calls to SetThreadPoolAllocator() in TProgram functions which allocate and/or free memory and are part of glslang's public interface. Without these calls crashes can occur upon calling these functions in debug builds of glslang on Windows.
=> Fix missing calls to SetThreadPoolAllocator() in TProgram public interface functions

glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h
This PR implements C versions of some functionality which is part of glslang's public C++ interface but currently missing from the C interface.
The first commit adds a C equivalent to glslang::GetVersion().
The second commit adds a function to directly supply preprocessed shader code, bypassing glslang's built-in preprocessor. This is useful for avoiding unnecessary double preprocessing overhead in scenarios where shader code has already been preprocessed once upstream (for example by a slower but more fully-featured preprocessor).
The third commit adds types and functions which provide additional control of glslang's IO mapping functionality. Together these functions allow for C interface users to make use of use of glslang's TGlslIoMapper and TDefaultGlslIoResolver mapper and resolver, …
=> Additional C interface functions

Test/baseResults/iomap.crossStage.vk.2.vert.out, Test/iomap.crossStage.vk.2.frag, Test/iomap.crossStage.vk.2.geom, Test/iomap.crossStage.vk.2.vert, glslang/MachineIndependent/linkValidate.cpp, gtests/GlslMapIO.FromFile.cpp
If an 'in' is present in a shader stage, make sure a matching 'out' is present in the previous stage. Only enabled when doing Vulkan.
This commit also fixes a bug where previous stage's linkerObjects got polluted with 'in' variables from the next stage when merging linker objects.
=> add cross-stage check for missing outputs

SPIRV/CInterface/spirv_c_interface.cpp, SPIRV/CMakeLists.txt, SPIRV/SpvTools.cpp, SPIRV/SpvTools.h
Clean up the includes in SpvTools.h so that it doesn't require any transitive dependencies and add it back to the headers that get installed.
=> Add SPIRV/SpvTools.h back to the public headers

SPIRV/GlslangToSpv.h, SPIRV/SpvTools.cpp, glslang/Include/glslang_c_interface.h
This option increases the max_id_bound in the optimizer to 0x3FFFFFFF, and then runs a compact-id pass if the final result has a max_id greater than the standard limit of 0x3FFFFF.
=> add optimizerAllowExpandedIDBound to SpvOptions

glslang/MachineIndependent/ParseHelper.cpp
... that 8/16-bit composites can't be directly constructed.
Earlier the comment looked misleading that composites of 8/16-bit types can't be constructed at all. As per the GL_EXT_shader_16bit_storage extension, they can't be constructed directly, however, can be constructed indirectly.
=> Update comment to more succint for 8/16-bit types

SPIRV/SpvBuilder.h
Without the change `glslang` build fails on upcoming `gcc-15` as:
In file included from /build/source/SPIRV/GlslangToSpv.cpp:45:
SPIRV/SpvBuilder.h:248:30: error: 'uint32_t' has not been declared
248 |     Id makeDebugLexicalBlock(uint32_t line);
|                              ^~~~~~~~
=> SPIRV/SpvBuilder.h: add missing <cstdint> include

glslang/CInterface/glslang_c_interface.cpp, glslang/CMakeLists.txt, glslang/MachineIndependent/iomapper.cpp, glslang/MachineIndependent/iomapper.h, gtests/GlslMapIO.FromFile.cpp
Clean up iomapper.h to make it suitable as a public API
Remove the dependency on LiveTraverser.h, which transitively includes localintermediate.h. As a result, some things have been moved from iomapper.h to iomapper.cpp, specifically the TVarEntry type and the constructor and destructor of TGlslIoMapper.
Add MachineIndependent/iomapper.h to the list of installed headers.
Fixes #3681
=> Iomapper api cleanup

glslang/MachineIndependent/ShaderLang.cpp, glslang/Public/ShaderLang.h
These are now accessible through the C++ ShaderLang.h public API as well as the C API.
Fixes #3691
=> Add setSourceFile and addSourceText to TShader

.github/workflows/continuous_integration.yml
It's not necessary to run the runtest tests separately, as they're already being run by the ctest testing process (as glslang-testsuite).
=> ci: Get rid of redundant testing

BUILD.gn, glslang/CMakeLists.txt, glslang/Include/glslang_c_interface.h, glslang/Include/visibility.h, glslang/Public/ShaderLang.h
The GLSLANG_EXPORT macro is already used (and defined) in two separate places and will be used in a few more in the near future. To reduce duplication it is now in its own header.
=> Move definition of GLSLANG_EXPORT to visibility.h

Test/baseResults/preprocess.inactive_stringify.vert.out, Test/preprocess.inactive_stringify.vert, glslang/MachineIndependent/preprocessor/Pp.cpp, glslang/MachineIndependent/preprocessor/PpContext.cpp, glslang/MachineIndependent/preprocessor/PpContext.h, gtests/Pp.FromFile.cpp
Don't report the following error when scanning inactive code (e.g. code inside #if 0): "error: '#' : (#) can be preceded in its line only by spaces or horizontal tab" Adds a variable to PpContext to say whether we're currently skipping over an inactive #if/#ifdef/#elif/#else, and don't report the error inside scanToken if true.
fixes 3704
=> PP: Don't report certain error about '#' when #if'd out

SPIRV/GlslangToSpv.h, SPIRV/Logger.h, SPIRV/SpvTools.h, SPIRV/disassemble.h
Symbols in the SPIRV/ directory that are meant to be part of the public API of glslangnow have GLSLANG_EXPORT annotations that make sure they will be accessible when building glslang as a shared library if -fvisibility=hidden is enabled.
Fixes #2308
=> Add symbol visibility annotations to symbols in SPIRV/

.github/workflows/continuous_deployment.yml
The runtests script is already run as part of the cmake-controlled testing, so can be removed from the CD workflow like it was from the CI ones.
=> ci: Remove redundant testing from continuous deployment workflow

gtests/GlslMapIO.FromFile.cpp, gtests/Link.FromFile.Vk.cpp, gtests/TestFixture.h, gtests/VkRelaxed.FromFile.cpp
This means the tests won't need to have this entrypoint exposed when building as a shared library with hidden symbols.
=> Remove redundant calls to spv::Parameterize() from tests

glslang/HLSL/hlslScanContext.cpp, glslang/MachineIndependent/Scan.cpp, glslang/MachineIndependent/ShaderLang.cpp
Rather than having a function that needs to be called from ShInitialize to initialize some global costants, convert them to use static initializers. This also ends up saving a bit of space in the binary, especially when building with GCC.
=> Convert keyword maps to static initializers

glslang/CMakeLists.txt, glslang/Public/ResourceLimits.h, glslang/Public/resource_limits_c.h
Among other things, this allows using it as a DLL on Windows because unlike Linux, the default on windows is hidden visibility unless things are explicitly exported.
=> Add symbol visibility annotations to glslang-resource-limits library

SPIRV/CMakeLists.txt, SPIRV/SPVRemapper.h
Windows requires symbols to be explicitly exported from DLLs, this change simply marks the entire spirvbin_t class as exported.
The macros from visibility.h are included inline to get around include path issues.
Fixes #3716
=> Explicitly export symbols from libSPVRemapper

glslang/CMakeLists.txt, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/iomapper.h, glslang/Public/ShaderLang.h, gtests/GlslMapIO.FromFile.cpp, gtests/VkRelaxed.FromFile.cpp
The TProgram::mapIO method takes a TIoMapResolver and a TIoMapper, however the only way to obtain instances of these was from methods in iomapper.h. Rather than try to expose that header as part of the API, new methods are added to the public ShaderLang.h header to create a TDefaultGlslIoResolver and a TGlslIoMapper and return them as pointers to their respective base classes, which are defined in the public header.
Also update the tests to use these new public entry points, rather than relying on private ones.
Fixes #3681
=> Improved iomapper api

glslang/CInterface/glslang_c_interface.cpp, glslang/Include/glslang_c_interface.h
This adds `glslang_shader_set_resource_set_binding()` to the C API as a counterpart to `setResourceSetBinding()`. I need this to set the descriptor set for automatically mapped samplers when compiling legacy OpenGL shaders in Vulkan mode with relaxed semantics.
=> Expose setResourceSetBinding() method to the C API

BUILD.gn
After commit d7d5ab8, projects based on
gn builds failed when running command:
gn gen out/<BUILDDIR> --check
```
ERROR at //third_party/glslang/src/glslang/Public/ResourceLimits.h:41:11: Include not allowed.
^----------------------
It is not in any dependency of
//third_party/glslang/src:glslang_default_resource_limits_sources
```
Add the visibility.h to the build target
glslang_default_resource_limits_sources
to fix the error.
=> Fix gn build error

BUILD.gn
The cmake build recently got ENABLE_SPIRV which is enabled by default. This was missing from the GN build, accidentally removing SPIR-V support in this build.
=> Fix SPIR-V support in GN build

CMakeLists.txt, StandAlone/StandAlone.cpp
This case fails slightly less silently now.
Also make ENABLE_OPT depend on ENABLE_SPIRV, since when there's no SPIR-V optimization doesn't really make sense.
=> Print an error when SPIR-V is requested and ENABLE_SPIRV=0 is set

SPIRV/SpvTools.cpp, SPIRV/SpvTools.h, glslang/Include/Types.h, glslang/MachineIndependent/iomapper.h, glslang/Public/ShaderLang.h
expose TIoMapper::setAutoPushConstantBlock()
add overload for MapToSpirvToolsEnv() that takes TIntermediate instead of SpvVersion.
=> A few more tweaks for #3681

glslang/CInterface/glslang_c_interface.cpp, glslang/MachineIndependent/SymbolTable.cpp
The `%p` specifier expects a void pointer argument, so explicitly cast to `void *`.
No functional changes.
=> Fix Wformat warnings for printf `%p`

glslang/MachineIndependent/Initialize.cpp
This is needed to fix the below errors on some compilers:
Initialize.cpp:4476:27: error: implicit instantiation of undefined template 'std::basic_stringstream'
std::stringstream cooperativeMatrixFuncs;
=> Add missing <sstream> header include

Test/baseResults/spv.bufferhandle_Error.frag.out, Test/spv.bufferhandle_Error.frag, glslang/MachineIndependent/ParseHelper.cpp
closes https://github.com/KhronosGroup/glslang/issues/3774
Now something like
```
#version 450
#extension GL_EXT_buffer_reference : enable
layout(buffer_reference, std140) buffer StructB;
layout(buffer_reference) buffer StructB {
vec4 x;
};
void main() {}
```
will give a warning of
`WARNING: test.comp:4: 'StructB' : the packing layout (scalar, std430, etc) is ignored when defined in forward declaration `
=> Add warning if Forward Declaration uses layout qualifiers

README.md
The bit about CMAKE_MSVC_RUNTIME_LIBRARY has lost all context. Originally it was related to OVERRIDE_MSVCCRT. Removing it fully is more clear.
Cleanup the configure instructions. Using newer CMake cli.
Remove bit about the CMake GUI being tested. Doesn't make sense to have in the README.md
Remove section about GLSLANG_TESTS. This documentation is now outdated.
=> Cleanup old CMake related docs in readme.md

glslang/MachineIndependent/iomapper.cpp
Ensure all copies of the global uniform block symbol get updated with the correct layoutPacking when it's auto upgraded to a push_constant. In some cases there are multiple copies, and only one was getting changed previously.
=> Improve auto push_constants upgrading.

.github/workflows/continuous_integration.yml
Turns out gcc on macos by default is just an alias for clang, so these configurations were adding no value at all.
=> ci: Remove gcc from macos matrix

.github/workflows/continuous_integration.yml, CMakeLists.txt, gtests/CMakeLists.txt, kokoro/linux-clang-cmake/build-docker.sh, kokoro/linux-gcc-cmake/build-docker.sh
Enable Windows DLL test configuration.
Configure tests to pull in DLL dependencies using `TARGET_RUNTIME_DLL_DIRS`.
Bump cmake version to 3.27 to use `TARGET_RUNTIME_DLL_DIRS`.
Remove Ubuntu 20.04 test configuration.
=> Fix Windows DLL test configuration

.github/workflows/continuous_integration.yml, CMakeLists.txt, gtests/CMakeLists.txt
Enable building on older versions of CMake.
Add warning for Windows shared library test configuration.
=> Re-add linux back compat test

SPIRV/GlslangToSpv.cpp
=> Fix incorrect extension dependency for Modf

StandAlone/StandAlone.cpp
This is for C++ modules build in chromium.
=> Add missing include headers

glslang/Include/glslang_c_interface.h
Fixes strict-prototypes warning
```
warning: function declaration isn’t a prototype [-Wstrict-prototypes]
```
=> Fix glslang_glsl_mapper_create prototype

CMakeLists.txt, glslang/OSDependent/Web/CMakeLists.txt
- Remove old style of ending functions/conditions
- MSVC RTTI flag /GR is not added to CMAKE_CXX_FLAGS by default anymore.
- Remove unneccessary pre 3.18 code path
=> cmake: Cleanup CMake code

.github/workflows/continuous_integration.yml
"error: emscripten requires python 3.8 or above"
=> ci: Fix emscripten build

SPIRV/GlslangToSpv.cpp, SPIRV/doc.cpp, Test/baseResults/spv.ext.RayGenShader.rgen.out
If the `GL_EXT_opacity_micromap` extension was requested in the input, emit the corresponding `SPV_EXT_opacity_micromap` extension and RayTracingOpacityMicromapEXT Capability in the SPIR-V output.
=> Emit SPV_EXT_opacity_micromap if GL extension is present

.github/workflows/continuous_integration.yml, SPIRV/CMakeLists.txt, StandAlone/spirv-remap.cpp, Test/find_package/CMakeLists.txt, Test/find_package/example.c, Test/find_package/stub.cpp
Fix find_package breaking on Windows when BUILD_SHARED_LIBS=ON due to SPIRV stub library.
Changed exit code for spirv-remap to 0 when requesting help, to allow for better integration testing.
closes #3462
=> ci: Add find_package testing

kokoro/android-ndk-build/build.sh, kokoro/linux-clang-cmake/build.sh, kokoro/linux-clang-gn/build.sh, kokoro/linux-gcc-cmake/build.sh
=> kokoro: linux: use cpp-builder image instead of radial-build

glslang/MachineIndependent/Scan.cpp
When the extension is disabled, `nontemporal` can be used as a normal identifier.
=> EXT_nontemporal_keyword: Don't warn when using nontemporal as an identifier

CMakeLists.txt, External/CMakeLists.txt, StandAlone/CMakeLists.txt
Highlight policy CMP0143 for future reference
Use GENERATOR_IS_MULTI_CONFIG for detecting multi configuration generators
Don't set CMAKE_BUILD_TYPE when using multi configuration generators.
Misc endif cleanup for modernization
Use lower case version of cmake_dependent_option for consistency with rest of codebase.
Use add_compile_definitions instead of add_definitions
Minor indentation for readability
Use MINGW variable where applicable
Use target_link_options instead of old LINK_FLAGS
=> cmake: Minor CMake cleanup

.github/workflows/continuous_deployment.yml, .github/workflows/continuous_integration.yml
Only keep it to test back compat for older versions of python.
Reduces CI cache misses which can be up to 1 minute when they happen.
=> ci: Reduce usage of setup-python

StandAlone/CMakeLists.txt, gtests/CMakeLists.txt
Until gcc 9, users of `std::filesystem` had to explicitly link against libstdc++fs.
=> Fix pre-gcc-9 builds for libstdc++fs

.github/workflows/continuous_deployment.yml
Remove package that was required when CI was ported from Travis but is no longer required.
=> Fix continuous deployment

Test/baseResults/liveTraverser.switch.vert.out, Test/liveTraverser.switch.vert, glslang/Include/PoolAlloc.h, glslang/MachineIndependent/LiveTraverser.h, gtests/CMakeLists.txt, gtests/LiveTraverser.FromFile.cpp
This PR improves LiveTraverser to no longer traverse switch cases that can be determined at compile time to not be live. This change is also a prerequisite for correct error reporting in cross-stage link-time IO validation, which necessarily depends on accurate information about IO variables' liveness.
A consequence of this change is that IO variables whose only access occurs in code paths which aren't live (now including switch cases) are no longer assigned bindings or locations by the IO mapper, which is how it already works now with if statements.
=> LiveTraverser no longer traverses switch cases that are statically not accessed

CMakeLists.txt
- Remove `-fno-exceptions` from unconditional compilation flags
It's added conditionally depending on the CMake option a few lines below.
=> Fix exceptions being unconditionally disabled on GCC

StandAlone/StandAlone.cpp, Test/baseResults/link.crossStageIO.0.vert.out, Test/baseResults/link.crossStageIO.1.vert.out, Test/baseResults/link.missingCrossStageIO.0.vert.out, Test/baseResults/link.vk.crossStageIO.0.vert.out, Test/baseResults/link.vk.crossStageIO.1.vert.out, Test/baseResults/link.vk.missingCrossStageIO.0.vert.out, Test/baseResults/validation_fails.txt, Test/link.crossStageIO.0.frag, Test/link.crossStageIO.0.vert, Test/link.crossStageIO.1.frag, Test/link.crossStageIO.1.geom, Test/link.crossStageIO.1.vert, Test/link.missingCrossStageIO.0.frag, Test/link.missingCrossStageIO.0.vert, Test/link.vk.crossStageIO.0.frag, Test/link.vk.crossStageIO.0.vert, Test/link.vk.crossStageIO.1.frag, Test/link.vk.crossStageIO.1.geom, Test/link.vk.crossStageIO.1.vert, Test/link.vk.missingCrossStageIO.0.frag, Test/link.vk.missingCrossStageIO.0.vert, glslang/Include/glslang_c_shader_types.h, glslang/MachineIndependent/ShaderLang.cpp, glslang/MachineIndependent/linkValidate.cpp, glslang/MachineIndependent/localintermediate.h, glslang/Public/ShaderLang.h, gtests/Link.FromFile.Vk.cpp, gtests/Link.FromFile.cpp, gtests/TestFixture.cpp
glslang does not currently have logic to detect when cross-stage IO statically accessed in one stage is missing in the previous stage, and there is a longstanding TODO comment in the existing TIntermediate::checkStageIO() function suggesting that such functionality should be implemented. To that end, this PR implements the proposed cross-stage link time IO validation and introduces a new EShMessages flag to optionally enable it. If the user does not explicitly opt in to this functionality by supplying the new flag, the behavior of linking remains unchanged from how it worked prior to this PR.
When enabled, the new cross-stage IO validation functionality aims to validate that statically read cross-stage input locations have corresponding output declarations in the previous stage. It also …
=> Implement optional cross-stage check for input with no matching output

CMakeLists.txt
BUILD_SHARED_LIBS is a built in CMake variable. Because the code simply declares the varriable (ie, doesn't change the default value), it was redundant and caused confusion for users unfamiliar with CMake & its built in's.
CMake documentation for the curious:
https://github.com/KhronosGroup/glslang/compare/main...charles-lunarg:glslang:remove_built_in_cmake_option?expand=1
=> cmake: Remove BUILD_SHARED_LIBS option

SPIRV/GLSL.ext.ARM.h, SPIRV/GLSL.ext.EXT.h
This is a vendor extension that was accidentally added into the EXT header.
=> Move E_SPV_ARM_cooperative_matrix_layouts into GLSL.ext.ARM.h

Test/runtests
Bash-like environments in Windows have a 32k command line limit. Eventually the number of tests exceeded that.
=> Workaround Windows command line limit

SPIRV/doc.cpp, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.16BitAccess.comp.out, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.8BitAccess.comp.out, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.MultiBlock.comp.out, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.SingleBlock.comp.out, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.scalar.comp.out, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.std140.comp.out, Test/baseResults/spv.WorkgroupMemoryExplicitLayout.std430.comp.out, Test/baseResults/spv.bfloat16.comp.out, Test/baseResults/spv.coopvec.comp.out, Test/baseResults/spv.coopvec2.comp.out, Test/baseResults/spv.floate4m3.comp.out, Test/baseResults/spv.floate4m3.const.comp.out, Test/baseResults/spv.floate5m2.comp.out, Test/baseResults/spv.floate5m2.const.comp.out, Test/baseResults/spv.fsi.frag.out, Test/baseResults/spv.nv.dmm-allops.rahit.out, Test/baseResults/spv.nv.dmm-allops.rchit.out, Test/baseResults/spv.nv.dmm-allops.rgen.out, Test/baseResults/spv.replicate.comp.out, Test/baseResults/spv.replicatespec.comp.out, Test/baseResults/spv.subgroupExtendedTypesRotate.comp.out, Test/baseResults/spv.subgroupRotate.comp.out
This fixes #4018
Capability names do not include the "Capability" prefix, but some capabilities where being labeled with it. This PR addresses the inconsistency.
Tests adjusted to match the new labels.
=> Fix inconsistent labeling of capability strings

Test/baseResults/validation_fails.txt, Test/baseResults/vk.relaxed.syntaxerror.vert.out, Test/vk.relaxed.syntaxerror.frag, Test/vk.relaxed.syntaxerror.vert, glslang/Include/Types.h, glslang/MachineIndependent/ParseHelper.cpp, gtests/VkRelaxed.FromFile.cpp
Old OpenGL-compatible code was allowed to contain variables named `sampler`.
This is not true under Vulkan semantics anymore, as this has become a reserved keyword.
Compiling shaders with function parameters named like this generates an unnamed parameter followed by a `SAMPLER` token.
Before this fix, such behaviour resulted in a segfault, as `vkRelaxedRemapFunctionParameter()` always expected the input variable to be named.
This PR addresses this issue by adding a function to check whether a type has a field name, and if not, `vkRelaxedRemapFunctionParameter()` generates all variables without prefixing them with anything.
=> Fix crash on unnamed function parameters under relaxed rules
